*&---------------------------------------------------------------------*
*& Report  ZSTORE1
*& DEVELOPED BY JYOTSNA ON 3.12.2012 FOR PURCHASE DEPT OT GET DATA PROPER FORMAT
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZSTORE2 NO STANDARD PAGE HEADING LINE-SIZE 400.
TABLES : EKET,
         EKKO,
         EKPO,
         LFA1,
         EKKN,
         T161T,
         LFB1,
         EKPA,
         CSKT.


TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.

DATA : IT_EKET TYPE TABLE OF EKET,
       WA_EKET TYPE EKET,
       IT_EKKO TYPE TABLE OF EKKO,
       WA_EKKO TYPE EKKO,
       IT_EKPO TYPE TABLE OF EKPO,
       WA_EKPO TYPE EKPO.

TYPES : BEGIN OF ITAB1,
          AEDAT      TYPE EKKO-AEDAT,
          AEDAT1     TYPE EKKO-AEDAT,
          EBELN      TYPE EKET-EBELN,
          EINDT      TYPE EKET-EINDT,
          EBELP      TYPE EKET-EBELP,
          J_1BNBM    TYPE EKPO-J_1BNBM,
          LIFNR      TYPE EKKO-LIFNR,
          MATNR      TYPE EKPO-MATNR,
          TXZ01      TYPE EKPO-TXZ01,
          LGORT      TYPE EKPO-LGORT,
          MENGE      TYPE EKPO-MENGE,
          MEINS      TYPE EKPO-MEINS,
          ELIKZ      TYPE EKPO-ELIKZ,
          NAME1      TYPE LFA1-NAME1,
          ORT01      TYPE LFA1-ORT01,
          WEMNG      TYPE EKET-WEMNG,
          QTY        TYPE EKET-WEMNG,
          KNTTP      TYPE EKPO-KNTTP,
          SAKTO      TYPE EKKN-SAKTO,
          KOSTL      TYPE EKKN-KOSTL,
          GSBER      TYPE EKKN-GSBER,
          ANLN1      TYPE EKKN-ANLN1,
          ANLN2      TYPE EKKN-ANLN2,
          STATUS1(6) TYPE C,
          BEDAT      TYPE EKET-BEDAT,
          NETWR      TYPE EKPO-NETWR,
          WAERS      TYPE EKKO-WAERS,
          WERKS      TYPE EKPO-WERKS,
          BATXT      TYPE T161T-BATXT,
          NETPR      TYPE EKPO-NETPR,
          PEINH      TYPE EKPO-PEINH,
          PEN_VAL    TYPE P DECIMALS 2,
          MBLNR      TYPE MSEG-MBLNR,
          BUDAT      TYPE EKBE-BUDAT,
          UEBTO      TYPE EKPO-UEBTO,
          BEDNR      TYPE EKPO-BEDNR,
          AFNAM      TYPE EKPO-AFNAM,
          CHARG      TYPE EKET-CHARG,
          LICHA      TYPE EKET-LICHA,
          MSME       TYPE LFB1-MINDK,
          STCD1      TYPE LFA1-STCD1,
          STCD3      TYPE LFA1-STCD3,
          SPERM      TYPE LFA1-SPERM,

          MFGR       TYPE LFA1-LIFNR,
          MNAME1     TYPE LFA1-NAME1,
          MORT01     TYPE LFA1-ORT01,
          MSTRAS     TYPE LFA1-STRAS,
          MPSTLZ     TYPE LFA1-PSTLZ,
          ZTERM      TYPE EKKO-ZTERM,
          ZBD1T      TYPE EKKO-ZBD1T,
          RETPO      TYPE EKPO-RETPO,
          MATKL      TYPE EKPO-MATKL,
          MWSKZ      TYPE EKPO-MWSKZ,
          bsart TYPE ekko-BSART,
        END OF ITAB1.

TYPES : BEGIN OF ITAB11,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          BWART TYPE MSEG-BWART,
          SMBLN TYPE MSEG-SMBLN,
          EBELN TYPE EKBE-EBELN,
          EBELP TYPE EKBE-EBELP,
          BUDAT TYPE EKBE-BUDAT,
        END OF ITAB11.

TYPES : BEGIN OF REC1,
          EBELN TYPE EKET-EBELN,
          EBELP TYPE EKET-EBELP,
          QTY   TYPE EKET-WEMNG,
        END OF REC1.

TYPES : BEGIN OF ITAB3,
          KOSTL TYPE EKKN-KOSTL,
          EBELN TYPE EKPO-EBELN,
          NAME1 TYPE LFA1-NAME1,
          NETWR TYPE EKPO-NETWR,


          MENGE TYPE EKPO-MENGE,
          MEINS TYPE EKPO-MEINS,
          WEMNG TYPE EKET-WEMNG,
          QTY   TYPE EKET-WEMNG,
          LTEXT TYPE CSKT-LTEXT,
          AEDAT TYPE EKKO-AEDAT,
        END OF ITAB3.

TYPES: BEGIN OF ITAB31,
         MATNR TYPE MARA-MATNR,
         LIFNR TYPE LFA1-LIFNR,
         WERKS TYPE MCHA-WERKS,
         TXZ01 TYPE EKPO-TXZ01,
         MEINS TYPE MARA-MEINS,
         MWSKZ TYPE EKPO-MWSKZ,
         NETPR TYPE EKPO-NETPR,
       END OF ITAB31.

DATA : IT_TAB1  TYPE TABLE OF ITAB1,
       WA_TAB1  TYPE ITAB1,
       IT_TAB2  TYPE TABLE OF ITAB1,
       WA_TAB2  TYPE ITAB1,
       IT_TAB31 TYPE TABLE OF ITAB31,
       WA_TAB31 TYPE ITAB31,
       IT_TAB3  TYPE TABLE OF ITAB3,
       WA_TAB3  TYPE ITAB3,
       IT_TAB11 TYPE TABLE OF ITAB11,
       WA_TAB11 TYPE ITAB11,
       IT_TAB12 TYPE TABLE OF ITAB11,
       WA_TAB12 TYPE ITAB11,
       IT_REC1  TYPE TABLE OF REC1,
       WA_REC1  TYPE REC1.

DATA : MESG(40) TYPE C,
       A        TYPE EKET-WEMNG.

DATA : PQTY TYPE P.

DATA: IT_EKBE      TYPE TABLE OF EKBE,
      WA_EKBE      TYPE EKBE,
      IT_MSEG      TYPE TABLE OF MSEG,
      WA_MSEG      TYPE MSEG,
      IT_ZPO_PRINT TYPE TABLE OF ZPO_PRINT,
      WA_ZPO_PRINT TYPE ZPO_PRINT.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE2 WITH FRAME TITLE TEXT-001.
PARAMETERS : R1  RADIOBUTTON GROUP R1 USER-COMMAND R2 DEFAULT 'X',
             R1A RADIOBUTTON GROUP R1,
             R1B RADIOBUTTON GROUP R1,
             R2  RADIOBUTTON GROUP R1,
             R3  RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK MERKMALE2.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
*parameters : org like ekko-ekorg obligatory.
SELECT-OPTIONS : ORG FOR EKKO-EKORG .
SELECT-OPTIONS : PO FOR EKPO-EBELN.
SELECT-OPTIONS : S_DATE FOR EKKO-AEDAT .
SELECT-OPTIONS : VENDOR FOR EKKO-LIFNR.
SELECT-OPTIONS : MATERIAL FOR EKPO-MATNR.
SELECT-OPTIONS : PO_TYP FOR EKKO-BSART.
SELECT-OPTIONS : HSN FOR EKPO-J_1BNBM.
SELECTION-SCREEN END OF BLOCK MERKMALE1 .

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE3 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: PURDT FOR SY-DATUM.
SELECTION-SCREEN END OF BLOCK MERKMALE3 .


AT SELECTION-SCREEN OUTPUT.
  IF R3 EQ 'X'.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PURDT*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.

    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*ORG*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PO*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*S_DATE*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*VENDOR*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*MATERIAL*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PO_TYP*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*HSN*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.


  ELSE.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PURDT*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.


    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*ORG*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PO*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*S_DATE*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*VENDOR*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*MATERIAL*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*PO_TYP*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*HSN*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.

  ENDIF.

INITIALIZATION.
  G_REPID = SY-REPID.



*at selection-screen.
*  authority-check object '/DSD/SL_WR'
*           id 'WERKS' field plant.
*
*  if sy-subrc ne 0.
*    mesg = 'Check your entry'.
*    message mesg type 'E'.
*  endif.


START-OF-SELECTION.

  IF R3 NE 'X'.
    IF ORG EQ SPACE.
      MESSAGE 'ENTER PURCHASE ORGANIZATION' TYPE 'E'.
    ENDIF.
    IF S_DATE-LOW LE 0.
      MESSAGE 'ENTER PO CREATION  FROM  DATE' TYPE 'E'.
    ENDIF.
    IF S_DATE-HIGH LE 0.
      MESSAGE 'ENTER PO CREATION  TO  DATE' TYPE 'E'.
    ENDIF.
  ENDIF.

  IF R3 EQ 'X'.
    PERFORM POPRINTSTAT.
  ELSE.

*  select * from ekko into table it_ekko where bukrs eq 'BCLL'  and ebeln in po and aedat in s_date and lifnr in vendor and ekorg in org
*    and bsart in po_typ.
    SELECT * FROM EKKO INTO TABLE IT_EKKO WHERE EBELN IN PO AND AEDAT IN S_DATE AND LIFNR IN VENDOR AND EKORG IN ORG
    AND BSART IN PO_TYP.
    IF SY-SUBRC NE 0.
      EXIT.
    ENDIF.

    IF IT_EKKO IS NOT INITIAL.
      SELECT * FROM EKPO INTO TABLE IT_EKPO FOR ALL ENTRIES IN IT_EKKO WHERE EBELN = IT_EKKO-EBELN AND MATNR IN MATERIAL
      AND LOEKZ EQ ' ' AND J_1BNBM IN HSN.
*      and elikz ne 'X' and statu ne 'A'
      IF SY-SUBRC EQ 0.
        SELECT * FROM EKET INTO TABLE IT_EKET FOR ALL ENTRIES IN IT_EKPO WHERE EBELN EQ IT_EKPO-EBELN AND EBELP EQ IT_EKPO-EBELP.
      ENDIF.
    ENDIF.

    IF IT_EKET IS NOT INITIAL.
      LOOP AT IT_EKET INTO WA_EKET.
        WA_REC1-EBELN = WA_EKET-EBELN.
        WA_REC1-EBELP = WA_EKET-EBELP.
        WA_REC1-QTY = WA_EKET-WEMNG.
        COLLECT WA_REC1 INTO IT_REC1.
        CLEAR WA_REC1.
      ENDLOOP.
    ENDIF.
    IF IT_EKPO IS NOT INITIAL.
      LOOP AT IT_EKPO INTO WA_EKPO .
*    from sy-tabix.
        READ TABLE IT_EKKO INTO WA_EKKO WITH KEY EBELN = WA_EKPO-EBELN.
        IF SY-SUBRC EQ 0.
*      write :  / wa_ekPo-aedat,wa_ekpo-ebeln,wa_ekpo-eindt,wa_ekpo-ebelp,wa_ekko-lifnr,wa_ekpo-matnr,wa_ekpo-txz01,
*                 wa_ekpo-lgort,wa_ekpo-menge,wa_ekpo-meins, wa_ekpo-elikz.
          wa_tab1-BSART = wa_ekko-BSART.
          WA_TAB1-EBELN = WA_EKPO-EBELN.
          WA_TAB1-MWSKZ = WA_EKPO-MWSKZ.
          WA_TAB1-EBELP = WA_EKPO-EBELP.
          WA_TAB1-ZTERM = WA_EKKO-ZTERM.
          WA_TAB1-ZBD1T = WA_EKKO-ZBD1T.
          WA_TAB1-J_1BNBM = WA_EKPO-J_1BNBM.
          WA_TAB1-UEBTO = WA_EKPO-UEBTO.
          WA_TAB1-WERKS = WA_EKPO-WERKS.
          WA_TAB1-AEDAT = WA_EKKO-AEDAT.
          WA_TAB1-PEINH = WA_EKPO-PEINH.
          WA_TAB1-AEDAT1 = WA_EKPO-AEDAT.
          WA_TAB1-KNTTP = WA_EKPO-KNTTP.
          WA_TAB1-MATNR = WA_EKPO-MATNR.
          WA_TAB1-RETPO = WA_EKPO-RETPO.
          WA_TAB1-MATKL = WA_EKPO-MATKL.
*      wa_tab1-wemng = wa_ekpo-wemng.
          WA_TAB1-NETWR = WA_EKPO-NETWR.
          WA_TAB1-NETPR = WA_EKPO-NETPR.
          WA_TAB1-WAERS = WA_EKKO-WAERS.
          WA_TAB1-EBELP = WA_EKPO-EBELP.
          WA_TAB1-LIFNR = WA_EKKO-LIFNR.
          WA_TAB1-TXZ01 = WA_EKPO-TXZ01.
          WA_TAB1-LGORT = WA_EKPO-LGORT.
          WA_TAB1-MENGE = WA_EKPO-MENGE.   " change of EKPO insted of ekpo.
          WA_TAB1-MEINS = WA_EKPO-MEINS.
          WA_TAB1-ELIKZ = WA_EKPO-ELIKZ.
          WA_TAB1-BEDNR = WA_EKPO-BEDNR.
          WA_TAB1-AFNAM = WA_EKPO-AFNAM.

          SELECT SINGLE * FROM LFB1 WHERE LIFNR EQ WA_EKKO-LIFNR AND MINDK EQ 'MSM'.
          IF SY-SUBRC EQ 0.
            WA_TAB1-MSME = LFB1-MINDK.
          ENDIF.

          SELECT SINGLE * FROM EKKN WHERE EBELN EQ WA_EKPO-EBELN AND EBELP EQ WA_EKPO-EBELP.
          IF SY-SUBRC EQ 0.
            WA_TAB1-KOSTL = EKKN-KOSTL.
            WA_TAB1-ANLN1 = EKKN-ANLN1.
            WA_TAB1-ANLN2 = EKKN-ANLN2.
          ENDIF.

*      WA_TAB1-EINDT = WA_EKPO-EINDT.
          IF WA_EKPO-ELIKZ EQ 'X'.
            WA_TAB1-STATUS1 = 'CLOSED'.
          ELSE.
            WA_TAB1-STATUS1 = 'OPEN'.
          ENDIF.
          SELECT SINGLE * FROM T161T WHERE BSART EQ WA_EKKO-BSART AND SPRAS EQ 'EN' AND BSTYP = 'F'.
          IF SY-SUBRC EQ 0.
            WA_TAB1-BATXT = T161T-BATXT.
          ENDIF.
          READ TABLE IT_EKET INTO WA_EKET WITH KEY EBELN = WA_EKPO-EBELN EBELP = WA_EKPO-EBELP.
          IF SY-SUBRC EQ 0.
            WA_TAB1-LICHA = WA_EKET-LICHA.
            WA_TAB1-CHARG = WA_EKET-CHARG.
            SELECT SINGLE * FROM EKET WHERE EBELN = WA_EKPO-EBELN AND EBELP = WA_EKPO-EBELP AND ETENR NE WA_EKET-ETENR.
            IF SY-SUBRC EQ 0.
              WA_TAB1-EINDT = '          '.
            ELSE.
              WA_TAB1-EINDT = WA_EKET-EINDT.
            ENDIF.
          ENDIF.

*      LOOP at it_eket into wa_eket WHERE ebeln = wa_ekpo-ebeln AND ebelp = wa_ekpo-ebelp.
**      if sy-subrc eq 0.
*        wa_tab1-qty = wa_ekpo-menge - wa_eket-wemng.
*        a = wa_ekpo-menge - wa_eket-wemng.
*        wa_tab1-eindt = wa_eket-eindt.
*        wa_tab1-wemng = wa_eket-wemng.
*        wa_tab1-pen_val = a * wa_ekpo-netpr.
*      ENdloop.
          READ TABLE IT_REC1 INTO WA_REC1 WITH KEY EBELN = WA_EKPO-EBELN EBELP = WA_EKPO-EBELP.
          IF SY-SUBRC EQ 0.
            WA_TAB1-WEMNG = WA_REC1-QTY.
          ENDIF.
          CLEAR : PQTY.
          PQTY = WA_TAB1-MENGE - WA_TAB1-WEMNG.
          IF PQTY GT 0.
            WA_TAB1-QTY = PQTY.
          ENDIF.

          SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_EKKO-LIFNR.
          IF SY-SUBRC EQ 0.
            WA_TAB1-NAME1 = LFA1-NAME1.
            WA_TAB1-ORT01 = LFA1-ORT01.
            WA_TAB1-STCD1 = LFA1-STCD1.
            WA_TAB1-STCD3 = LFA1-STCD3.
            WA_TAB1-SPERM = LFA1-SPERM.
          ENDIF.
**********  manufacturer***********
          SELECT SINGLE * FROM EKPA WHERE EBELN EQ WA_EKKO-EBELN AND PARVW EQ 'HR' .
          IF SY-SUBRC EQ 0.
            WA_TAB1-MFGR = EKPA-LIFN2.
            SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ EKPA-LIFN2.
            IF SY-SUBRC EQ 0.
              WA_TAB1-MNAME1 = LFA1-NAME1.
              WA_TAB1-MORT01 = LFA1-ORT01.
              WA_TAB1-MSTRAS = LFA1-STRAS.
              WA_TAB1-MPSTLZ = LFA1-PSTLZ.
            ENDIF.
          ENDIF.
          COLLECT WA_TAB1 INTO IT_TAB1.
          CLEAR WA_TAB1.
*      WA_EKPO-ZGTYP.
*      ENDIF.
        ENDIF.
*  endif.
*CLEAR WA_TAB1.
      ENDLOOP.
    ENDIF.
*  uline.
*ULINE.

    IF IT_TAB1 IS NOT INITIAL.
      SELECT * FROM EKBE INTO TABLE IT_EKBE FOR ALL ENTRIES IN IT_TAB1 WHERE EBELN EQ IT_TAB1-EBELN AND EBELP EQ IT_TAB1-EBELP AND BWART IN
      ('101','102') AND  BEWTP EQ 'E'.
    ENDIF.
    IF IT_EKBE IS NOT INITIAL.
      SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN IT_EKBE WHERE MBLNR EQ IT_EKBE-BELNR AND MJAHR EQ IT_EKBE-GJAHR AND SMBLN
      NE IT_EKBE-BELNR.
    ENDIF.
*ENDIF.
    SORT IT_EKBE BY BELNR DESCENDING EBELN EBELP ASCENDING.
*  LOOP at it_ekbe INTO wa_ekbe.
*    WRITE : / 'aa',wa_ekbe-ebeln,wa_ekbe-ebelp,wa_ekbe-belnr,wa_ekbe-gjahr.
*  ENDLOOP.




    IF IT_TAB1 IS NOT INITIAL.
      LOOP AT IT_TAB1 INTO WA_TAB1.
        MOVE-CORRESPONDING WA_TAB1 TO WA_TAB2.
        READ TABLE IT_EKBE INTO WA_EKBE WITH KEY EBELN = WA_TAB1-EBELN EBELP = WA_TAB1-EBELP.
        IF SY-SUBRC EQ 0.
          MOVE WA_EKBE-BELNR TO WA_TAB2-MBLNR.
          MOVE WA_EKBE-BUDAT TO WA_TAB2-BUDAT.
        ENDIF.
        COLLECT WA_TAB2 INTO IT_TAB2.
        CLEAR WA_TAB2.

*    pack : wa_tab1-matnr to wa_tab1-matnr ,
*           wa_tab1-lifnr  to wa_tab1-lifnr,
*           wa_tab1-sakto to wa_tab1-sakto.
*    condense : wa_tab1-matnr,wa_tab1-lifnr,wa_tab1-sakto.
*    modify it_tab1 from wa_tab1 transporting matnr lifnr sakto.

*  WRITE : / WA_TAB1-AEDAT,WA_TAB1-EBELN,WA_TAB1-EINDT,WA_TAB1-EBELP,WA_TAB1-LIFNR,WA_TAB1-NAME1,WA_TAB1-ORT01,WA_TAB1-MATNR,WA_TAB1-TXZ01,
*            WA_TAB1-LGORT,WA_TAB1-MENGE,WA_TAB1-MEINS,WA_TAB1-ELIKZ.
      ENDLOOP.
    ENDIF.

    IF R2 EQ 'X'.

      PERFORM COSTCSUMM.
    ELSEIF R1A EQ 'X'.

      LOOP AT IT_TAB2 INTO WA_TAB2.
        PACK : WA_TAB2-MATNR TO WA_TAB2-MATNR ,
              WA_TAB2-LIFNR  TO WA_TAB2-LIFNR,
              WA_TAB2-SAKTO TO WA_TAB2-SAKTO.
        CONDENSE : WA_TAB2-MATNR,WA_TAB2-LIFNR,WA_TAB2-SAKTO.
        MODIFY IT_TAB2 FROM WA_TAB2 TRANSPORTING MATNR LIFNR SAKTO.
      ENDLOOP.

      SORT IT_TAB2 BY MATNR LIFNR.
      DELETE ADJACENT DUPLICATES FROM IT_TAB2 COMPARING MATNR LIFNR.


      WA_FIELDCAT-FIELDNAME = 'MATNR'.
      WA_FIELDCAT-SELTEXT_L = 'ITEM CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'LIFNR'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'TXZ01'.
      WA_FIELDCAT-SELTEXT_L = 'MATERIAL'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MEINS'.
      WA_FIELDCAT-SELTEXT_L = 'UNIT'.
      APPEND WA_FIELDCAT TO FIELDCAT.


      LAYOUT-ZEBRA = 'X'.
      LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
      LAYOUT-WINDOW_TITLEBAR  = 'EXPECTED DATE OF RECEIPT'.


      CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
        EXPORTING
          I_CALLBACK_PROGRAM      = G_REPID
          I_CALLBACK_USER_COMMAND = 'USER_COMM'
          I_CALLBACK_TOP_OF_PAGE  = 'TOP'
          IS_LAYOUT               = LAYOUT
          IT_FIELDCAT             = FIELDCAT
          I_SAVE                  = 'A'
        TABLES
          T_OUTTAB                = IT_TAB2
        EXCEPTIONS
          PROGRAM_ERROR           = 1
          OTHERS                  = 2.
      IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDIF.

    ELSEIF R1B EQ 'X'.
*
*      LOOP AT IT_TAB2 INTO WA_TAB2.
*        PACK : WA_TAB2-MATNR TO WA_TAB2-MATNR ,
*              WA_TAB2-LIFNR  TO WA_TAB2-LIFNR,
*              WA_TAB2-SAKTO TO WA_TAB2-SAKTO.
*        CONDENSE : WA_TAB2-MATNR,WA_TAB2-LIFNR,WA_TAB2-SAKTO.
*        MODIFY IT_TAB2 FROM WA_TAB2 TRANSPORTING MATNR LIFNR SAKTO.
*      ENDLOOP.

      SORT IT_TAB2 BY MATNR LIFNR WERKS.
      DELETE ADJACENT DUPLICATES FROM IT_TAB2 COMPARING MATNR LIFNR WERKS.

SORT IT_TAB1 DESCENDING BY EBELN.

      LOOP AT IT_TAB2 INTO WA_TAB2.
        WA_TAB31-MATNR = WA_TAB2-MATNR.
        WA_TAB31-LIFNR = WA_TAB2-LIFNR.
        WA_TAB31-WERKS = WA_TAB2-WERKS.
        WA_TAB31-TXZ01 = WA_TAB2-TXZ01.
        WA_TAB31-MEINS = WA_TAB2-MEINS.
        WA_TAB31-MWSKZ = WA_TAB2-MWSKZ.

        READ TABLE IT_TAB1 INTO WA_TAB1 WITH KEY MATNR = WA_TAB2-MATNR LIFNR = WA_TAB2-LIFNR WERKS = WA_TAB2-WERKS.
        IF SY-SUBRC EQ 0.
          WA_TAB31-NETPR = WA_TAB1-NETPR / WA_TAB1-PEINH.
        ENDIF.
        COLLECT WA_TAB31 INTO IT_TAB31.
        CLEAR WA_TAB31.
      ENDLOOP.


      WA_FIELDCAT-FIELDNAME = 'MATNR'.
      WA_FIELDCAT-SELTEXT_L = 'ITEM CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'NETPR'.
      WA_FIELDCAT-SELTEXT_L = 'NET RATE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'LIFNR'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'TXZ01'.
      WA_FIELDCAT-SELTEXT_L = 'MATERIAL'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MEINS'.
      WA_FIELDCAT-SELTEXT_L = 'UNIT'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'WERKS'.
      WA_FIELDCAT-SELTEXT_L = 'PLANT'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MWSKZ'.
      WA_FIELDCAT-SELTEXT_L = 'TAX CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.


      LAYOUT-ZEBRA = 'X'.
      LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
      LAYOUT-WINDOW_TITLEBAR  = 'EXPECTED DATE OF RECEIPT'.


      CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
        EXPORTING
          I_CALLBACK_PROGRAM      = G_REPID
          I_CALLBACK_USER_COMMAND = 'USER_COMM'
          I_CALLBACK_TOP_OF_PAGE  = 'TOP'
          IS_LAYOUT               = LAYOUT
          IT_FIELDCAT             = FIELDCAT
          I_SAVE                  = 'A'
        TABLES
          T_OUTTAB                = IT_TAB31
        EXCEPTIONS
          PROGRAM_ERROR           = 1
          OTHERS                  = 2.
      IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDIF.

    ELSEIF R1 EQ 'X'.

      LOOP AT IT_TAB2 INTO WA_TAB2.
        PACK : WA_TAB2-MATNR TO WA_TAB2-MATNR ,
              WA_TAB2-LIFNR  TO WA_TAB2-LIFNR,
              WA_TAB2-SAKTO TO WA_TAB2-SAKTO.
        CONDENSE : WA_TAB2-MATNR,WA_TAB2-LIFNR,WA_TAB2-SAKTO.
        MODIFY IT_TAB2 FROM WA_TAB2 TRANSPORTING MATNR LIFNR SAKTO.
      ENDLOOP.

      WA_FIELDCAT-FIELDNAME = 'RETPO'.
      WA_FIELDCAT-SELTEXT_L = 'RETURN PO'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MATKL'.
      WA_FIELDCAT-SELTEXT_L = 'MAT GROUP'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'AEDAT'.
      WA_FIELDCAT-SELTEXT_L = 'PO DATE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'BATXT'.
      WA_FIELDCAT-SELTEXT_L = 'PO.TYPE.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'WERKS'.
      WA_FIELDCAT-SELTEXT_L = 'PLANT'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'EBELN'.
      WA_FIELDCAT-SELTEXT_L = 'PO. NO.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

         WA_FIELDCAT-FIELDNAME = 'BSART'.
      WA_FIELDCAT-SELTEXT_L = 'PO. Type.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'KNTTP'.
      WA_FIELDCAT-SELTEXT_L = 'TYPE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'ZTERM'.
      WA_FIELDCAT-SELTEXT_L = 'PO PAY TERM'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'ZBD1T'.
      WA_FIELDCAT-SELTEXT_L = 'PO PAY TERM DAYS'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'AEDAT1'.
      WA_FIELDCAT-SELTEXT_L = 'PO CHANGE DATE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'EBELP'.
      WA_FIELDCAT-SELTEXT_L = 'ITEM NO'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'J_1BNBM'.
      WA_FIELDCAT-SELTEXT_L = 'HSN CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'KOSTL'.
      WA_FIELDCAT-SELTEXT_L = 'COST CENTER'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MWSKZ'.
      WA_FIELDCAT-SELTEXT_L = 'TAX CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'CHARG'.
      WA_FIELDCAT-SELTEXT_L = 'BATCH'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'LICHA'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR BATCH'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'UEBTO'.
      WA_FIELDCAT-SELTEXT_L = 'TOLERANCE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MATNR'.
      WA_FIELDCAT-SELTEXT_L = 'ITEM CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'TXZ01'.
      WA_FIELDCAT-SELTEXT_L = 'MATERIAL'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'LGORT'.
      WA_FIELDCAT-SELTEXT_L = 'STORAGE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'STATUS1'.
      WA_FIELDCAT-SELTEXT_L = 'STATUS'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'EINDT'.
      WA_FIELDCAT-SELTEXT_L = 'EXCPT DELV DT'.
      APPEND WA_FIELDCAT TO FIELDCAT.

*  wa_fieldcat-fieldname = 'MBLNR'.
*  wa_fieldcat-seltext_s = 'GRN NO.'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'BUDAT'.
*  wa_fieldcat-seltext_s = 'GRN POSTING DATE'.
*  append wa_fieldcat to fieldcat.


      WA_FIELDCAT-FIELDNAME = 'BEDNR'.
      WA_FIELDCAT-SELTEXT_L = 'REQMT. NO.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'AFNAM'.
      WA_FIELDCAT-SELTEXT_L = 'REQUISITIONER'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'QTY'.
      WA_FIELDCAT-SELTEXT_L = 'PENDING QTY'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MENGE'.
      WA_FIELDCAT-SELTEXT_L = 'TOTAL QTY'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'NETPR'.
      WA_FIELDCAT-SELTEXT_L = 'NET RATE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'PEINH'.
      WA_FIELDCAT-SELTEXT_L = 'PER'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'PEN_VAL'.
      WA_FIELDCAT-SELTEXT_L = 'PENDING VALUE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'NETWR'.
      WA_FIELDCAT-SELTEXT_L = 'TOT NET VAL'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'WAERS'.
      WA_FIELDCAT-SELTEXT_L = 'CURRENCY'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'WEMNG'.
      WA_FIELDCAT-SELTEXT_L = 'RECEIVED QTY'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MEINS'.
      WA_FIELDCAT-SELTEXT_L = 'UNIT'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MSME'.
      WA_FIELDCAT-SELTEXT_L = 'MSME'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'STCD1'.
      WA_FIELDCAT-SELTEXT_L = 'MSME REG. NO.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'STCD3'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR GSTN'.
      APPEND WA_FIELDCAT TO FIELDCAT.


      WA_FIELDCAT-FIELDNAME = 'LIFNR'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'NAME1'.
      WA_FIELDCAT-SELTEXT_L = 'NAME'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'ORT01'.
      WA_FIELDCAT-SELTEXT_L = 'PLACE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'SPERM'.
      WA_FIELDCAT-SELTEXT_L = 'VENDOR DELETION'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MFGR'.
      WA_FIELDCAT-SELTEXT_L = 'MANUFACTURER CODE'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MNAME1'.
      WA_FIELDCAT-SELTEXT_L = 'MANUFACTURER NAME'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MORT01'.
      WA_FIELDCAT-SELTEXT_L = 'MANUFACTURER CITY'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MSTRAS'.
      WA_FIELDCAT-SELTEXT_L = 'MANUFACTURER STREET'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'MPSTLZ'.
      WA_FIELDCAT-SELTEXT_L = 'MANUFACTURER PIN'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'ANLN1'.
      WA_FIELDCAT-SELTEXT_L = 'ASSET NO.'.
      APPEND WA_FIELDCAT TO FIELDCAT.

      WA_FIELDCAT-FIELDNAME = 'ANLN2'.
      WA_FIELDCAT-SELTEXT_L = 'ASSET SUBCLASS'.
      APPEND WA_FIELDCAT TO FIELDCAT.




*   WA_FIELDCAT-fieldname = 'ELIKZ'.
*  WA_FIELDCAT-seltext_s = 'DEL. INDICATOR'.
*  APPEND WA_FIELDCAT TO FIELDCAT.



      LAYOUT-ZEBRA = 'X'.
      LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
      LAYOUT-WINDOW_TITLEBAR  = 'EXPECTED DATE OF RECEIPT'.


      CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
        EXPORTING
          I_CALLBACK_PROGRAM      = G_REPID
          I_CALLBACK_USER_COMMAND = 'USER_COMM'
          I_CALLBACK_TOP_OF_PAGE  = 'TOP'
          IS_LAYOUT               = LAYOUT
          IT_FIELDCAT             = FIELDCAT
          I_SAVE                  = 'A'
        TABLES
          T_OUTTAB                = IT_TAB2
        EXCEPTIONS
          PROGRAM_ERROR           = 1
          OTHERS                  = 2.
      IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDIF.

    ENDIF.
  ENDIF.
*&---------------------------------------------------------------------*
*&      Form  TOP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'PO DATE OF RECEIPT'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'EBELN'.
      SET PARAMETER ID 'BES' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'ME23N' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM
*&---------------------------------------------------------------------*
*&      Form  COSTCSUMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM COSTCSUMM .


  LOOP AT IT_TAB2 INTO WA_TAB2 .
    WA_TAB3-KOSTL = WA_TAB2-KOSTL.
    WA_TAB3-EBELN = WA_TAB2-EBELN.
    WA_TAB3-NAME1 = WA_TAB2-NAME1.
    WA_TAB3-NETWR = WA_TAB2-NETWR.
    WA_TAB3-AEDAT = WA_TAB2-AEDAT.

    WA_TAB3-QTY = WA_TAB2-QTY.
    WA_TAB3-MENGE = WA_TAB2-MENGE.
    WA_TAB3-WEMNG = WA_TAB2-WEMNG.
*    WA_TAB3-MEINS = WA_TAB2-MEINS.
    SELECT SINGLE * FROM CSKT WHERE SPRAS EQ 'EN' AND KOKRS EQ 'BCLL' AND KOSTL EQ WA_TAB2-KOSTL AND DATBI GE SY-DATUM.
    IF SY-SUBRC EQ 0.
      WA_TAB3-LTEXT = CSKT-MCTXT.
    ENDIF.
    COLLECT WA_TAB3 INTO IT_TAB3.
    CLEAR WA_TAB3.
  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'AEDAT'.
  WA_FIELDCAT-SELTEXT_L = 'PO DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'EBELN'.
  WA_FIELDCAT-SELTEXT_L = 'PO. NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'KOSTL'.
  WA_FIELDCAT-SELTEXT_L = 'COST CENTER'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LTEXT'.
  WA_FIELDCAT-SELTEXT_L = 'COST CENTER NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETWR'.
  WA_FIELDCAT-SELTEXT_L = 'TOT NET VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'QTY'.
  WA_FIELDCAT-SELTEXT_L = 'PENDING QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MENGE'.
  WA_FIELDCAT-SELTEXT_L = 'TOTAL QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WEMNG'.
  WA_FIELDCAT-SELTEXT_L = 'RECEIVED QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*  WA_FIELDCAT-FIELDNAME = 'MEINS'.
*  WA_FIELDCAT-SELTEXT_L = 'UNIT'.
*  APPEND WA_FIELDCAT TO FIELDCAT.






*   WA_FIELDCAT-fieldname = 'ELIKZ'.
*  WA_FIELDCAT-seltext_s = 'DEL. INDICATOR'.
*  APPEND WA_FIELDCAT TO FIELDCAT.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'EXPECTED DATE OF RECEIPT'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM      = G_REPID
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
      I_SAVE                  = 'A'
    TABLES
      T_OUTTAB                = IT_TAB3
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  POPRINTSTAT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM POPRINTSTAT .
  SELECT * FROM ZPO_PRINT INTO TABLE IT_ZPO_PRINT WHERE BUDAT IN PURDT.
  IF IT_ZPO_PRINT IS INITIAL.
    MESSAGE 'NO DATA' TYPE 'E'.
  ENDIF.
  IF IT_ZPO_PRINT IS NOT INITIAL.
    WRITE : /1 'PO NO', 15 'PO PRINT DATE', 30 'PO PRINT TIME',45 'PO PRINT LOGIN'..
    SKIP.
    LOOP AT IT_ZPO_PRINT INTO WA_ZPO_PRINT.
      WRITE : /1 WA_ZPO_PRINT-EBELN, 15 WA_ZPO_PRINT-BUDAT,30 WA_ZPO_PRINT-UZEIT,45 WA_ZPO_PRINT-USNAM.
    ENDLOOP.
  ENDIF.
ENDFORM.
