*&---------------------------------------------------------------------*
*& Report  ZAC1
*&DEVELOPED BY JYOTSNA.
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZAC11 NO STANDARD PAGE HEADING LINE-SIZE 900.
TABLES : AUFK,
         AFPO,
         MARA,
         MVKE,
         TVM5T,
         LFA1,
         BKPF,
         BSAK,
         BSIK,
         EKBE,
         MKPF,
         RSEG,
         MSEG,
         J_1IGRXREF,
         EKPO,
         T007S,
         MAKT,
         EKKO,
         VBRP,
         T001W,
         MARM,
         VBFA,
         VBRK,
         prcd_elements ,"KONV commented by ps ,
         MCHA.

TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.


TYPES : BEGIN OF ITAB1,
          AUFNR TYPE AFPO-AUFNR,
          MATNR TYPE AFPO-MATNR,
          CHARG TYPE AFPO-CHARG,
          MAKTX TYPE MAKT-MAKTX,
          PSMNG TYPE AFPO-PSMNG,
          WEMNG TYPE AFPO-WEMNG,
          BEZEI TYPE TVM5T-BEZEI,
          RATE1 TYPE P DECIMALS 2,
          MTART TYPE MARA-MTART,
        END OF ITAB1.

TYPES : BEGIN OF ITAB2,
          MATNR TYPE AFPO-MATNR,
          CHARG TYPE AFPO-CHARG,
          AUFNR TYPE AFPO-AUFNR,
          MAKTX TYPE MAKT-MAKTX,
          PSMNG TYPE AFPO-PSMNG,
          WEMNG TYPE AFPO-WEMNG,
          BEZEI TYPE TVM5T-BEZEI,
          MENGE TYPE AUFM-MENGE,
          DMBTR TYPE AUFM-DMBTR,
        END OF ITAB2.

TYPES : BEGIN OF ITAB3,
          MATNR  TYPE AFPO-MATNR,
          CHARG  TYPE AFPO-CHARG,
          AUFNR  TYPE AFPO-AUFNR,
          MAKTX  TYPE MAKT-MAKTX,
          PSMNG  TYPE AFPO-PSMNG,
          WEMNG  TYPE AFPO-WEMNG,
          BEZEI  TYPE TVM5T-BEZEI,
          MENGE2 TYPE AUFM-MENGE,
          DMBTR2 TYPE AUFM-DMBTR,
*  aufnr TYPE afpo-aufnr,
          MATNR2 TYPE AFPO-MATNR,
          CHARG2 TYPE AFPO-CHARG,
          MAKTX2 TYPE MAKT-MAKTX,
          PSMNG2 TYPE AFPO-PSMNG,
          WEMNG2 TYPE AFPO-WEMNG,
          BEZEI2 TYPE TVM5T-BEZEI,
          RATE1  TYPE P DECIMALS 2,
          MTART  TYPE MARA-MTART,
          VAL    TYPE P DECIMALS 2,
          VAL2   TYPE P DECIMALS 2,
          W_RATE TYPE P DECIMALS 2,
        END OF ITAB3.


TYPES : BEGIN OF ITAB4,
          MATNR     TYPE AFPO-MATNR,
          CHARG     TYPE AFPO-CHARG,
          AUFNR     TYPE AFPO-AUFNR,
          MAKTX     TYPE MAKT-MAKTX,
          PSMNG     TYPE AFPO-PSMNG,
          WEMNG     TYPE AFPO-WEMNG,
          BEZEI     TYPE TVM5T-BEZEI,
          MENGE2    TYPE AUFM-MENGE,
          DMBTR2    TYPE AUFM-DMBTR,
*  aufnr TYPE afpo-aufnr,
          MATNR2    TYPE AFPO-MATNR,
          CHARG2    TYPE AFPO-CHARG,
          MAKTX2    TYPE MAKT-MAKTX,
          PSMNG2    TYPE AFPO-PSMNG,
          WEMNG2    TYPE AFPO-WEMNG,
          BEZEI2    TYPE TVM5T-BEZEI,
          RATE1     TYPE P DECIMALS 2,
          MTART     TYPE MARA-MTART,
          VAL       TYPE P DECIMALS 2,
          VAL2      TYPE P DECIMALS 2,
          W_RATE    TYPE P DECIMALS 2,
          MBLNR     TYPE MSEG-MBLNR,
          LIFNR     TYPE MSEG-LIFNR,
          NAME1     TYPE LFA1-NAME1,
          ORT01     TYPE LFA1-ORT01,
          GRN_MENGE TYPE MSEG-MENGE,
          GRN_DMBTR TYPE MSEG-DMBTR,
          EBELN     TYPE MSEG-EBELN,
          EBELP     TYPE MSEG-EBELP,
          NETPR     TYPE EKPO-NETPR,
          PEINH     TYPE EKPO-PEINH,
          MENGE     TYPE EKPO-MENGE,
          NETWR     TYPE EKPO-NETWR,
          MWSKZ     TYPE EKPO-MWSKZ,
          KBETR     TYPE KONP-KBETR,
          C         TYPE P DECIMALS 2,
          BELNR     TYPE EKBE-BELNR,
          GJAHR     TYPE EKBE-GJAHR,
          XBLNR     TYPE EKBE-XBLNR,
          AUGBL     TYPE BSAK-AUGBL,
          PO_MENGE  TYPE EKPO-MENGE,
          EXBED     TYPE J_1IGRXREF-EXBED,
          PO_VAL    TYPE P DECIMALS 2,
          FI_VAL    TYPE P,
          BUDAT     TYPE MKPF-BUDAT,
          R1        TYPE P DECIMALS 2,
          R2        TYPE P,
          FI_YEAR   TYPE BKPF-GJAHR,
          VAT       TYPE P DECIMALS 2,
          FIBUDAT   TYPE BKPF-BUDAT,
          MJAHR     TYPE MSEG-MJAHR,
        END OF ITAB4.

TYPES : BEGIN OF ITAB5,
          MATNR     TYPE AFPO-MATNR,
          CHARG     TYPE AFPO-CHARG,
          AUFNR     TYPE AFPO-AUFNR,
          MAKTX     TYPE MAKT-MAKTX,
          PSMNG     TYPE AFPO-PSMNG,
          WEMNG     TYPE AFPO-WEMNG,
          BEZEI     TYPE TVM5T-BEZEI,
          MENGE2    TYPE AUFM-MENGE,
          DMBTR2    TYPE AUFM-DMBTR,
*  aufnr TYPE afpo-aufnr,
          MATNR2    TYPE AFPO-MATNR,
          CHARG2    TYPE AFPO-CHARG,
          MAKTX2    TYPE MAKT-MAKTX,
          PSMNG2    TYPE AFPO-PSMNG,
          WEMNG2    TYPE AFPO-WEMNG,
          BEZEI2    TYPE TVM5T-BEZEI,
          RATE1     TYPE P DECIMALS 2,
          MTART     TYPE MARA-MTART,
          VAL       TYPE P DECIMALS 2,
          VAL2      TYPE P DECIMALS 2,
          W_RATE    TYPE P DECIMALS 2,
          MBLNR     TYPE MSEG-MBLNR,
          LIFNR     TYPE MSEG-LIFNR,
          NAME1     TYPE LFA1-NAME1,
          ORT01     TYPE LFA1-ORT01,
          GRN_MENGE TYPE MSEG-MENGE,
          GRN_DMBTR TYPE MSEG-DMBTR,
          EBELN     TYPE MSEG-EBELN,
          EBELP     TYPE MSEG-EBELP,
          NETPR     TYPE EKPO-NETPR,
          PEINH     TYPE EKPO-PEINH,
          MENGE     TYPE EKPO-MENGE,
          NETWR     TYPE EKPO-NETWR,
          MWSKZ     TYPE EKPO-MWSKZ,
          KBETR     TYPE KONP-KBETR,
          C         TYPE P DECIMALS 2,
*          BELNR     TYPE EKBE-BELNR,
          BELNR(15) TYPE C,
          GJAHR     TYPE EKBE-GJAHR,
          XBLNR     TYPE EKBE-XBLNR,
          AUGBL     TYPE BSAK-AUGBL,
          PO_MENGE  TYPE EKPO-MENGE,
          EXBED     TYPE J_1IGRXREF-EXBED,
          PO_VAL    TYPE P DECIMALS 2,
          FI_VAL    TYPE P,
    FIVAL    TYPE P,
          BUDAT     TYPE MKPF-BUDAT,
          R1        TYPE P DECIMALS 2,
          R2        TYPE P,
          FI_YEAR   TYPE BKPF-GJAHR,
          VAT       TYPE P DECIMALS 2,
          FIBUDAT   TYPE BKPF-BUDAT,

          HWSTE     TYPE BSET-HWSTE,
          HWBAS     TYPE BSET-HWBAS,
          RATE(10)  TYPE C,
*     KTOSL(3) TYPE C,
*     MWSKZ TYPE BSET-MWSKZ,
          SGST      TYPE BSET-HWSTE,
          CGST      TYPE BSET-HWSTE,
          IGST      TYPE BSET-HWSTE,
          UGST      TYPE BSET-HWSTE,
          MJAHR     TYPE MSEG-MJAHR,
          PRDYLD    TYPE P   DECIMALS 2,
          PKGYLD    TYPE P DECIMALS 2,
          VAR       TYPE P DECIMALS 2,
        END OF ITAB5.

TYPES : BEGIN OF PO1,
          EBELN TYPE EKBE-EBELN,
          EBELP TYPE EKBE-EBELP,
          BELNR TYPE EKBE-BELNR,
          BUDAT TYPE EKBE-BUDAT,
          MATNR TYPE AFPO-MATNR,
          CHARG TYPE AFPO-CHARG,
          AUFNR TYPE AFPO-AUFNR,
          BUZEI TYPE EKBE-BUZEI,
          BWART TYPE EKBE-BWART,
          WERKS TYPE EKBE-WERKS,
          DMBTR TYPE EKBE-DMBTR,
          MAKTX TYPE MAKT-MAKTX,
          MENGE TYPE EKBE-MENGE,
          XBLNR TYPE EKBE-XBLNR,
          LIFNR TYPE LFA1-LIFNR,
          NAME1 TYPE LFA1-NAME1,
          ORT01 TYPE LFA1-ORT01,
          LFBNR TYPE EKBE-LFBNR,
          GJAHR TYPE EKBE-GJAHR,
        END OF PO1.

TYPES : BEGIN OF PO2,
          EBELN  TYPE EKBE-EBELN,
          EBELP  TYPE EKBE-EBELP,
          BELNR  TYPE EKBE-BELNR,
          GJAHR  TYPE EKBE-GJAHR,
          BUDAT  TYPE EKBE-BUDAT,
          MATNR  TYPE AFPO-MATNR,
          CHARG  TYPE AFPO-CHARG,
          AUFNR  TYPE AFPO-AUFNR,
          BUZEI  TYPE EKBE-BUZEI,
          BWART  TYPE EKBE-BWART,
          WERKS  TYPE EKBE-WERKS,
          DMBTR  TYPE EKBE-DMBTR,
          MAKTX  TYPE MAKT-MAKTX,
          MENGE  TYPE EKBE-MENGE,
          XBLNR  TYPE EKBE-XBLNR,
          LIFNR  TYPE LFA1-LIFNR,
          NAME1  TYPE LFA1-NAME1,
          ORT01  TYPE LFA1-ORT01,
          MATNR1 TYPE AFPO-MATNR,
          CHARG1 TYPE AFPO-CHARG,
          DMBTR1 TYPE EKBE-DMBTR,
          MENGE1 TYPE EKBE-MENGE,

          BELNR1 TYPE EKBE-BELNR,
          BUDAT1 TYPE EKBE-BUDAT,
          GJAHR1 TYPE EKBE-GJAHR,
*          MATNR1  TYPE AFPO-MATNR,
*          CHARG1  TYPE AFPO-CHARG,
          AUFNR1 TYPE AFPO-AUFNR,
          BUZEI1 TYPE EKBE-BUZEI,
          BWART1 TYPE EKBE-BWART,
          WERKS1 TYPE EKBE-WERKS,
*          DMBTR1  TYPE EKBE-DMBTR,
          MAKTX1 TYPE MAKT-MAKTX,
*          MENGE1  TYPE EKBE-MENGE,
          XBLNR1 TYPE EKBE-XBLNR,
          LIFNR1 TYPE LFA1-LIFNR,
          LFBNR  TYPE EKBE-LFBNR,
          LFBNR1 TYPE EKBE-LFBNR,
        END OF PO2.

TYPES : BEGIN OF PO3,
          EBELN  TYPE EKBE-EBELN,
          EBELP  TYPE EKBE-EBELP,
          BELNR  TYPE EKBE-BELNR,
          BUDAT  TYPE EKBE-BUDAT,
          MATNR  TYPE AFPO-MATNR,
          CHARG  TYPE AFPO-CHARG,
          AUFNR  TYPE AFPO-AUFNR,
          BUZEI  TYPE EKBE-BUZEI,
          BWART  TYPE EKBE-BWART,
          WERKS  TYPE EKBE-WERKS,
          DMBTR  TYPE EKBE-DMBTR,
          MAKTX  TYPE MAKT-MAKTX,
          MENGE  TYPE EKBE-MENGE,
          XBLNR  TYPE EKBE-XBLNR,
          LIFNR  TYPE LFA1-LIFNR,
          NAME1  TYPE LFA1-NAME1,
          ORT01  TYPE LFA1-ORT01,
          LFBNR  TYPE EKBE-LFBNR,
          LFBNR1 TYPE EKBE-LFBNR,
          BELNR1 TYPE EKBE-BELNR,
          WERKS1 TYPE EKBE-WERKS,
          MATNR1 TYPE AFPO-MATNR,
          CHARG1 TYPE AFPO-CHARG,
          DMBTR1 TYPE EKBE-DMBTR,
          MENGE1 TYPE EKBE-MENGE,
          EBELN2 TYPE MSEG-EBELN,
          EBELP2 TYPE MSEG-EBELP,
          MBLNR2 TYPE MSEG-MBLNR,
          MJAHR2 TYPE MSEG-MJAHR,
          BWART2 TYPE MSEG-BWART,
          MENGE2 TYPE MSEG-MENGE,
          DMBTR2 TYPE MSEG-DMBTR,
          WERKS2 TYPE MSEG-WERKS,
          LIFNR2 TYPE LFA1-LIFNR,
        END OF PO3.

TYPES : BEGIN OF PO4,
          EBELN  TYPE EKBE-EBELN,
          EBELP  TYPE EKBE-EBELP,
          BELNR  TYPE EKBE-BELNR,
          BUDAT  TYPE EKBE-BUDAT,
          MATNR  TYPE AFPO-MATNR,
          CHARG  TYPE AFPO-CHARG,
          AUFNR  TYPE AFPO-AUFNR,
          BUZEI  TYPE EKBE-BUZEI,
          BWART  TYPE EKBE-BWART,
          WERKS  TYPE EKBE-WERKS,
          DMBTR  TYPE EKBE-DMBTR,
          MAKTX  TYPE MAKT-MAKTX,
          MENGE  TYPE EKBE-MENGE,
          XBLNR  TYPE EKBE-XBLNR,
          LIFNR  TYPE LFA1-LIFNR,
          NAME1  TYPE LFA1-NAME1,
          ORT01  TYPE LFA1-ORT01,
          LFBNR  TYPE EKBE-LFBNR,
          LFBNR1 TYPE EKBE-LFBNR,
          BELNR1 TYPE EKBE-BELNR,
          WERKS1 TYPE EKBE-WERKS,
          MATNR1 TYPE AFPO-MATNR,
          CHARG1 TYPE AFPO-CHARG,
          DMBTR1 TYPE EKBE-DMBTR,
          MENGE1 TYPE EKBE-MENGE,
          EBELN2 TYPE MSEG-EBELN,
          EBELP2 TYPE MSEG-EBELP,
          MBLNR2 TYPE MSEG-MBLNR,
          MJAHR2 TYPE MSEG-MJAHR,
          BWART2 TYPE MSEG-BWART,
          MENGE2 TYPE MSEG-MENGE,
          DMBTR2 TYPE MSEG-DMBTR,
          WERKS2 TYPE MSEG-WERKS,
          BELNR3 TYPE BKPF-BELNR,
          GJAHR3 TYPE BKPF-GJAHR,
          LIFNR2 TYPE LFA1-LIFNR,
        END OF PO4.

TYPES : BEGIN OF PO5,
          EBELN    TYPE EKBE-EBELN,
          EBELP    TYPE EKBE-EBELP,
          BELNR    TYPE EKBE-BELNR,
          BUDAT    TYPE EKBE-BUDAT,
          MATNR    TYPE AFPO-MATNR,
          CHARG    TYPE AFPO-CHARG,
          AUFNR    TYPE AFPO-AUFNR,
          BUZEI    TYPE EKBE-BUZEI,
          BWART    TYPE EKBE-BWART,
          WERKS    TYPE EKBE-WERKS,
          DMBTR    TYPE EKBE-DMBTR,
          MAKTX    TYPE MAKT-MAKTX,
          MENGE    TYPE EKBE-MENGE,
          XBLNR    TYPE EKBE-XBLNR,
          LIFNR    TYPE LFA1-LIFNR,
          LFBNR1   TYPE EKBE-LFBNR,
          MAKTX1   TYPE MAKT-MAKTX,
          BELNR1   TYPE EKBE-BELNR,
          WERKS1   TYPE EKBE-WERKS,
          NAME1    TYPE LFA1-NAME1,
          ORT01    TYPE LFA1-ORT01,
          MATNR1   TYPE AFPO-MATNR,
          CHARG1   TYPE AFPO-CHARG,
          DMBTR1   TYPE EKBE-DMBTR,
          MENGE1   TYPE EKBE-MENGE,
          EBELN2   TYPE MSEG-EBELN,
          EBELP2   TYPE MSEG-EBELP,
          MBLNR2   TYPE MSEG-MBLNR,
          MJAHR2   TYPE MSEG-MJAHR,
          BWART2   TYPE MSEG-BWART,
          MENGE2   TYPE MSEG-MENGE,
          DMBTR2   TYPE MSEG-DMBTR,
          WERKS2   TYPE MSEG-WERKS,
          BELNR3   TYPE BKPF-BELNR,
          GJAHR3   TYPE BKPF-GJAHR,
          HWSTE    TYPE BSET-HWSTE,
          RATE(10) TYPE C,
          IGST     TYPE BSET-HWSTE,
          CGST     TYPE BSET-HWSTE,
          SGST     TYPE BSET-HWSTE,
          UGST     TYPE BSET-HWSTE,
          LIFNR2   TYPE LFA1-LIFNR,
          EXBED    TYPE J_1IGRXREF-EXBED,
          NETPR    TYPE EKPO-NETPR,
          PEINH    TYPE EKPO-PEINH,
          MWSKZ    TYPE EKPO-MWSKZ,
          TAXDESC  TYPE T007S-TEXT1,
          LFBNR    TYPE EKBE-LFBNR,

          LIFNR3   TYPE MCHA-LIFNR,
          VNAME3   TYPE LFA1-NAME1,
          VORT01_3 TYPE LFA1-ORT01,

        END OF PO5.

TYPES : BEGIN OF ITAX,
          MWSKZ TYPE A053-MWSKZ,
          KBETR TYPE KONP-KBETR,
        END OF ITAX.

TYPES : BEGIN OF ITAX1,
          BELNR TYPE BKPF-BELNR,
          GJAHR TYPE BKPF-GJAHR,
          MATNR TYPE EKPO-MATNR,
          EBELN TYPE EKPO-EBELN,
          EBELP TYPE EKPO-EBELP,
        END OF ITAX1.

TYPES : BEGIN OF ITAX2,
          BELNR    TYPE BKPF-BELNR,
          GJAHR    TYPE BKPF-GJAHR,
          TXGRP    TYPE BSET-TXGRP,
*          BUZEI(3) TYPE C,
          HWSTE    TYPE BSET-HWSTE,
          HWBAS    TYPE BSET-HWBAS,
          RATE(10) TYPE C,
          MENGE(10) TYPE C,
*     KTOSL(3) TYPE C,
*     MWSKZ TYPE BSET-MWSKZ,
          SGST     TYPE BSET-HWSTE,
          CGST     TYPE BSET-HWSTE,
          IGST     TYPE BSET-HWSTE,
          UGST     TYPE BSET-HWSTE,
          OTHR     TYPE BSET-HWSTE,
          MWSKZ    TYPE BSET-MWSKZ,
          EBELN    TYPE BSEG-EBELN,
          EBELP    TYPE BSEG-EBELP,
        END OF ITAX2.

TYPES : BEGIN OF RTAX2,
          BELNR    TYPE BKPF-BELNR,
          GJAHR    TYPE BKPF-GJAHR,
          TXGRP    TYPE BSET-TXGRP,
          HWSTE    TYPE BSET-HWSTE,
          HWBAS    TYPE BSET-HWBAS,
          RATE(10) TYPE C,
          MBLNR    TYPE MSEG-MBLNR,
          MJAHR    TYPE MSEG-MJAHR,
          MATNR    TYPE MSEG-MATNR,
*     KTOSL(3) TYPE C,
*     MWSKZ TYPE BSET-MWSKZ,
          SGST     TYPE BSET-HWSTE,
          CGST     TYPE BSET-HWSTE,
          IGST     TYPE BSET-HWSTE,
          UGST     TYPE BSET-HWSTE,
          OTHR     TYPE BSET-HWSTE,
          MWSKZ    TYPE BSET-MWSKZ,
          EBELN    TYPE BSEG-EBELN,
          EBELP    TYPE BSEG-EBELP,
        END OF RTAX2.

TYPES : BEGIN OF QTY1,
          MATNR TYPE EKBE-MATNR,
          CHARG TYPE EKBE-CHARG,
        END OF QTY1.

TYPES : BEGIN OF ITAP1,
          OMATNR TYPE EKBE-MATNR,
          OCHARG TYPE EKBE-CHARG,
          OAUFNR TYPE AFPO-AUFNR,
          MBLNR  TYPE MSEG-MBLNR,
          MATNR  TYPE MSEG-MATNR,
          CHARG  TYPE MSEG-CHARG,
          MENGE  TYPE MSEG-MENGE,
          LIFNR  TYPE MSEG-LIFNR,
          BELNR  TYPE BKPF-BELNR,
          BUDAT  TYPE BKPF-BUDAT,
          GJAHR  TYPE BKPF-GJAHR,
          VBELN  TYPE VBRK-VBELN,
          NETWR  TYPE VBRP-NETWR,
          MWSBP  TYPE VBRP-MWSBP,
          FKIMG  TYPE VBRP-FKIMG,
          EBELN  TYPE MSEG-EBELN,
          EBELP  TYPE MSEG-EBELP,

          VAL11  TYPE P DECIMALS 2,
          VAL12  TYPE P DECIMALS 2,

        END OF ITAP1.

TYPES : BEGIN OF TAQ1,
*          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          QTY1  TYPE P,

        END OF TAQ1.
TYPES : BEGIN OF TAQ2,
*          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          QTY2  TYPE P DECIMALS 2,
        END OF TAQ2.

TYPES : BEGIN OF MAT1,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
        END OF MAT1.

TYPES : BEGIN OF TP2,
          MATNR  TYPE MCHA-MATNR,
          CHARG  TYPE MCHA-CHARG,
          MATNR1 TYPE MCHA-MATNR,
          CHARG1 TYPE MCHA-CHARG,
        END OF TP2.

TYPES : BEGIN OF STK1,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          DMBTR TYPE MSEG-DMBTR,
          MENGE TYPE MSEG-MENGE,
          EBELN TYPE MSEG-EBELN,
          EBELP TYPE MSEG-EBELP,
          WERKS TYPE MSEG-WERKS,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          BWART TYPE MSEG-BWART,
          LIFNR TYPE MSEG-LIFNR,
          EMLIF TYPE MSEG-EMLIF,
        END OF STK1.

DATA : IT_TAB1  TYPE TABLE OF ITAB1,
       WA_TAB1  TYPE ITAB1,
       IT_TAB2  TYPE TABLE OF ITAB2,
       WA_TAB2  TYPE ITAB2,
       IT_TAB3  TYPE TABLE OF ITAB3,
       WA_TAB3  TYPE ITAB3,
       IT_TAX   TYPE TABLE OF ITAX,
       WA_TAX   TYPE ITAX,
       IT_TAB4  TYPE TABLE OF ITAB4,
       WA_TAB4  TYPE ITAB4,
       IT_TAB5  TYPE TABLE OF ITAB5,
       WA_TAB5  TYPE ITAB5,
       IT_TAQ1  TYPE TABLE OF TAQ1,
       WA_TAQ1  TYPE TAQ1,
       IT_TAQ2  TYPE TABLE OF TAQ2,
       WA_TAQ2  TYPE TAQ2,
       IT_TAB7  TYPE TABLE OF ITAB5,
       WA_TAB7  TYPE ITAB5,
       IT_TAB6  TYPE TABLE OF ITAB5,
       WA_TAB6  TYPE ITAB5,
       IT_PO1   TYPE TABLE OF PO1,
       WA_PO1   TYPE PO1,
       IT_PO2   TYPE TABLE OF PO2,
       WA_PO2   TYPE PO2,
       IT_PO3   TYPE TABLE OF PO3,
       WA_PO3   TYPE PO3,
       IT_PO4   TYPE TABLE OF PO4,
       WA_PO4   TYPE PO4,
       IT_PO5   TYPE TABLE OF PO5,
       WA_PO5   TYPE PO5,
       IT_PO6   TYPE TABLE OF PO5,
       WA_PO6   TYPE PO5,
       IT_TAX1  TYPE TABLE OF ITAX1,
       WA_TAX1  TYPE ITAX1,
       IT_TAX2  TYPE TABLE OF ITAX2,
       WA_TAX2  TYPE ITAX2,
       IT_TAX3  TYPE TABLE OF ITAX2,
       WA_TAX3  TYPE ITAX2,
       IT_RTAX2 TYPE TABLE OF RTAX2,
       WA_RTAX2 TYPE RTAX2,
       IT_RTAX3 TYPE TABLE OF RTAX2,
       WA_RTAX3 TYPE RTAX2,
       IT_QTY1  TYPE TABLE OF QTY1,
       WA_QTY1  TYPE QTY1,
       IT_TAP1  TYPE TABLE OF ITAP1,
       WA_TAP1  TYPE ITAP1,
       IT_MAT1  TYPE TABLE OF MAT1,
       WA_MAT1  TYPE MAT1,
       IT_TP2   TYPE TABLE OF TP2,
       WA_TP2   TYPE TP2,
       IT_STK2  TYPE TABLE OF STK1,
       WA_STK2  TYPE STK1.

DATA : VAL11 TYPE P   DECIMALS 2,
       VAL12 TYPE P   DECIMALS 2.
DATA: MDOC1 TYPE RSEG-BELNR.
*DATA: BUZEI TYPE RSEG-BUZEI.
*DATA: BUZEI1(3) TYPE C.
DATA : IT_AFPO       TYPE TABLE OF AFPO,
       WA_AFPO       TYPE AFPO,
       IT_AUFK       TYPE TABLE OF AUFK,
       WA_AUFK       TYPE AUFK,
       IT_AUFM       TYPE TABLE OF AUFM,
       WA_AUFM       TYPE AUFM,
       IT_MARA       TYPE TABLE OF MARA,
       WA_MARA       TYPE MARA,
       IT_MAKT       TYPE TABLE OF MAKT,
       WA_MAKT       TYPE MAKT,
       IT_MCHA       TYPE TABLE OF MCHA,
       WA_MCHA       TYPE MCHA,
       IT_MKPF       TYPE TABLE OF MKPF,
       WA_MKPF       TYPE MKPF,
       IT_MSEG       TYPE TABLE OF MSEG,
       IT_RSEG       TYPE TABLE OF RSEG,
       WA_RSEG       TYPE RSEG,
       WA_MSEG       TYPE MSEG,
       IT_EKPO       TYPE TABLE OF EKPO,
       WA_EKPO       TYPE EKPO,
       IT_J_1IGRXREF TYPE TABLE OF J_1IGRXREF,
       WA_J_1IGRXREF TYPE J_1IGRXREF,
       IT_EKBE       TYPE TABLE OF EKBE,
       WA_EKBE       TYPE EKBE,
       IT_A053       TYPE TABLE OF A053,
       WA_A053       TYPE A053,
       IT_KONP       TYPE TABLE OF KONP,
       WA_KONP       TYPE KONP,
       IT_BSEG       TYPE TABLE OF BSEG,
       WA_BSEG       TYPE BSEG,
       IT_BSET       TYPE TABLE OF BSET,
       WA_BSET       TYPE BSET,
       IT_EKKO       TYPE TABLE OF EKKO,
       WA_EKKO       TYPE EKKO.

DATA : VAL    TYPE P DECIMALS 2,
       VAL1   TYPE P DECIMALS 2,
       VAL2   TYPE P DECIMALS 2,
       QTY    TYPE P DECIMALS 3,
       RATE1  TYPE P DECIMALS 2,
       RATE2  TYPE P DECIMALS 2,
       VAL_1  TYPE P DECIMALS 2,
       TYPE1  TYPE MARA-MTART,
       W_RATE TYPE P DECIMALS 2,
       PO_VAL TYPE P DECIMALS 2,
       R1     TYPE P DECIMALS 2,
       R2     TYPE P,
       DOC3   TYPE BKPF-AWKEY.

DATA : VBEL  TYPE BKPF-XBLNR,
       VBEL1 TYPE BKPF-XBLNR.

DATA : TXGRP TYPE BSET-TXGRP.
DATA : XBLNR TYPE VBRK-VBELN.

DATA : NET_RATE TYPE P DECIMALS 2,
       NET_VAL  TYPE P,
       VAT_RATE TYPE P DECIMALS 2,
       VAT      TYPE P DECIMALS 2.

DATA : RTAX TYPE P DECIMALS 2.

DATA : A        TYPE P DECIMALS 2,
       B        TYPE P DECIMALS 2,
       C        TYPE P DECIMALS 2,
       E        TYPE P DECIMALS 2,
       T        TYPE P DECIMALS 2,
       A1       TYPE P   DECIMALS 2,
       DOC(14)  TYPE C,
       DOC1(14) TYPE C,
       DOC2(14) TYPE C,
       TAX      TYPE BSET-HWSTE,
       COT      TYPE I.

DATA : UMREN   TYPE MARM-UMREN,
       QTY1    TYPE P,
       PRDYLD  TYPE P DECIMALS 2,
       PACKYLD TYPE P DECIMALS 2.

DATA : COUNT  TYPE I,
       COUNT1 TYPE I.
DATA : W_UMREN LIKE MARM-UMREN,
       W_UMREZ LIKE MARM-UMREZ.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001 .
SELECT-OPTIONS  : S_MATNR FOR   AFPO-MATNR.
SELECT-OPTIONS  : S_AUFNR FOR AFPO-AUFNR.
*PARAMETERS : p_werks LIKE afpo-dwerk .
SELECT-OPTIONS : P_WERKS FOR AFPO-DWERK .
SELECT-OPTIONS : BATCH FOR AFPO-CHARG.
*SELECT-OPTIONS : s_lgort FOR afpo-lgort .
SELECT-OPTIONS : S_BUDAT FOR AUFK-ERDAT .
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-001 .
PARAMETERS : R11 RADIOBUTTON GROUP R1.
SELECT-OPTIONS : S_BUDAT1 FOR AUFK-ERDAT .
*SELECT-OPTIONS : s_budat2 FOR aufk-erdat .
PARAMETERS : R12 RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK B2.



INITIALIZATION.
  G_REPID = SY-REPID.

*  AT SELECTION-SCREEN.
*  perform authorization.

*  AUTHORITY-CHECK OBJECT '/DSD/SL_WR'
*           ID 'WERKS' FIELD from_plt.
*
*  If sy-subrc ne 0.
*    MeSG = 'Check your entry'.
*    MESSAGE MESG TYPE 'E'.
*  endif.


START-OF-SELECTION.

  IF R11 EQ 'X'.
    IF P_WERKS IS INITIAL.
      MESSAGE 'Enter plant' TYPE 'E'.
    ENDIF.
    IF S_BUDAT IS INITIAL.
      MESSAGE 'Enter Date' TYPE 'E'.
    ENDIF.
    PERFORM NSKGOA.
  ELSEIF R12 EQ 'X'.
    IF S_BUDAT1 IS INITIAL.
      MESSAGE 'Enter Date' TYPE 'E'.
    ENDIF.
    PERFORM LLM.
  ENDIF.

FORM NSKGOA.

  SELECT * FROM AUFK INTO TABLE IT_AUFK WHERE AUFNR IN S_AUFNR AND ERDAT IN S_BUDAT AND WERKS IN P_WERKS.
  IF SY-SUBRC NE 0.
    EXIT.
  ENDIF.

  SELECT * FROM AFPO INTO TABLE IT_AFPO FOR ALL ENTRIES IN IT_AUFK WHERE AUFNR EQ IT_AUFK-AUFNR AND MATNR IN S_MATNR AND CHARG IN BATCH.
*      AND lgort IN s_lgort.
  IF SY-SUBRC NE 0.
    EXIT.
  ENDIF.


  SELECT * FROM AUFM INTO TABLE IT_AUFM FOR ALL ENTRIES IN IT_AFPO WHERE AUFNR EQ IT_AFPO-AUFNR.
  IF SY-SUBRC NE 0.
    EXIT.
  ENDIF.

  SELECT * FROM MARA INTO TABLE IT_MARA FOR ALL ENTRIES IN IT_AUFM WHERE MATNR EQ IT_AUFM-MATNR AND  MTART IN ('ZVRP','ZROH').
  IF SY-SUBRC EQ 0.
    SELECT * FROM MAKT INTO TABLE IT_MAKT FOR ALL ENTRIES IN IT_AUFM WHERE MATNR EQ IT_AUFM-MATNR.
    IF SY-SUBRC NE 0.
    ENDIF.
  ENDIF.



*SORT it_afpo BY charg ASCENDING matnr DESCENDING.
  SORT IT_AFPO BY MATNR.
  SORT IT_AUFM BY MATNR.


  LOOP AT IT_AFPO INTO WA_AFPO.

    WA_TAB1-MATNR = WA_AFPO-MATNR.
    READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR = WA_AFPO-MATNR.
    IF SY-SUBRC EQ 0.
*    WRITE : 31(35) wa_makt-maktx.
      WA_TAB1-MAKTX = WA_MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE MATNR = WA_AFPO-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB1-MTART = MARA-MTART.
    ENDIF.
*  WRITE : 68 'ORDER',wa_afpo-aufnr.
    WA_TAB1-AUFNR = WA_AFPO-AUFNR.
*  WRITE : / 'BATCH SIZE',12 wa_afpo-psmng LEFT-JUSTIFIED,68 'ACTUAL QTY RECD.',wa_afpo-wemng.
    VAL_1 = WA_AFPO-WEMNG.

    WA_TAB1-PSMNG = WA_AFPO-PSMNG.
    WA_TAB1-WEMNG = WA_AFPO-WEMNG.
    SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_AFPO-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
      IF SY-SUBRC EQ 0.
*          WRITE : /1 'PACK SIZE',12 tvm5t-bezei LEFT-JUSTIFIED.
        WA_TAB1-BEZEI = TVM5T-BEZEI.
      ENDIF.
    ENDIF.
*  WRITE : 68 'BATCH ', wa_afpo-charg .
    WA_TAB1-CHARG = WA_AFPO-CHARG.
*  wa_afpo-dnrel.
*  ULINE.
*  WRITE : /1 'MATERIAL',31 'DESCRIPTION',68 'ID NO.',80 'QUANTITY',97 'VALUE'.
*  ULINE.


    LOOP AT IT_AUFM INTO WA_AUFM WHERE AUFNR EQ WA_AFPO-AUFNR.
      IF WA_AUFM-SHKZG EQ 'S'.
        WA_AUFM-MENGE = WA_AUFM-MENGE * ( - 1 ).
        WA_AUFM-DMBTR = WA_AUFM-DMBTR * ( - 1 ).
      ENDIF.

      READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_AUFM-MATNR .
      IF SY-SUBRC EQ 0.
*        WRITE : /1 wa_aufm-matnr LEFT-JUSTIFIED.
        WA_TAB2-AUFNR = WA_AUFM-AUFNR.
        WA_TAB2-MATNR = WA_AUFM-MATNR.
        WA_TAB2-CHARG = WA_AUFM-CHARG.
        READ TABLE IT_MAKT INTO WA_MAKT WITH KEY MATNR = WA_AUFM-MATNR.
        IF SY-SUBRC EQ 0.
*              WRITE : 31(35) wa_makt-maktx LEFT-JUSTIFIED.
          WA_TAB2-MAKTX = WA_MAKT-MAKTX.
        ENDIF.
*           WRITE : 68 wa_aufm-charg LEFT-JUSTIFIED,80 wa_aufm-menge LEFT-JUSTIFIED,97 wa_aufm-dmbtr LEFT-JUSTIFIED.
*           wa_tab2-charg = wa_aufm-charg.
        WA_TAB2-MENGE = WA_AUFM-MENGE.
        WA_TAB2-DMBTR = WA_AUFM-DMBTR.

*           val = val + wa_aufm-dmbtr.
*           qty = qty + wa_aufm-menge.
      ENDIF.
      COLLECT WA_TAB2 INTO IT_TAB2.
      CLEAR WA_TAB2.
    ENDLOOP.


    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
  ENDLOOP.

  SORT IT_TAB1 BY CHARG ASCENDING MATNR DESCENDING.

  LOOP AT IT_TAB1 INTO WA_TAB1.
    LOOP AT IT_TAB2 INTO WA_TAB2 WHERE AUFNR = WA_TAB1-AUFNR.
*    FORMAT COLOR 2.
*    WRITE : /1 wa_tab2-matnr,15 wa_tab2-maktx,50 wa_tab2-menge,70 wa_tab2-dmbtr.

      WA_TAB3-MATNR = WA_TAB1-MATNR.
      WA_TAB3-MAKTX = WA_TAB1-MAKTX.
      WA_TAB3-AUFNR = WA_TAB1-AUFNR.
      WA_TAB3-PSMNG = WA_TAB1-PSMNG.
      WA_TAB3-WEMNG = WA_TAB1-WEMNG.
      WA_TAB3-BEZEI = WA_TAB1-BEZEI.
      WA_TAB3-CHARG = WA_TAB1-CHARG.
      WA_TAB3-MATNR2 = WA_TAB2-MATNR.
      WA_TAB3-CHARG2 = WA_TAB2-CHARG.
      WA_TAB3-MAKTX2 = WA_TAB2-MAKTX.
      WA_TAB3-MENGE2 = WA_TAB2-MENGE.
      WA_TAB3-DMBTR2 = WA_TAB2-DMBTR.

      COLLECT WA_TAB3 INTO IT_TAB3.
      CLEAR WA_TAB3.
    ENDLOOP.

  ENDLOOP.


*LOOP at it_tab3 INTO wa_tab3.
*  WRITE : /'e', wa_tab3-matnr,wa_tab3-maktx,wa_tab3-aufnr,wa_tab3-psmng,wa_tab3-wemng,wa_tab3-bezei,wa_tab3-charg.
*  WRITE : wa_tab3-matnr2,wa_tab3-maktx2,wa_tab3-menge2,wa_tab3-dmbtr2.
*ENDLOOP.

  IF IT_TAB3 IS NOT INITIAL.
    SELECT * FROM MCHA INTO TABLE IT_MCHA FOR ALL ENTRIES IN IT_TAB3 WHERE CHARG EQ IT_TAB3-CHARG2.
    IF SY-SUBRC EQ 0.
      SELECT * FROM MKPF INTO TABLE IT_MKPF FOR ALL ENTRIES IN IT_MCHA WHERE BUDAT EQ IT_MCHA-LWEDT AND VGART EQ 'WE'.
      IF SY-SUBRC EQ 0.
        SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN  IT_MKPF WHERE MBLNR = IT_MKPF-MBLNR AND MJAHR EQ IT_MKPF-MJAHR AND BWART EQ '101'
          AND WERKS IN  P_WERKS .
        IF SY-SUBRC EQ 0.
          SELECT * FROM EKPO INTO TABLE IT_EKPO FOR ALL ENTRIES IN IT_MSEG WHERE EBELN = IT_MSEG-EBELN AND EBELP = IT_MSEG-EBELP.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDIF.

  IF IT_MSEG IS NOT INITIAL.
    SELECT * FROM J_1IGRXREF INTO TABLE IT_J_1IGRXREF FOR ALL ENTRIES IN IT_MSEG WHERE MBLNR = IT_MSEG-MBLNR AND MJAHR = IT_MSEG-MJAHR AND
            ZEILE = IT_MSEG-ZEILE.
    SELECT * FROM EKBE INTO TABLE IT_EKBE FOR ALL ENTRIES IN IT_MSEG WHERE EBELN = IT_MSEG-EBELN AND EBELP = IT_MSEG-EBELP AND BEWTP IN ('Q','R') AND
    LFBNR EQ IT_MSEG-MBLNR.
  ENDIF.

  SORT IT_TAB3 BY CHARG ASCENDING MATNR DESCENDING.

  IF IT_EKPO IS NOT INITIAL.
    SELECT * FROM A053 INTO TABLE IT_A053 FOR ALL ENTRIES IN IT_EKPO WHERE KAPPL EQ 'TX' AND KSCHL IN ('JIP1','JIP2') AND ALAND EQ 'IN' AND
      MWSKZ EQ IT_EKPO-MWSKZ AND DATBI GE SY-DATUM.
    IF SY-SUBRC EQ 0.
      SELECT * FROM KONP INTO TABLE IT_KONP FOR ALL ENTRIES IN IT_A053 WHERE KNUMH EQ IT_A053-KNUMH AND KBETR NE 0.
    ENDIF.
  ENDIF.


  LOOP AT IT_KONP INTO WA_KONP FROM SY-TABIX.
    CLEAR A1.
    READ TABLE IT_A053 INTO WA_A053 WITH KEY KNUMH = WA_KONP-KNUMH.
    IF SY-SUBRC EQ 0.
      WA_TAX-MWSKZ = WA_A053-MWSKZ.
*      WRITE:/ 'A',WA_A053-MWSKZ,WA_KONP-KBETR.
      A1 = WA_KONP-KBETR / 10.
      WA_TAX-KBETR = A1.
      COLLECT WA_TAX INTO IT_TAX.
      CLEAR WA_TAX.
    ENDIF.
  ENDLOOP.


  LOOP AT IT_TAB3 INTO WA_TAB3.
    CLEAR : R1,R2,PO_VAL,C,A,T,E.
*  WRITE : /'e', wa_tab3-matnr,wa_tab3-maktx,wa_tab3-aufnr,wa_tab3-psmng,wa_tab3-wemng,wa_tab3-bezei,wa_tab3-charg.
*  WRITE : wa_tab3-matnr2,wa_tab3-maktx2,wa_tab3-charg2,wa_tab3-menge2,wa_tab3-dmbtr2.

    WA_TAB4-MATNR =  WA_TAB3-MATNR.
    WA_TAB4-MAKTX =  WA_TAB3-MAKTX.
    WA_TAB4-AUFNR =  WA_TAB3-AUFNR.
*    ON CHANGE OF WA_TAB3-MATNR.
    ON CHANGE OF WA_TAB3-AUFNR.
      WA_TAB4-PSMNG =  WA_TAB3-PSMNG.
      WA_TAB4-WEMNG =  WA_TAB3-WEMNG.
    ENDON.
    WA_TAB4-BEZEI =  WA_TAB3-BEZEI.
    WA_TAB4-CHARG =  WA_TAB3-CHARG.
    WA_TAB4-MATNR2 =  WA_TAB3-MATNR2.
    WA_TAB4-MAKTX2 =  WA_TAB3-MAKTX2.
    WA_TAB4-CHARG2 =  WA_TAB3-CHARG2.
    WA_TAB4-MENGE2 =  WA_TAB3-MENGE2.
    WA_TAB4-DMBTR2 =  WA_TAB3-DMBTR2.


    READ TABLE IT_MSEG INTO WA_MSEG WITH KEY CHARG = WA_TAB3-CHARG2 BWART = '101' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MKPF WHERE MBLNR EQ WA_MSEG-MBLNR AND MJAHR EQ WA_MSEG-MJAHR.
      IF SY-SUBRC EQ 0.
        WA_TAB4-BUDAT = MKPF-BUDAT.
      ENDIF.
*    WRITE : 'aa', WA_MSEG-MBLNR, WA_MSEG-LIFNR.
      WA_TAB4-MBLNR = WA_MSEG-MBLNR.
      WA_TAB4-MJAHR = WA_MSEG-MJAHR.
      WA_TAB4-LIFNR = WA_MSEG-LIFNR.
      SELECT SINGLE * FROM LFA1 WHERE LIFNR = WA_MSEG-LIFNR.
      IF SY-SUBRC EQ 0.
*      WRITE : lfa1-name1,lfa1-ort01.
        WA_TAB4-NAME1 = LFA1-NAME1.
        WA_TAB4-ORT01 = LFA1-ORT01.
      ENDIF.

*    WRITE :  WA_MSEG-MENGE,WA_MSEG-DMBTR,WA_MSEG-EBELN,WA_MSEG-EBELP.
      WA_TAB4-GRN_MENGE =  WA_MSEG-MENGE.
      WA_TAB4-GRN_DMBTR =  WA_MSEG-DMBTR.
      WA_TAB4-EBELN =  WA_MSEG-EBELN.
      WA_TAB4-EBELP =  WA_MSEG-EBELP.
*      CONCATENATE wa_mseg-mblnr wa_mseg-mjahr INTO doc1.

      READ TABLE IT_EKPO INTO WA_EKPO WITH KEY EBELN = WA_MSEG-EBELN EBELP = WA_MSEG-EBELP.
      IF SY-SUBRC EQ 0.
*        select SINGLE * FROM rseg WHERE ebeln eq wa_ekpo-ebeln AND ebelp eq wa_ekpo-ebelp AND lfbnr eq wa_mseg-mblnr.
*        if sy-subrc eq 0.
*          WRITE : / '*',rseg-belnr.
*          CONCATENATE RSEG-BELNR RSEG-GJAHR INTO doc2.
*          select SINGLE * FROM bkpf WHERE bukrs eq 'BCLL' AND AWKEY EQ DOC2.
*          IF SY-SUBRC EQ 0.
*            WRITE : BKPF-BELNR,BKPF-GJAHR.
*          ENDIF.
*        endif.
        SELECT SINGLE * FROM EKBE WHERE EBELN EQ WA_MSEG-EBELN AND EBELP EQ WA_MSEG-EBELP AND BELNR EQ WA_MSEG-MBLNR.
        IF SY-SUBRC EQ 0.

          IF EKBE-WAERS NE 'INR'.
            CONCATENATE WA_MSEG-MBLNR WA_MSEG-MJAHR INTO DOC1.
*            WRITE : 'DOC',DOC.
            SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND AWKEY EQ DOC1.
            IF SY-SUBRC EQ 0.
*              WRITE : / wa_mseg-mblnr,wa_mseg-ebeln,wa_mseg-ebelp,bkpf-kursf.
              NET_RATE = ( WA_EKPO-NETPR / WA_EKPO-PEINH ) * BKPF-KURSF.
            ENDIF.
*            SELECT SINGLE * FROM BKPF WHERE AW
          ELSE.
            NET_RATE = WA_EKPO-NETPR / WA_EKPO-PEINH .
          ENDIF.
        ELSE.
          NET_RATE = WA_EKPO-NETPR / WA_EKPO-PEINH .
        ENDIF.
        WA_TAB4-NETPR = NET_RATE.
        NET_VAL = NET_RATE * WA_MSEG-ERFMG.
        WA_TAB4-NETWR = NET_VAL.

        VAT_RATE = WA_EKPO-NAVNW / WA_EKPO-MENGE.
        VAT = VAT_RATE * WA_MSEG-ERFMG.
        WA_TAB4-VAT = VAT.

*      WRITE : WA_EKPO-NETPR, WA_EKPO-PEINH, WA_EKPO-MENGE,WA_EKPO-NETWR.
*      WRITE : WA_EKPO-MWSKZ.
*          wa_tab4-netpr = WA_EKPO-NETPR.
        WA_TAB4-PEINH = WA_EKPO-PEINH.
        WA_TAB4-PO_MENGE = WA_EKPO-MENGE.
*          wa_tab4-netwr = WA_EKPO-NETwR.
        WA_TAB4-MWSKZ = WA_EKPO-MWSKZ.

*        r1 =

        READ TABLE IT_TAX INTO WA_TAX WITH KEY MWSKZ = WA_EKPO-MWSKZ.
        IF SY-SUBRC EQ 0.
*        WRITE : WA_TAX-KBETR.
          T = WA_TAX-KBETR.
          WA_TAB4-KBETR = WA_TAX-KBETR.
        ENDIF.
*        A = WA_EKPO-MENGE * WA_EKPO-NETPR.

        READ TABLE IT_J_1IGRXREF INTO WA_J_1IGRXREF WITH KEY MBLNR = WA_MSEG-MBLNR MJAHR = WA_MSEG-MJAHR ZEILE = WA_MSEG-ZEILE.
        IF SY-SUBRC EQ 0.
*        WRITE :  wa_j_1igrxref-exbed.
          E = WA_J_1IGRXREF-EXBED.
          WA_TAB4-EXBED = WA_J_1IGRXREF-EXBED.
        ENDIF.
        B = NET_VAL + E.
        C = B * ( T / 100 ).
*        B = A + E.
*        C = B * ( T / 100 ).
**      WRITE :  C .
        WA_TAB4-C = C.


      ENDIF.


      READ TABLE IT_EKBE INTO WA_EKBE WITH KEY EBELN = WA_MSEG-EBELN EBELP = WA_MSEG-EBELP .
      IF SY-SUBRC EQ 0.
        CONCATENATE WA_EKBE-BELNR WA_EKBE-GJAHR INTO DOC.
*      WRITE :  wa_ekbe-xblnr.
        WA_TAB4-XBLNR = WA_EKBE-XBLNR.

*         365 wa_ekbe-belnr LEFT-JUSTIFIED, 378 wa_ekbe-gjahr,385 doc LEFT-JUSTIFIED.
*        select SINGLE * FROM bkpf WHERE awkey eq doc.
*        if sy-subrc eq 0.
*        WRITE :  bkpf-belnr.
*          wa_tab4-belnr = bkpf-belnr.
*          WA_TAB4-FI_YEAR = BKPF-GJAHR.

        SELECT SINGLE * FROM RSEG WHERE EBELN EQ WA_EKPO-EBELN AND EBELP EQ WA_EKPO-EBELP AND LFBNR EQ WA_MSEG-MBLNR AND SHKZG EQ 'S'.
        IF SY-SUBRC EQ 0.
*          WRITE : / '*',rseg-belnr.
          CONCATENATE RSEG-BELNR RSEG-GJAHR INTO DOC2.
          SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND AWKEY EQ DOC2.
          IF SY-SUBRC EQ 0.
*            WRITE : / BKPF-BELNR,BKPF-GJAHR,wa_tab3-matnr2,wa_ekpo-ebeln,wa_ekpo-ebelp.
            WA_TAX1-BELNR = BKPF-BELNR.
            WA_TAX1-GJAHR = BKPF-GJAHR.
            WA_TAX1-MATNR = WA_TAB3-MATNR2.
            WA_TAX1-EBELN = WA_EKPO-EBELN.
            WA_TAX1-EBELP = WA_EKPO-EBELP.
            COLLECT WA_TAX1 INTO IT_TAX1.
            CLEAR WA_TAX1.

            WA_TAB4-BELNR = BKPF-BELNR.
            WA_TAB4-GJAHR = BKPF-GJAHR.
            WA_TAB4-FIBUDAT = BKPF-BUDAT.
            WA_TAB4-FI_YEAR = BKPF-GJAHR.

            SELECT SINGLE * FROM BSAK WHERE BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND LIFNR EQ WA_MSEG-LIFNR.
            IF SY-SUBRC EQ 0.
*          WRITE :  bsak-augbl.
              WA_TAB4-AUGBL = BSAK-AUGBL.
              WA_TAB4-FI_VAL = BSAK-DMBTR.
            ELSE.
              SELECT SINGLE * FROM BSIK WHERE BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND LIFNR EQ WA_MSEG-LIFNR.
              IF SY-SUBRC EQ 0.
*            WRITE :  bsik-augbl LEFT-JUSTIFIED.
                WA_TAB4-AUGBL = BSIK-AUGBL.
                WA_TAB4-FI_VAL = BSIK-DMBTR.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDIF.
*        endif.
      ENDIF.

      PO_VAL = WA_TAB4-NETWR + WA_TAB4-EXBED + WA_TAB4-C.
      WA_TAB4-PO_VAL = PO_VAL.
      R1 = PO_VAL / WA_TAB4-GRN_MENGE.
      WA_TAB4-R1 = R1.
      R2 = R1 * WA_TAB4-MENGE2.
      WA_TAB4-R2 = R2.
    ENDIF.
    COLLECT WA_TAB4 INTO IT_TAB4.
    CLEAR WA_TAB4.
  ENDLOOP.
*BREAK-POINT.
  PERFORM TAX.

*  LOOP at it_tab4 INTO wa_tab4.
*    WRITE : / 'r',wa_tab4-matnr,wa_tab4-maktx,wa_tab4-aufnr,wa_tab4-psmng,wa_tab4-wemng,wa_tab4-bezei,wa_tab4-charg.
*    WRITE : wa_tab4-matnr2,wa_tab4-maktx2,wa_tab4-charg2,wa_tab4-menge2,wa_tab4-dmbtr2.
*    WRITE : wa_tab4-MBLNR,WA_tab4-LIFNR,wa_tab4-name1,wa_tab4-ort01.
*    WRITE : WA_tab4-grn_MENGE,WA_tab4-grn_DMBTR,WA_tab4-EBELN,WA_tab4-EBELP.
*    WRITE : WA_tab4-NETPR, WA_tab4-PEINH,WA_tab4-po_MENGE,WA_tab4-NETWR,WA_tab4-MWSKZ,WA_tab4-KBETR,wa_tab4-exbed,
*            wa_tab4-c,wa_tab4-xblnr,wa_tab4-belnr,wa_tab4-augbl.
*
*     if wa_tab4-matnr na 'H'.
*      pack wa_tab4-matnr to wa_tab4-matnr.
*      CONDENSE wa_tab4-matnr.
*      modify it_tab4 from wa_tab4 TRANSPORTING matnr.
*    ENDIF.
*  ENDLOOP.
*  BREAK-POINT.

  LOOP AT IT_TAB4 INTO WA_TAB4.
*MOVE-CORRESPONDING WA_TAB4 TO WA_TAB5.
    WA_TAB5-MATNR = WA_TAB4-MATNR.
    WA_TAB5-MAKTX = WA_TAB4-MAKTX.
    WA_TAB5-AUFNR = WA_TAB4-AUFNR.
    WA_TAB5-PSMNG = WA_TAB4-PSMNG.
    WA_TAB5-WEMNG = WA_TAB4-WEMNG.
    WA_TAB5-BEZEI = WA_TAB4-BEZEI.
    WA_TAB5-CHARG = WA_TAB4-CHARG.
    WA_TAB5-MATNR2 = WA_TAB4-MATNR2.
    WA_TAB5-MAKTX = WA_TAB4-MAKTX.
    WA_TAB5-MAKTX2 = WA_TAB4-MAKTX2.
    WA_TAB5-CHARG2 = WA_TAB4-CHARG2.
    WA_TAB5-MENGE2 = WA_TAB4-MENGE2.
    WA_TAB5-R1 = WA_TAB4-R1.
    WA_TAB5-R2 = WA_TAB4-R2.
    WA_TAB5-DMBTR2 = WA_TAB4-DMBTR2.
    WA_TAB5-MBLNR = WA_TAB4-MBLNR.
    WA_TAB5-MJAHR = WA_TAB4-MJAHR.
    WA_TAB5-BUDAT = WA_TAB4-BUDAT.
    WA_TAB5-LIFNR = WA_TAB4-LIFNR.
    WA_TAB5-NAME1 = WA_TAB4-NAME1.
    WA_TAB5-ORT01 = WA_TAB4-ORT01.
    WA_TAB5-GRN_MENGE = WA_TAB4-GRN_MENGE.
    WA_TAB5-GRN_DMBTR = WA_TAB4-GRN_DMBTR.
    WA_TAB5-EBELN = WA_TAB4-EBELN.
    WA_TAB5-PO_VAL = WA_TAB4-PO_VAL.
    WA_TAB5-EBELP = WA_TAB4-EBELP.
    WA_TAB5-NETPR = WA_TAB4-NETPR.
    WA_TAB5-PEINH = WA_TAB4-PEINH.
    WA_TAB5-PO_MENGE = WA_TAB4-PO_MENGE.
    WA_TAB5-NETWR = WA_TAB4-NETWR.
    WA_TAB5-MWSKZ = WA_TAB4-MWSKZ.
    WA_TAB5-KBETR = WA_TAB4-KBETR.
    WA_TAB5-EXBED = WA_TAB4-EXBED.
    WA_TAB5-C = WA_TAB4-C.
    WA_TAB5-XBLNR = WA_TAB4-XBLNR.
    WA_TAB5-BELNR = WA_TAB4-BELNR.
    WA_TAB5-FIBUDAT = WA_TAB4-FIBUDAT.
    WA_TAB5-FI_YEAR = WA_TAB4-FI_YEAR.
    WA_TAB5-FI_VAL = WA_TAB4-FI_VAL.
    WA_TAB5-AUGBL = WA_TAB4-AUGBL.
    CLEAR : MDOC1.
*    BREAK-POINT.
    SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND BELNR EQ WA_TAB4-BELNR AND GJAHR EQ WA_TAB4-GJAHR.
    IF SY-SUBRC EQ 0.
      MDOC1 = BKPF-AWKEY+0(10).
      SELECT SINGLE * FROM RSEG WHERE BELNR EQ MDOC1 AND GJAHR EQ BKPF-GJAHR AND EBELN EQ WA_TAB4-EBELN AND EBELP EQ WA_TAB4-EBELP AND
        LFBNR EQ WA_TAB4-MBLNR AND MENGE EQ WA_TAB4-GRN_MENGE.
      IF SY-SUBRC EQ 0.
        READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY BELNR = WA_TAB4-BELNR GJAHR = WA_TAB4-GJAHR EBELN = WA_TAB4-EBELN   EBELP = WA_TAB4-EBELP
      MENGE =  RSEG-MENGE.
        IF SY-SUBRC EQ 0.
          WA_TAB5-HWBAS = WA_TAX3-HWBAS.
          WA_TAB5-HWSTE = WA_TAX3-HWSTE.
          WA_TAB5-RATE = WA_TAX3-RATE.
          WA_TAB5-IGST = WA_TAX3-IGST.
          WA_TAB5-CGST = WA_TAX3-CGST.
          WA_TAB5-SGST = WA_TAX3-SGST.
          WA_TAB5-UGST = WA_TAX3-UGST.
          WA_TAB5-FIVAL = WA_TAX3-HWBAS + WA_TAX3-HWSTE.
        ELSE.
          WA_TAB5-HWBAS = 0.
          WA_TAB5-HWSTE = 0.
          WA_TAB5-RATE = 0.
          WA_TAB5-IGST = 0.
          WA_TAB5-CGST = 0.
          WA_TAB5-SGST = 0.
          WA_TAB5-UGST = 0.
            WA_TAB5-FIVAL = 0.

        ENDIF.

      ENDIF.
    ENDIF.
*

*    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_TAB4-MBLNR  AND MATNR EQ WA_TAB4-MATNR2 AND CHARG EQ WA_TAB4-CHARG2.
*    IF SY-SUBRC EQ 0.
*      CLEAR : TXGRP.
*      TXGRP = MSEG-ZEILE.
*      READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY BELNR = WA_TAB4-BELNR GJAHR = WA_TAB4-GJAHR EBELN = WA_TAB4-EBELN   EBELP = WA_TAB4-EBELP
*      TXGRP = TXGRP.
*      IF SY-SUBRC EQ 0.
*        WA_TAB5-HWBAS = WA_TAX3-HWBAS.
*        WA_TAB5-HWSTE = WA_TAX3-HWSTE.
*        WA_TAB5-RATE = WA_TAX3-RATE.
*        WA_TAB5-IGST = WA_TAX3-IGST.
*        WA_TAB5-CGST = WA_TAX3-CGST.
*        WA_TAB5-SGST = WA_TAX3-SGST.
*        WA_TAB5-UGST = WA_TAX3-UGST.
*      ENDIF.
*    ENDIF.
*    IF WA_TAB5-HWBAS EQ 0.
*      READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY BELNR = WA_TAB4-BELNR GJAHR = WA_TAB4-GJAHR EBELN = WA_TAB4-EBELN   EBELP = WA_TAB4-EBELP.
*      IF SY-SUBRC EQ 0.
*        WA_TAB5-HWBAS = WA_TAX3-HWBAS.
*        WA_TAB5-HWSTE = WA_TAX3-HWSTE.
*        WA_TAB5-RATE = WA_TAX3-RATE.
*        WA_TAB5-IGST = WA_TAX3-IGST.
*        WA_TAB5-CGST = WA_TAX3-CGST.
*        WA_TAB5-SGST = WA_TAX3-SGST.
*        WA_TAB5-UGST = WA_TAX3-UGST.
*      ENDIF.

*    ENDIF.

    COLLECT WA_TAB5 INTO IT_TAB5.
    CLEAR WA_TAB5.


  ENDLOOP.

  LOOP AT IT_TAB5 INTO WA_TAB5.
    IF WA_TAB5-LIFNR EQ 0.
      MOVE-CORRESPONDING WA_TAB5 TO WA_TAB6.
      COLLECT WA_TAB6 INTO IT_TAB6.
      CLEAR WA_TAB6.
    ENDIF.
  ENDLOOP.

  LOOP AT IT_TAB6 INTO WA_TAB6.

    WA_TAP1-OMATNR = WA_TAB6-MATNR.
    WA_TAP1-OCHARG = WA_TAB6-CHARG.
    WA_TAP1-OAUFNR = WA_TAB6-AUFNR.

    WA_TAP1-MBLNR = WA_TAB6-MBLNR.
    WA_TAP1-MATNR = WA_TAB6-MATNR2.
    WA_TAP1-CHARG = WA_TAB6-CHARG2.
    WA_TAP1-MENGE = WA_TAB6-GRN_MENGE.
    WA_TAP1-LIFNR = WA_TAB6-LIFNR.
    WA_TAP1-EBELN = WA_TAB6-EBELN.
    WA_TAP1-EBELP = WA_TAB6-EBELP.

    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_TAB6-MBLNR AND MJAHR EQ WA_TAB6-MJAHR AND MATNR EQ WA_TAB6-MATNR2 AND CHARG = WA_TAB6-CHARG2
      AND EBELN EQ WA_TAB6-EBELN AND EBELP EQ WA_TAB6-EBELP.
    IF SY-SUBRC EQ 0.
*      write : '*',mseg-xblnr_mkpf.
      VBEL =  MSEG-XBLNR_MKPF.
      CONCATENATE '0' VBEL INTO VBEL1.
      SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND BLART IN ('RV','EA') AND AWKEY EQ VBEL AND XREVERSAL EQ ' '.
      IF SY-SUBRC EQ 0.
*        write : bkpf-belnr,bkpf-gjahr.
        WA_TAP1-BELNR = BKPF-BELNR.
        WA_TAP1-BUDAT = BKPF-BUDAT.
        WA_TAP1-GJAHR = BKPF-GJAHR.
        WA_TAP1-VBELN = VBEL.
      ELSE.
        SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND BLART IN ('RV','EA') AND AWKEY EQ VBEL1 AND XREVERSAL EQ ' '.
        IF SY-SUBRC EQ 0.
*          write : bkpf-belnr,bkpf-gjahr.
          WA_TAP1-BELNR = BKPF-BELNR.
          WA_TAP1-BUDAT = BKPF-BUDAT.
          WA_TAP1-GJAHR = BKPF-GJAHR.
          WA_TAP1-VBELN = VBEL1.
        ENDIF.
      ENDIF.
      SELECT SINGLE * FROM VBRP WHERE VBELN EQ VBEL AND MATNR EQ WA_TAB6-MATNR2 AND CHARG EQ WA_TAB6-CHARG2 AND AUBEL EQ WA_TAB6-EBELN
        AND AUPOS EQ WA_TAB6-EBELP AND FKIMG GT 0.
      IF SY-SUBRC EQ 0.
*        write : vbrp-netwr,vbrp-mwsbp,vbrp-fkimg.
        WA_TAP1-NETWR = VBRP-NETWR.
        WA_TAP1-MWSBP = VBRP-MWSBP.
        WA_TAP1-FKIMG = VBRP-FKIMG.
      ELSE.
        SELECT SINGLE * FROM VBRP WHERE VBELN EQ VBEL1 AND MATNR EQ WA_TAB6-MATNR2 AND CHARG EQ WA_TAB6-CHARG2 AND AUBEL EQ WA_TAB6-EBELN
        AND AUPOS EQ WA_TAB6-EBELP AND FKIMG GT 0.
        IF SY-SUBRC EQ 0.
*          write : vbrp-netwr,vbrp-mwsbp,vbrp-fkimg.
          WA_TAP1-NETWR = VBRP-NETWR.
          WA_TAP1-MWSBP = VBRP-MWSBP.
          WA_TAP1-FKIMG = VBRP-FKIMG.
        ENDIF.
      ENDIF.

      SELECT SINGLE * FROM EKKO WHERE EBELN EQ WA_TAB6-EBELN.
      IF SY-SUBRC EQ 0.
*        write : 'VENDOR',ekko-reswk.
        WA_TAP1-LIFNR = EKKO-RESWK.
      ENDIF.
    ENDIF.

******************************
    CLEAR : VAL11,VAL12.
    SELECT SINGLE * FROM VBRK WHERE VBELN EQ WA_TAP1-VBELN.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM VBRP WHERE VBELN EQ VBRK-VBELN AND MATNR EQ WA_TAP1-MATNR AND CHARG EQ WA_TAP1-CHARG AND FKIMG GT 0.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM prcd_elements WHERE KNUMV EQ VBRK-KNUMV AND KPOSN EQ VBRP-POSNR AND KRECH EQ 'C'.
        IF SY-SUBRC EQ 0.
          VAL11 =  prcd_elements-KBETR / prcd_elements-KPEIN.
          VAL12 = VAL11 * VBRP-FKIMG.
          WA_TAP1-VAL11 = VAL11.
          WA_TAP1-VAL12 = VAL12.
        ENDIF.
      ENDIF.
    ENDIF.
**********************************
    COLLECT WA_TAP1 INTO IT_TAP1.
    CLEAR WA_TAP1.
  ENDLOOP.

*  PERFORM TRFVAL.


  LOOP AT IT_TAB5 INTO WA_TAB5.
    CLEAR: UMREN,QTY1,PRDYLD.
*    WRITE : /'A', WA_TAB5-MATNR,WA_TAB5-CHARG,WA_TAB5-AUFNR,WA_TAB5-PSMNG,WA_TAB5-WEMNG,WA_TAB5-BEZEI.
    SELECT SINGLE * FROM MARM WHERE MATNR EQ WA_TAB5-MATNR AND MEINH EQ 'PC'.
    IF SY-SUBRC EQ 0.
      UMREN = MARM-UMREN.
    ENDIF.
    QTY1 = WA_TAB5-WEMNG * UMREN.
*    WRITE : 'b',QTY1.
    IF WA_TAB5-MATNR CS 'H'.
      PRDYLD = ( QTY1 / WA_TAB5-PSMNG ) * 100.
*      WRITE : 'prod. yld',PRDYLD.
      WA_TAQ2-CHARG = WA_TAB5-CHARG.
      WA_TAQ2-QTY2 = PRDYLD.
      COLLECT WA_TAQ2 INTO IT_TAQ2.
      CLEAR WA_TAQ2.
    ELSE.
*      WA_TAQ1-MATNR = WA_TAB5-MATNR.
      WA_TAQ1-CHARG = WA_TAB5-CHARG.
      WA_TAQ1-QTY1 = QTY1.
      COLLECT WA_TAQ1 INTO IT_TAQ1.
      CLEAR WA_TAQ1.
    ENDIF.
  ENDLOOP.

  LOOP AT IT_TAB5 INTO WA_TAB5.
    CLEAR : PACKYLD.
    MOVE-CORRESPONDING WA_TAB5 TO WA_TAB7.
    IF WA_TAB5-LIFNR EQ 0.
      READ TABLE IT_TAP1 INTO WA_TAP1 WITH KEY MBLNR = WA_TAB5-MBLNR MATNR = WA_TAB5-MATNR2 CHARG = WA_TAB5-CHARG2
      EBELN = WA_TAB5-EBELN EBELP = WA_TAB5-EBELP
      OMATNR = WA_TAB5-MATNR OCHARG = WA_TAB5-CHARG OAUFNR = WA_TAB5-AUFNR.
      IF SY-SUBRC EQ 0.

        WA_TAB7-R1 = WA_TAP1-VAL11.
        WA_TAB7-R2 = WA_TAP1-VAL12.
        WA_TAB7-LIFNR = WA_TAP1-LIFNR.
        WA_TAB7-BELNR = WA_TAP1-BELNR.
        WA_TAB7-FIBUDAT = WA_TAP1-BUDAT.
        WA_TAB7-HWSTE = WA_TAP1-MWSBP.
        WA_TAB7-HWBAS = WA_TAP1-NETWR.
        WA_TAB7-IGST = WA_TAP1-MWSBP.
        WA_TAB7-FI_VAL = WA_TAP1-NETWR + WA_TAP1-MWSBP.
        WA_TAB7-GRN_DMBTR = WA_TAP1-NETWR + WA_TAP1-MWSBP.
        WA_TAB7-FI_YEAR = WA_TAP1-GJAHR.
        WA_TAB7-XBLNR = WA_TAP1-VBELN.
        SELECT SINGLE * FROM T001W   WHERE WERKS EQ WA_TAP1-LIFNR.
        IF SY-SUBRC EQ 0.
          WA_TAB7-NAME1 = T001W-NAME1.
          WA_TAB7-ORT01 = T001W-ORT01.
        ENDIF.
      ENDIF.
    ENDIF.
    IF WA_TAB7-MATNR CS 'H'.
      IF WA_TAB7-PSMNG GT 0.
        READ TABLE IT_TAQ2 INTO WA_TAQ2 WITH KEY CHARG = WA_TAB7-CHARG.
        IF SY-SUBRC EQ 0.
          WA_TAB7-PRDYLD = WA_TAQ2-QTY2.
        ENDIF.
        READ TABLE IT_TAQ1 INTO WA_TAQ1 WITH KEY CHARG = WA_TAB7-CHARG.
        IF SY-SUBRC EQ 0.
*          WRITE : WA_TAQ1-QTY1.
          PACKYLD = ( WA_TAQ1-QTY1 / WA_TAB7-PSMNG ) * 100.
          WA_TAB7-PKGYLD = PACKYLD.
        ENDIF.
        IF WA_TAB7-PKGYLD GT 0.
          WA_TAB7-VAR = WA_TAB7-PRDYLD -   WA_TAB7-PKGYLD.
        ENDIF.
      ENDIF.
    ENDIF.
    COLLECT WA_TAB7 INTO IT_TAB7.
    CLEAR WA_TAB7.



*    if wa_tab5-matnr na 'H'.
*      pack wa_tab5-matnr to wa_tab5-matnr.
*      pack wa_tab5-aufnr to wa_tab5-aufnr.
*      pack wa_tab5-matnr2 to wa_tab5-matnr2.
*      pack wa_tab5-lifnr to wa_tab5-lifnr.
*      pack wa_tab5-belnr to wa_tab5-belnr.
*      pack wa_tab5-augbl to wa_tab5-augbl.
*
*      condense : wa_tab5-matnr,wa_tab5-aufnr,wa_tab5-matnr2,wa_tab5-lifnr,wa_tab5-belnr,wa_tab5-augbl.
*      modify it_tab5 from wa_tab5 transporting matnr aufnr matnr2 lifnr belnr augbl.
*    else.
*      pack wa_tab5-matnr2 to wa_tab5-matnr2.
*      pack wa_tab5-aufnr to wa_tab5-aufnr.
*      pack wa_tab5-lifnr to wa_tab5-lifnr.
*      pack wa_tab5-belnr to wa_tab5-belnr.
*      pack wa_tab5-augbl to wa_tab5-augbl.
*
*      condense : wa_tab5-matnr2,wa_tab5-aufnr,wa_tab5-lifnr,wa_tab5-belnr,wa_tab5-augbl.
*      modify it_tab5 from wa_tab5 transporting matnr2 aufnr lifnr belnr augbl.
*    endif.
  ENDLOOP.



  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUFNR'.
  WA_FIELDCAT-SELTEXT_L = 'ORDER'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PSMNG'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH SIZE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WEMNG'.
  WA_FIELDCAT-SELTEXT_L = 'ACTUAL QTY RECEIVED'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'PACK SIZE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PRDYLD'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCTION YIELD'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'PKGYLD'.
  WA_FIELDCAT-SELTEXT_L = 'PACKING YIELD'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'VAR'.
  WA_FIELDCAT-SELTEXT_L = 'VARIENCE'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'MATNR2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MENGE2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'R1'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'R2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL ACTUAL VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DMBTR2'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL VALUE AS PER ORDER'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MBLNR'.
  WA_FIELDCAT-SELTEXT_L = 'GRN'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDAT'.
  WA_FIELDCAT-SELTEXT_L = 'GRN POSTING DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LIFNR'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ORT01'.
  WA_FIELDCAT-SELTEXT_L = 'CITY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRN_MENGE'.
  WA_FIELDCAT-SELTEXT_L = 'GRN QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRN_DMBTR'.
  WA_FIELDCAT-SELTEXT_L = 'GRN VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELN'.
  WA_FIELDCAT-SELTEXT_L = 'PO NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PO_VAL'.
  WA_FIELDCAT-SELTEXT_L = 'PO GROSS VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELP'.
  WA_FIELDCAT-SELTEXT_L = 'PO ITEM'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETPR'.
  WA_FIELDCAT-SELTEXT_L = 'PO RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PEINH'.
  WA_FIELDCAT-SELTEXT_L = 'RATE PER'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PO_MENGE'.
  WA_FIELDCAT-SELTEXT_L = 'PO QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETWR'.
  WA_FIELDCAT-SELTEXT_L = 'BASIC PO VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*  WA_FIELDCAT-fieldname = 'VAT'.
*  WA_FIELDCAT-seltext_L = 'VAT'.
*  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MWSKZ'.
  WA_FIELDCAT-SELTEXT_L = 'TAX CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'KBETR'.
  WA_FIELDCAT-SELTEXT_L = 'TAX RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EXBED'.
  WA_FIELDCAT-SELTEXT_L = 'ED AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'C'.
  WA_FIELDCAT-SELTEXT_L = 'TAX AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'XBLNR'.
  WA_FIELDCAT-SELTEXT_L = 'INV. REF. NO'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BELNR'.
  WA_FIELDCAT-SELTEXT_L = 'FI DOC'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FIBUDAT'.
  WA_FIELDCAT-SELTEXT_L = 'FI POSTING DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FI_YEAR'.
  WA_FIELDCAT-SELTEXT_L = 'FI DOC YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*  WA_FIELDCAT-FIELDNAME = 'FI_VAL'.
*  WA_FIELDCAT-SELTEXT_L = 'FI TOTAL VALUE'.
*  APPEND WA_FIELDCAT TO FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'FIVAL'.
  WA_FIELDCAT-SELTEXT_L = 'FI VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.



  WA_FIELDCAT-FIELDNAME = 'HWBAS'.
  WA_FIELDCAT-SELTEXT_L = 'GST TAXABLE VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'HWSTE'.
  WA_FIELDCAT-SELTEXT_L = 'GST TAX VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'RATE'.
  WA_FIELDCAT-SELTEXT_L = 'GST RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'IGST'.
  WA_FIELDCAT-SELTEXT_L = 'IGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CGST'.
  WA_FIELDCAT-SELTEXT_L = 'CGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SGST'.
  WA_FIELDCAT-SELTEXT_L = 'SGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'UGST'.
  WA_FIELDCAT-SELTEXT_L = 'UGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUGBL'.
  WA_FIELDCAT-SELTEXT_L = 'CLEARING DOC'.
  APPEND WA_FIELDCAT TO FIELDCAT.




  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'PLANT WISE STOCK TRANSFER DETAIL'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB7
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.

FORM LLM.
  SELECT * FROM EKKO INTO TABLE IT_EKKO WHERE BUKRS EQ '1000' AND BSART EQ 'ZS' AND AEDAT IN S_BUDAT1.
  IF SY-SUBRC EQ 0.
    SELECT * FROM EKBE INTO TABLE IT_EKBE FOR ALL ENTRIES IN IT_EKKO WHERE EBELN EQ IT_EKKO-EBELN AND BEWTP IN ('E','O').
*      AND BUDAT IN S_BUDAT1

  ENDIF.

  LOOP AT IT_EKBE INTO WA_EKBE WHERE BEWTP EQ 'E' AND MATNR IN S_MATNR AND CHARG IN BATCH AND WERKS IN P_WERKS.

    WA_PO1-MATNR = WA_EKBE-MATNR.
    WA_PO1-CHARG = WA_EKBE-CHARG.
    WA_PO1-EBELN = WA_EKBE-EBELN.
    WA_PO1-EBELP = WA_EKBE-EBELP.
    WA_PO1-GJAHR = WA_EKBE-GJAHR.
    WA_PO1-BELNR = WA_EKBE-BELNR.
    WA_PO1-WERKS = WA_EKBE-WERKS.
    WA_PO1-BWART = WA_EKBE-BWART.
    WA_PO1-BUDAT = WA_EKBE-BUDAT.
    WA_PO1-MENGE = WA_EKBE-MENGE.
    WA_PO1-DMBTR = WA_EKBE-DMBTR.
    WA_PO1-LFBNR = WA_EKBE-LFBNR.
    COLLECT WA_PO1 INTO IT_PO1.
    CLEAR WA_PO1.
  ENDLOOP.

*  LOOP AT IT_EKBE INTO WA_EKBE .
**      WHERE EBELN EQ WA_PO1-EBELN AND EBELP = WA_PO1-EBELP AND BEWTP EQ 'O' AND
**      LFBNR EQ WA_PO1-LFBNR.
*    WRITE : / 'B',WA_EKBE-EBELN,WA_EKBE-BELNR,WA_EKBE-MATNR,WA_EKBE-CHARG,WA_EKBE-DMBTR.
*  ENDLOOP.

  LOOP AT IT_PO1 INTO WA_PO1.
*      WRITE : / 'A',WA_PO1-EBELN,WA_PO1-BELNR,WA_PO1-MATNR,WA_PO1-CHARG,WA_PO1-DMBTR,WA_PO1-LFBNR.
    LOOP AT IT_EKBE INTO WA_EKBE WHERE EBELN EQ WA_PO1-EBELN AND EBELP = WA_PO1-EBELP AND BEWTP EQ 'O' AND
      LFBNR EQ WA_PO1-LFBNR.
*       WRITE : / 'B',WA_EKBE-EBELN,WA_EKBE-BELNR,WA_EKBE-MATNR,WA_EKBE-CHARG,WA_EKBE-DMBTR.
      WA_PO2-MATNR = WA_PO1-MATNR.
      WA_PO2-CHARG = WA_PO1-CHARG.
      WA_PO2-EBELN = WA_PO1-EBELN.
      WA_PO2-EBELP = WA_PO1-EBELP.
      WA_PO2-GJAHR = WA_PO1-GJAHR.
      WA_PO2-BELNR = WA_PO1-BELNR.
      WA_PO2-BWART = WA_PO1-BWART.
      WA_PO2-BUDAT = WA_PO1-BUDAT.
      WA_PO2-MENGE = WA_PO1-MENGE.
      WA_PO2-DMBTR = WA_PO1-DMBTR.
      WA_PO2-LFBNR = WA_PO1-LFBNR.
      WA_PO2-WERKS = WA_PO1-WERKS.

      WA_PO2-BELNR1 = WA_EKBE-BELNR.
      WA_PO2-GJAHR1 = WA_EKBE-GJAHR.
      WA_PO2-BUZEI1 = WA_EKBE-BUZEI.
      WA_PO2-BWART1 = WA_EKBE-BWART.
      WA_PO2-BUDAT1 = WA_EKBE-BUDAT.
      WA_PO2-MENGE1 = WA_EKBE-MENGE.
      WA_PO2-DMBTR1 = WA_EKBE-DMBTR.
      WA_PO2-XBLNR1 = WA_EKBE-XBLNR.
      WA_PO2-MATNR1 = WA_EKBE-MATNR.
      WA_PO2-WERKS1 = WA_EKBE-WERKS.
      WA_PO2-CHARG1 = WA_EKBE-CHARG.
      WA_PO2-LFBNR1 = WA_EKBE-LFBNR.
      COLLECT WA_PO2 INTO IT_PO2.
      CLEAR WA_PO2.
    ENDLOOP.
  ENDLOOP.
  SORT IT_PO2 BY BELNR MATNR CHARG.

  LOOP AT IT_PO2 INTO WA_PO2.
*    ON CHANGE OF WA_PO2-MATNR.
*      COT = 1.
*    ENDON.
*    ON CHANGE OF WA_PO2-CHARG.
*      COT = 1.
*    ENDON.
    ON CHANGE OF WA_PO2-BELNR.
      COT = 1.
    ENDON.

    IF COT EQ 1.

      WA_PO3-MENGE = WA_PO2-MENGE.
      WA_PO3-DMBTR = WA_PO2-DMBTR.

    ENDIF.
    WA_PO3-EBELN = WA_PO2-EBELN.
    WA_PO3-EBELP = WA_PO2-EBELP.
    WA_PO3-BELNR = WA_PO2-BELNR.
    WA_PO3-MATNR = WA_PO2-MATNR.
    WA_PO3-CHARG = WA_PO2-CHARG.
    WA_PO3-LFBNR = WA_PO2-LFBNR.
    WA_PO3-WERKS = WA_PO2-WERKS.
    WA_PO3-BWART = WA_PO2-BWART.
    WA_PO3-BUDAT = WA_PO2-BUDAT.
*    WA_PO2-BUZEI WA_PO2-DMBTR, WA_PO2-XBLNR, WA_PO2-LIFNR, WA_PO2-NAME1,WA_PO2-ORT01.
    WA_PO3-MATNR1 = WA_PO2-MATNR1.
    WA_PO3-CHARG1 = WA_PO2-CHARG1.
    WA_PO3-MENGE1 = WA_PO2-MENGE1.
    WA_PO3-DMBTR1 = WA_PO2-DMBTR1.
    WA_PO3-LFBNR1 = WA_PO2-LFBNR1.
    WA_PO3-BELNR1 = WA_PO2-BELNR1.
    WA_PO3-WERKS1 = WA_PO2-WERKS1.
    COLLECT WA_PO3 INTO IT_PO3.
    CLEAR WA_PO3.
    WA_QTY1-MATNR = WA_PO2-MATNR1.
    WA_QTY1-CHARG = WA_PO2-CHARG1.
    COLLECT WA_QTY1 INTO IT_QTY1.
    CLEAR WA_QTY1.
*    WA_PO2-MATNR1,WA_PO2-WERKS1,WA_PO2-CHARG1,WA_PO2-BELNR1,WA_PO2-BUZEI1,WA_PO2-BWART1, WA_PO2-BUDAT1,WA_PO2-MENGE1,
*    WA_PO2-DMBTR1, WA_PO2-XBLNR1.
    COT = COT + 1.
  ENDLOOP.

  SORT IT_QTY1 BY MATNR CHARG.
  DELETE ADJACENT DUPLICATES FROM IT_QTY1 COMPARING MATNR CHARG.
  IF IT_QTY1 IS NOT INITIAL.
    SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN IT_QTY1 WHERE BWART EQ '101' AND MATNR EQ IT_QTY1-MATNR
      AND CHARG EQ IT_QTY1-CHARG.
  ENDIF.
  SORT IT_MSEG DESCENDING BY MBLNR.

  LOOP AT IT_PO3 INTO WA_PO3.
    WA_PO4-EBELN = WA_PO3-EBELN.
    WA_PO4-EBELP = WA_PO3-EBELP.
    WA_PO4-BELNR = WA_PO3-BELNR.
    WA_PO4-MATNR = WA_PO3-MATNR.
    WA_PO4-CHARG = WA_PO3-CHARG.
    WA_PO4-MENGE = WA_PO3-MENGE.
    WA_PO4-DMBTR = WA_PO3-DMBTR.
    WA_PO4-LFBNR = WA_PO3-LFBNR.
    WA_PO4-WERKS = WA_PO3-WERKS.
    WA_PO4-BWART = WA_PO3-BWART.
    WA_PO4-BUDAT = WA_PO3-BUDAT.
    WA_PO4-MATNR1 = WA_PO3-MATNR1.
    WA_PO4-CHARG1 = WA_PO3-CHARG1.
    WA_PO4-MENGE1 = WA_PO3-MENGE1.
    WA_PO4-DMBTR1 = WA_PO3-DMBTR1.
    WA_PO4-LFBNR1 = WA_PO3-LFBNR1.
    WA_PO4-BELNR1 = WA_PO3-BELNR1.
    WA_PO4-WERKS1 = WA_PO3-WERKS1.
    READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MATNR = WA_PO3-MATNR1 CHARG = WA_PO3-CHARG1.
    IF SY-SUBRC EQ 0.
      IF WA_MSEG-SHKZG EQ 'H'.
        WA_MSEG-DMBTR = WA_MSEG-DMBTR * ( - 1 ).
        WA_MSEG-MENGE = WA_MSEG-MENGE * ( - 1 ).
      ENDIF.
      WA_PO4-EBELN2 = WA_MSEG-EBELN.
      WA_PO4-EBELP2 = WA_MSEG-EBELP.
      WA_PO4-WERKS2 = WA_MSEG-WERKS.
      WA_PO4-MBLNR2 = WA_MSEG-MBLNR.
      WA_PO4-MJAHR2 = WA_MSEG-MJAHR.
      WA_PO4-BWART2 = WA_MSEG-BWART.
      WA_PO4-MENGE2 = WA_MSEG-MENGE.
      WA_PO4-DMBTR2 = WA_MSEG-DMBTR.
      WA_PO4-LIFNR2 = WA_MSEG-LIFNR.
    ELSE.
      WA_MAT1-MATNR = WA_PO3-MATNR1.
      WA_MAT1-CHARG = WA_PO3-CHARG1.
      COLLECT WA_MAT1 INTO IT_MAT1.
      CLEAR WA_MAT1.
    ENDIF.
    COLLECT WA_PO4 INTO IT_PO4.
    CLEAR WA_PO4.
  ENDLOOP.

  PERFORM PODET.

  LOOP AT IT_PO4 INTO WA_PO4.
    IF WA_PO4-MBLNR2 EQ SPACE.
      READ TABLE IT_STK2 INTO WA_STK2 WITH KEY MATNR = WA_PO4-MATNR1 CHARG = WA_PO4-CHARG1.
      IF SY-SUBRC EQ 0.
        WA_PO4-EBELN2 = WA_STK2-EBELN.
        WA_PO4-EBELP2 = WA_STK2-EBELP.
        WA_PO4-WERKS2 = WA_STK2-WERKS.
        WA_PO4-MBLNR2 = WA_STK2-MBLNR.
        WA_PO4-MJAHR2 = WA_STK2-MJAHR.
        WA_PO4-BWART2 = WA_STK2-BWART.
        WA_PO4-MENGE2 = WA_STK2-MENGE.
        WA_PO4-DMBTR2 = WA_STK2-DMBTR.
        WA_PO4-LIFNR2 = WA_STK2-LIFNR.
        MODIFY IT_PO4 FROM WA_PO4 TRANSPORTING EBELN2 EBELP2 WERKS2 MBLNR2 MJAHR2 BWART2 MENGE2 DMBTR2 LIFNR2.
        CLEAR WA_PO4.
      ENDIF.
    ENDIF.
  ENDLOOP.


  IF IT_PO4 IS NOT INITIAL.
    SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_PO4 WHERE EBELN EQ IT_PO4-EBELN2 AND EBELP EQ
      IT_PO4-EBELP2 AND WERKS EQ IT_PO4-WERKS2 AND LFBNR EQ IT_PO4-MBLNR2 AND LFGJA EQ IT_PO4-MJAHR2
      AND TBTKZ EQ SPACE.
  ENDIF.
  SORT IT_RSEG DESCENDING.


*
  LOOP AT IT_PO4 INTO WA_PO4.
    CLEAR : DOC3.
*    WRITE : / '4', WA_PO4-EBELN,WA_PO4-EBELP,WA_PO4-BELNR,WA_PO4-MATNR1,WA_PO4-CHARG1,WA_PO4-MENGE1,WA_PO4-DMBTR1,
*    WA_PO4-BUZEI,WA_PO4-BWART, WA_PO4-BUDAT,WA_PO4-MENGE, WA_PO4-DMBTR, WA_PO4-XBLNR,WA_PO4-MATNR,WA_PO4-WERKS,
*    WA_PO4-CHARG,'AAA',WA_PO4-EBELN2,WA_PO4-EBELP2,WA_PO4-MBLNR2,WA_PO4-MJAHR2,WA_PO4-BWART2,WA_PO4-MENGE2,WA_PO4-DMBTR2.

    WA_PO5-EBELN = WA_PO4-EBELN.
    WA_PO5-EBELP = WA_PO4-EBELP.
    WA_PO5-BELNR = WA_PO4-BELNR.
    WA_PO5-MATNR = WA_PO4-MATNR.
    WA_PO5-CHARG = WA_PO4-CHARG.
    WA_PO5-MENGE = WA_PO4-MENGE.
    WA_PO5-DMBTR = WA_PO4-DMBTR.
    WA_PO5-LFBNR = WA_PO4-LFBNR.
    WA_PO5-WERKS = WA_PO4-WERKS.
    WA_PO5-BWART = WA_PO4-BWART.
    WA_PO5-BUDAT = WA_PO4-BUDAT.
    WA_PO5-MATNR1 = WA_PO4-MATNR1.
    WA_PO5-CHARG1 = WA_PO4-CHARG1.
    WA_PO5-MENGE1 = WA_PO4-MENGE1.
    WA_PO5-DMBTR1 = WA_PO4-DMBTR1.
    WA_PO5-LFBNR1 = WA_PO4-LFBNR1.
    WA_PO5-BELNR1 = WA_PO4-BELNR1.
    WA_PO5-WERKS1 = WA_PO4-WERKS1.
    WA_PO5-EBELN2 = WA_PO4-EBELN2.
    WA_PO5-EBELP2 = WA_PO4-EBELP2.
    WA_PO5-WERKS2 = WA_PO4-WERKS2.
    WA_PO5-MBLNR2 = WA_PO4-MBLNR2.
    WA_PO5-MJAHR2 = WA_PO4-MJAHR2.
    WA_PO5-BWART2 = WA_PO4-BWART2.
    WA_PO5-MENGE2 = WA_PO4-MENGE2.
    WA_PO5-DMBTR2 = WA_PO4-DMBTR2.
    WA_PO5-LIFNR2 = WA_PO4-LIFNR2.
    READ TABLE IT_RSEG INTO WA_RSEG WITH KEY EBELN = WA_PO4-EBELN2 EBELP = WA_PO4-EBELP2 LFBNR = WA_PO4-MBLNR2
    LFGJA = WA_PO4-MJAHR2.
    IF SY-SUBRC EQ 0.
*      WRITE : WA_RSEG-BELNR.
      CONCATENATE WA_RSEG-BELNR WA_RSEG-GJAHR INTO DOC3.
      SELECT SINGLE * FROM BKPF WHERE BUKRS EQ '1000' AND AWKEY EQ DOC3.
      IF SY-SUBRC EQ 0.
        WA_PO5-BELNR3 = BKPF-BELNR.
        WA_PO5-GJAHR3 = BKPF-GJAHR.
      ENDIF.
    ENDIF.
    IF WA_PO5-BELNR3 EQ SPACE.
      SELECT SINGLE * FROM EKKO WHERE EBELN EQ WA_PO4-EBELN2 AND BSART EQ 'ZUB'.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_PO4-MBLNR2 AND MJAHR EQ WA_PO4-MJAHR2.
        IF SY-SUBRC EQ 0.
          IF MSEG-VBELN_IM NE SPACE.
            SELECT SINGLE * FROM VBFA WHERE VBELV EQ MSEG-VBELN_IM AND POSNN EQ MSEG-VBELP_IM AND VBTYP_N EQ 'M'.
            IF SY-SUBRC EQ 0.
              SELECT SINGLE * FROM BKPF WHERE BLART EQ 'EA' AND XBLNR EQ VBFA-VBELN.
              IF SY-SUBRC EQ 0.
                WA_PO5-BELNR3 = BKPF-BELNR.
                WA_PO5-GJAHR3 = BKPF-GJAHR.
              ENDIF.
            ENDIF.

          ELSE.

*            SELECT SINGLE * FROM bkpf WHERE blart EQ 'EA' AND xblnr EQ mseg-xblnr_mkpf.
*            IF sy-subrc EQ 0.
*              wa_po5-belnr3 = bkpf-belnr.
*              wa_po5-gjahr3 = bkpf-gjahr.
*            ELSE.
*              CLEAR : xblnr.
*              xblnr = mseg-xblnr_mkpf.
*              SHIFT xblnr RIGHT DELETING TRAILING space.
*              OVERLAY xblnr WITH '0000000000'.
*
*              SELECT SINGLE * FROM bkpf WHERE blart EQ 'EA' AND xblnr EQ xblnr.
*              IF sy-subrc EQ 0.
*                wa_po5-belnr3 = bkpf-belnr.
*                wa_po5-gjahr3 = bkpf-gjahr.
*              ENDIF.
*            ENDIF.

          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.
    COLLECT WA_PO5 INTO IT_PO5.
    CLEAR WA_PO5.
  ENDLOOP.

*
  PERFORM TAX1.
*
  LOOP AT IT_PO5 INTO WA_PO5.
*    WRITE : / '5', WA_PO5-EBELN,WA_PO5-EBELP,WA_PO5-BELNR,WA_PO5-MATNR1,WA_PO5-CHARG1,WA_PO5-MENGE1,WA_PO5-DMBTR1,
*    WA_PO5-BUZEI,WA_PO5-BWART, WA_PO5-BUDAT,WA_PO5-MENGE, WA_PO5-DMBTR, WA_PO5-XBLNR,WA_PO5-MATNR,WA_PO5-WERKS,
*    WA_PO5-CHARG,'aaaa',WA_PO5-EBELN2,WA_PO5-EBELP2,WA_PO5-MBLNR2,WA_PO5-MJAHR2,WA_PO5-BWART2,WA_PO5-MENGE2,WA_PO5-DMBTR2,
*    WA_PO5-BELNR3,WA_PO5-GJAHR3.

    WA_PO6-EBELN = WA_PO5-EBELN.
    WA_PO6-EBELP = WA_PO5-EBELP.
    WA_PO6-BELNR = WA_PO5-BELNR.
    WA_PO6-MATNR = WA_PO5-MATNR.
    WA_PO6-CHARG = WA_PO5-CHARG.
    WA_PO6-MENGE = WA_PO5-MENGE.
    WA_PO6-DMBTR = WA_PO5-DMBTR.
    WA_PO6-LFBNR = WA_PO5-LFBNR.
    WA_PO6-WERKS = WA_PO5-WERKS.
    WA_PO6-BWART = WA_PO5-BWART.
    WA_PO6-BUDAT = WA_PO5-BUDAT.
    WA_PO6-MATNR1 = WA_PO5-MATNR1.
    WA_PO6-CHARG1 = WA_PO5-CHARG1.
    WA_PO6-MENGE1 = WA_PO5-MENGE1.
    WA_PO6-DMBTR1 = WA_PO5-DMBTR1.
    WA_PO6-LFBNR1 = WA_PO5-LFBNR1.
    WA_PO6-BELNR1 = WA_PO5-BELNR1.
    WA_PO6-WERKS1 = WA_PO5-WERKS1.
    WA_PO6-EBELN2 = WA_PO5-EBELN2.
    WA_PO6-EBELP2 = WA_PO5-EBELP2.
    WA_PO6-WERKS2 = WA_PO5-WERKS2.
    WA_PO6-MBLNR2 = WA_PO5-MBLNR2.
    WA_PO6-MJAHR2 = WA_PO5-MJAHR2.
    WA_PO6-BWART2 = WA_PO5-BWART2.
    WA_PO6-MENGE2 = WA_PO5-MENGE2.
    WA_PO6-DMBTR2 = WA_PO5-DMBTR2.
    WA_PO6-LIFNR2 = WA_PO5-LIFNR2.

    IF WA_PO5-LIFNR2 EQ SPACE.
      SELECT SINGLE * FROM MCHA WHERE MATNR EQ WA_PO5-MATNR1 AND CHARG EQ WA_PO5-CHARG1 AND LIFNR NE SPACE.
      IF SY-SUBRC EQ 0.
        WA_PO6-LIFNR3 = MCHA-LIFNR.
        SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ MCHA-LIFNR.
        IF SY-SUBRC EQ 0.
          WA_PO6-VNAME3 = LFA1-NAME1.
          WA_PO6-VORT01_3 = LFA1-ORT01.
        ENDIF.
      ENDIF.
    ENDIF.

    WA_PO6-BELNR3 = WA_PO5-BELNR3.
    WA_PO6-GJAHR3 = WA_PO5-GJAHR3.

    READ TABLE IT_RTAX3 INTO WA_RTAX3 WITH KEY BELNR = WA_PO5-BELNR3 GJAHR = WA_PO5-GJAHR3 MBLNR = WA_PO5-MBLNR2
    EBELN = WA_PO5-EBELN2 EBELP = WA_PO5-EBELP2.
    IF SY-SUBRC EQ 0.
      WA_PO6-HWSTE = WA_RTAX3-HWSTE.
      WA_PO6-RATE = WA_RTAX3-RATE.
      WA_PO6-IGST = WA_RTAX3-IGST.
      WA_PO6-CGST = WA_RTAX3-CGST.
      WA_PO6-SGST = WA_RTAX3-SGST.
      WA_PO6-UGST = WA_RTAX3-UGST.
    ENDIF.
    SELECT SINGLE * FROM J_1IGRXREF WHERE MBLNR = WA_PO5-MBLNR2 AND MJAHR = WA_PO5-MJAHR2 AND ZEILE = WA_PO5-BUZEI.
    IF SY-SUBRC EQ 0.
      WA_PO6-EXBED = J_1IGRXREF-EXBED.
    ENDIF.
    SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_PO5-EBELN2 AND EBELP EQ WA_PO5-EBELP2.
    IF SY-SUBRC EQ 0.
      WA_PO6-NETPR = EKPO-NETPR.
      WA_PO6-PEINH = EKPO-PEINH.
      WA_PO6-MWSKZ = EKPO-MWSKZ.
      SELECT SINGLE * FROM T007S WHERE SPRAS EQ 'EN' AND KALSM EQ 'TAXINN' AND MWSKZ EQ EKPO-MWSKZ.
      IF SY-SUBRC EQ 0.
        WA_PO6-TAXDESC = T007S-TEXT1.
      ELSE.
        SELECT SINGLE * FROM T007S WHERE SPRAS EQ 'EN' AND KALSM EQ 'TAXINJ' AND MWSKZ EQ EKPO-MWSKZ.
        IF SY-SUBRC EQ 0.
          WA_PO6-TAXDESC = T007S-TEXT1.
        ENDIF.
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_PO5-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_PO6-MAKTX = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_PO5-MATNR1 AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_PO6-MAKTX1 = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_PO5-LIFNR2.
    IF SY-SUBRC EQ 0.
      WA_PO6-NAME1 = LFA1-NAME1.
      WA_PO6-ORT01 = LFA1-ORT01.
    ENDIF.
    COLLECT WA_PO6 INTO IT_PO6.
    CLEAR WA_PO6.
  ENDLOOP.
*
**  LOOP AT IT_PO5 INTO WA_PO5.
**     WRITE : / '5', WA_PO5-EBELN,WA_PO5-EBELP,WA_PO5-BELNR,WA_PO5-MATNR1,WA_PO5-CHARG1,WA_PO5-MENGE1,WA_PO5-DMBTR1,
**    WA_PO5-BUZEI,WA_PO5-BWART, WA_PO5-BUDAT,WA_PO5-MENGE, WA_PO5-DMBTR, WA_PO5-XBLNR,WA_PO5-MATNR,WA_PO5-WERKS,
**    WA_PO5-CHARG,WA_PO5-EBELN2,WA_PO5-EBELP2,WA_PO5-MBLNR2,WA_PO5-MJAHR2,WA_PO5-BWART2,WA_PO5-MENGE2,WA_PO5-DMBTR2,
**    WA_PO5-BELNR3,WA_PO5-GJAHR3,WA_PO5-LIFNR2,WA_PO5-NAME1,WA_PO5-ORT01, WA_PO5-HWSTE,WA_PO5-RATE,WA_PO5-IGST,WA_PO5-CGST,WA_PO5-SGST,WA_PO5-UGST.
**  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'EBELN'.
  WA_FIELDCAT-SELTEXT_L = 'LLM PO'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELP'.
  WA_FIELDCAT-SELTEXT_L = 'LL PO ITEM'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BELNR'.
  WA_FIELDCAT-SELTEXT_L = 'LL RECEIPT GRN'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*  WA_FIELDCAT-FIELDNAME = 'BUZEI'.
*  WA_FIELDCAT-SELTEXT_L = 'BUZEI'.
*  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BWART'.
  WA_FIELDCAT-SELTEXT_L = 'LL MOVEMENT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDAT'.
  WA_FIELDCAT-SELTEXT_L = 'LL POSTING DT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'FIN.PRODUCT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'FIN.PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
  WA_FIELDCAT-SELTEXT_L = 'FIN.BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MENGE'.
  WA_FIELDCAT-SELTEXT_L = 'PO QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DMBTR'.
  WA_FIELDCAT-SELTEXT_L = 'PO VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*  WA_FIELDCAT-FIELDNAME = 'XBLNR'.
*  WA_FIELDCAT-SELTEXT_L = 'REF'.
*  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'MATNR1'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX1'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG1'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MENGE1'.
  WA_FIELDCAT-SELTEXT_L = 'QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DMBTR1'.
  WA_FIELDCAT-SELTEXT_L = 'VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELN2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELP2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO ITEM'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MBLNR2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM GRN'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MJAHR2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM GRN YR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BWART2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM GRN MOV'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MENGE2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DMBTR2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BELNR3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM MIRO'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GJAHR3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM MIRO YR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'LIFNR2'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ORT01'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR CITY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

*****************************
  WA_FIELDCAT-FIELDNAME = 'LIFNR3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR1'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VNAME3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR NAME1'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VORT01_3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO VENDOR CITY1'.
  APPEND WA_FIELDCAT TO FIELDCAT.

****************************
*
  WA_FIELDCAT-FIELDNAME = 'EXBED'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM PO EXCIDE DUTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
*
*
  WA_FIELDCAT-FIELDNAME = 'HWSTE'.
  WA_FIELDCAT-SELTEXT_L = 'GST TAX VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'RATE'.
  WA_FIELDCAT-SELTEXT_L = 'GST RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'IGST'.
  WA_FIELDCAT-SELTEXT_L = 'IGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CGST'.
  WA_FIELDCAT-SELTEXT_L = 'CGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SGST'.
  WA_FIELDCAT-SELTEXT_L = 'SGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'UGST'.
  WA_FIELDCAT-SELTEXT_L = 'UGST VAL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETPR'.
  WA_FIELDCAT-SELTEXT_L = 'PO RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PEINH'.
  WA_FIELDCAT-SELTEXT_L = 'PO RATE UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MWSKZ'.
  WA_FIELDCAT-SELTEXT_L = 'PO TAX CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'TAXDESC'.
  WA_FIELDCAT-SELTEXT_L = 'PO TAX CODE DESC.'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
**  WA_FIELDCAT-fieldname = 'AUGBL'.
**  WA_FIELDCAT-seltext_L = 'CLEARING DOC'.
**  APPEND WA_FIELDCAT TO FIELDCAT.




  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'PLANT WISE STOCK TRANSFER DETAIL'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_PO6
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.



ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  TOP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'DETAILS'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'MBLNR'.
      SET PARAMETER ID 'MBN' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'MIGO' AND SKIP FIRST SCREEN.
    WHEN 'EBELN'.
      SET PARAMETER ID 'BES' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'ME23N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM
*&---------------------------------------------------------------------*
*&      Form  TAX
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM TAX .
  IF IT_TAX1 IS NOT INITIAL.
    SELECT * FROM BSEG INTO TABLE IT_BSEG FOR ALL ENTRIES IN IT_TAX1 WHERE BUKRS EQ '1000' AND BELNR EQ IT_TAX1-BELNR
      AND GJAHR EQ IT_TAX1-GJAHR AND EBELN EQ IT_TAX1-EBELN AND EBELP EQ IT_TAX1-EBELP.
    IF SY-SUBRC EQ 0.
      SELECT * FROM BSET INTO TABLE IT_BSET FOR ALL ENTRIES IN IT_BSEG WHERE BUKRS EQ '1000' AND BELNR EQ
        IT_BSEG-BELNR AND GJAHR EQ IT_BSEG-GJAHR AND TXGRP EQ IT_BSEG-TXGRP.
    ENDIF.
  ENDIF.
*  BREAK-POINT.

  LOOP AT IT_BSET INTO WA_BSET .
    READ TABLE IT_BSEG INTO WA_BSEG WITH KEY BELNR = WA_BSET-BELNR GJAHR = WA_BSET-GJAHR TXGRP = WA_BSET-TXGRP.
    IF SY-SUBRC EQ 0.
*     READ TABLE IT_TAX1 INTO WA_TAX1 WITH KEY BELNR = WA_BSEG-BELNR GJAHR = WA_BSEG-GJAHR EBELN = WA_BSEG-EBELN
*     EBELP = WA_BSEG-EBELP.
*     IF SY-SUBRC EQ 0.
      WA_TAX2-EBELN = WA_BSEG-EBELN.
      WA_TAX2-EBELP = WA_BSEG-EBELP.
      WA_TAX2-BELNR = WA_BSET-BELNR.
      WA_TAX2-GJAHR = WA_BSET-GJAHR.
      WA_TAX2-MENGE = WA_BSEG-MENGE.
*     WA_TAX2-MWSKZ = WA_BSET-MWSKZ.
      WA_TAX2-TXGRP = WA_BSET-TXGRP.

      IF WA_BSET-SHKZG EQ 'H'.
        WA_BSET-HWSTE = WA_BSET-HWSTE * ( - 1 ).
        WA_BSET-HWBAS = WA_BSET-HWBAS * ( - 1 ).
      ENDIF.
*     IF WA_BSET-KTOSL NE 'VS1'.
      WA_TAX2-HWSTE = WA_BSET-HWSTE.
      IF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JOI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX2-IGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIC'.
        WA_TAX2-CGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIS'.
        WA_TAX2-SGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIU'.
        WA_TAX2-UGST = WA_BSET-HWSTE.
      ELSE.
*       WA_TAX2-OTHR = WA_BSET-HWSTE.
      ENDIF.
*     ENDIF.
      IF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JRI' OR WA_BSET-KTOSL EQ 'JOI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX2-RATE = ( WA_BSET-KBETR / 10 ).
*     ELSEIF WA_BSET-KTOSL EQ 'NVV'.
*      WA_TAX2-RATE = ( WA_BSET-KBETR / 10 ).
      ELSE.
        WA_TAX2-RATE = ( WA_BSET-KBETR / 10 ) * 2.
      ENDIF.
*     WA_TAX1-KTOSL = WA_BSET-KTOSL.
      IF WA_BSET-KTOSL EQ 'JII'.
        WA_TAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JIC'.
        WA_TAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JRC'.
*     WA_TAX1-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JOI'.
        WA_TAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX2-HWBAS = WA_BSET-HWBAS.
*     ELSEIF WA_BSET-KTOSL EQ 'NVV'.
*     WA_TAX2-HWBAS = WA_BSET-HWBAS.
      ENDIF.
      COLLECT WA_TAX2 INTO IT_TAX2.
      CLEAR WA_TAX2.
*    ENDIF.
    ENDIF.
  ENDLOOP.
*BREAK-POINT.
  LOOP AT IT_TAX2 INTO WA_TAX2.
    CLEAR : TAX.
    TAX = WA_TAX2-IGST + WA_TAX2-CGST.
    IF TAX GT 0.
      WA_TAX3-BELNR = WA_TAX2-BELNR.
      WA_TAX3-GJAHR = WA_TAX2-GJAHR.
      WA_TAX3-TXGRP = WA_TAX2-TXGRP.

      WA_TAX3-MENGE = WA_TAX2-MENGE.
      WA_TAX3-HWBAS = WA_TAX2-HWBAS.
      WA_TAX3-HWSTE = WA_TAX2-HWSTE.
      WA_TAX3-IGST = WA_TAX2-IGST.
      WA_TAX3-CGST = WA_TAX2-CGST.
      WA_TAX3-SGST = WA_TAX2-SGST.
      WA_TAX3-UGST = WA_TAX2-UGST.
      WA_TAX3-RATE = WA_TAX2-RATE.
      WA_TAX3-EBELN = WA_TAX2-EBELN.
      WA_TAX3-EBELP = WA_TAX2-EBELP.
      COLLECT WA_TAX3 INTO IT_TAX3.
      CLEAR WA_TAX3.
    ENDIF.
  ENDLOOP.
*BREAK-POINT.
*LOOP AT IT_TAX1 INTO WA_TAX1.
*  WRITE : / 'A',WA_TAX1-BELNR,WA_TAX1-GJAHR,WA_TAX1-MATNR,WA_TAX1-EBELN,WA_TAX1-EBELP.
*ENDLOOP.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  TAX1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM TAX1 .

  IF IT_PO5 IS NOT INITIAL.
    SELECT * FROM BSEG INTO TABLE IT_BSEG FOR ALL ENTRIES IN IT_PO5 WHERE BUKRS EQ '1000' AND BELNR
      EQ IT_PO5-BELNR3 AND GJAHR EQ IT_PO5-GJAHR3 AND EBELN EQ IT_PO5-EBELN2 AND EBELP EQ IT_PO5-EBELP2 .
*      AND MATNR EQ IT_PO5-MATNR1.
    IF SY-SUBRC EQ 0.
      SELECT * FROM BSET INTO TABLE IT_BSET FOR ALL ENTRIES IN IT_BSEG WHERE BUKRS EQ '1000' AND BELNR EQ
        IT_BSEG-BELNR AND GJAHR EQ IT_BSEG-GJAHR AND TXGRP EQ IT_BSEG-TXGRP.
    ENDIF.
  ENDIF.


  LOOP AT IT_BSET INTO WA_BSET .
    READ TABLE IT_BSEG INTO WA_BSEG WITH KEY BELNR = WA_BSET-BELNR GJAHR = WA_BSET-GJAHR TXGRP = WA_BSET-TXGRP.
    IF SY-SUBRC EQ 0.
      WA_RTAX2-EBELN = WA_BSEG-EBELN.
      WA_RTAX2-EBELP = WA_BSEG-EBELP.
      WA_RTAX2-BELNR = WA_BSET-BELNR.
      WA_RTAX2-GJAHR = WA_BSET-GJAHR.
      WA_RTAX2-TXGRP = WA_BSET-TXGRP.
      READ TABLE IT_PO5 INTO WA_PO5 WITH KEY BELNR3 = WA_BSEG-BELNR GJAHR3 = WA_BSEG-GJAHR EBELN2 = WA_BSEG-EBELN
      EBELP2 = WA_BSEG-EBELP.
      IF SY-SUBRC EQ 0.
        WA_RTAX2-MBLNR = WA_PO5-MBLNR2.
        WA_RTAX2-MJAHR = WA_PO5-MJAHR2.
        WA_RTAX2-MATNR = WA_PO5-MATNR.
      ENDIF.
*     WA_RTAX2-MWSKZ = WA_BSET-MWSKZ.
      IF WA_BSET-SHKZG EQ 'H'.
        WA_BSET-HWSTE = WA_BSET-HWSTE * ( - 1 ).
        WA_BSET-HWBAS = WA_BSET-HWBAS * ( - 1 ).
      ENDIF.
      WA_RTAX2-HWSTE = WA_BSET-HWSTE.
      IF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JOI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_RTAX2-IGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIC'.
        WA_RTAX2-CGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIS'.
        WA_RTAX2-SGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JIU'.
        WA_RTAX2-UGST = WA_BSET-HWSTE.
      ELSE.
*       WA_RTAX2-OTHR = WA_BSET-HWSTE.
      ENDIF.
*     ENDIF.
      IF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JRI' OR WA_BSET-KTOSL EQ 'JOI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_RTAX2-RATE = ( WA_BSET-KBETR / 10 ).
*     ELSEIF WA_BSET-KTOSL EQ 'NVV'.
*      WA_RTAX2-RATE = ( WA_BSET-KBETR / 10 ).
      ELSE.
        WA_RTAX2-RATE = ( WA_BSET-KBETR / 10 ) * 2.
      ENDIF.
*     WA_RTAX1-KTOSL = WA_BSET-KTOSL.
      IF WA_BSET-KTOSL EQ 'JII'.
        WA_RTAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JIC'.
        WA_RTAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JRC'.
*     WA_RTAX1-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JOI'.
        WA_RTAX2-HWBAS = WA_BSET-HWBAS.
      ELSEIF WA_BSET-KTOSL EQ 'JIM'.
        WA_RTAX2-HWBAS = WA_BSET-HWBAS.
*     ELSEIF WA_BSET-KTOSL EQ 'NVV'.
*     WA_RTAX2-HWBAS = WA_BSET-HWBAS.
      ENDIF.
      COLLECT WA_RTAX2 INTO IT_RTAX2.
      CLEAR WA_RTAX2.
*    ENDIF.
    ENDIF.
  ENDLOOP.

  LOOP AT IT_RTAX2 INTO WA_RTAX2.
    CLEAR : RTAX.
    RTAX = WA_RTAX2-IGST + WA_RTAX2-CGST.
    SELECT SINGLE * FROM EKKO WHERE EBELN EQ WA_RTAX2-EBELN AND BSART EQ 'ZUB'.
    IF SY-SUBRC EQ 0.
      WA_RTAX3-MBLNR = WA_RTAX2-MBLNR.
      WA_RTAX3-MJAHR = WA_RTAX2-MJAHR.
      WA_RTAX3-MATNR = WA_RTAX2-MATNR.
*   WA_RTAX3-TXGRP = WA_RTAX2-TXGRP.
      WA_RTAX3-BELNR = WA_RTAX2-BELNR.
      WA_RTAX3-GJAHR = WA_RTAX2-GJAHR.
*   WA_RTAX3-TXGRP = WA_RTAX2-TXGRP.
      WA_RTAX3-HWBAS = WA_RTAX2-HWBAS * ( - 1 ).
      WA_RTAX3-HWSTE = WA_RTAX2-HWSTE * ( - 1 ).
      WA_RTAX3-IGST = WA_RTAX2-IGST * ( - 1 ).
      WA_RTAX3-CGST = WA_RTAX2-CGST * ( - 1 ).
      WA_RTAX3-SGST = WA_RTAX2-SGST * ( - 1 ).
      WA_RTAX3-UGST = WA_RTAX2-UGST * ( - 1 ).
      WA_RTAX3-RATE = WA_RTAX2-RATE.
      WA_RTAX3-EBELN = WA_RTAX2-EBELN.
      WA_RTAX3-EBELP = WA_RTAX2-EBELP.
      COLLECT WA_RTAX3 INTO IT_RTAX3.
      CLEAR WA_RTAX3.
    ELSE.
      IF RTAX GT 0.
        WA_RTAX3-MBLNR = WA_RTAX2-MBLNR.
        WA_RTAX3-MJAHR = WA_RTAX2-MJAHR.
        WA_RTAX3-MATNR = WA_RTAX2-MATNR.
*   WA_RTAX3-TXGRP = WA_RTAX2-TXGRP.
        WA_RTAX3-BELNR = WA_RTAX2-BELNR.
        WA_RTAX3-GJAHR = WA_RTAX2-GJAHR.
*   WA_RTAX3-TXGRP = WA_RTAX2-TXGRP.
        WA_RTAX3-HWBAS = WA_RTAX2-HWBAS.
        WA_RTAX3-HWSTE = WA_RTAX2-HWSTE.
        WA_RTAX3-IGST = WA_RTAX2-IGST.
        WA_RTAX3-CGST = WA_RTAX2-CGST.
        WA_RTAX3-SGST = WA_RTAX2-SGST.
        WA_RTAX3-UGST = WA_RTAX2-UGST.
        WA_RTAX3-RATE = WA_RTAX2-RATE.
        WA_RTAX3-EBELN = WA_RTAX2-EBELN.
        WA_RTAX3-EBELP = WA_RTAX2-EBELP.
        COLLECT WA_RTAX3 INTO IT_RTAX3.
        CLEAR WA_RTAX3.
      ENDIF.
    ENDIF.
  ENDLOOP.

*LOOP AT IT_RTAX3 INTO WA_RTAX3.
*  WRITE : / 'TAX',WA_RTAX3-MBLNR,WA_RTAX3-MJAHR,WA_RTAX3-BELNR,WA_RTAX3-GJAHR,WA_RTAX3-MATNR,
*  WA_RTAX3-EBELN,WA_RTAX3-EBELP,WA_RTAX3-HWBAS,WA_RTAX3-HWSTE,WA_RTAX3-RATE,WA_RTAX3-IGST,WA_RTAX3-CGST,
*  WA_RTAX3-SGST,WA_RTAX3-UGST.
*ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PODET
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM PODET .
  SORT IT_MAT1 BY MATNR CHARG.
  DELETE ADJACENT DUPLICATES FROM IT_MAT1 COMPARING MATNR CHARG.
  CLEAR : IT_MSEG ,WA_MSEG.
  IF IT_MAT1 IS NOT INITIAL.
    SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN  IT_MAT1 WHERE MATNR EQ IT_MAT1-MATNR AND CHARG EQ IT_MAT1-CHARG AND BWART EQ '309'.
  ENDIF.

  IF IT_MAT1 IS NOT INITIAL.
    LOOP AT IT_MAT1 INTO WA_MAT1.
      READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MATNR = WA_MAT1-MATNR CHARG = WA_MAT1-CHARG.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR AND CHARG = WA_MSEG-CHARG AND XAUTO = ' '.
        IF SY-SUBRC EQ 0.
          WA_TP2-MATNR = WA_MAT1-MATNR.
          WA_TP2-CHARG = WA_MAT1-CHARG.
          WA_TP2-MATNR1 = MSEG-MATNR.
          WA_TP2-CHARG1 = MSEG-CHARG.
          IF WA_TP2-MATNR EQ WA_TP2-MATNR1.
            IF WA_TP2-CHARG EQ WA_TP2-CHARG1.
              DELETE IT_MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR.
              READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MATNR = WA_MAT1-MATNR CHARG = WA_MAT1-CHARG.
              IF SY-SUBRC EQ 0.
                SELECT SINGLE * FROM MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR AND XAUTO = ' '.
                IF SY-SUBRC EQ 0.
                  WA_TP2-MATNR = WA_MAT1-MATNR.
                  WA_TP2-CHARG = WA_MAT1-CHARG.
                  WA_TP2-MATNR1 = MSEG-MATNR.
                  WA_TP2-CHARG1 = MSEG-CHARG.
                ENDIF.
              ENDIF.
            ENDIF.
          ENDIF.
          COLLECT WA_TP2 INTO IT_TP2.
          CLEAR WA_TP2.
        ELSE.
          SELECT SINGLE * FROM MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR AND XAUTO = ' '.
          IF SY-SUBRC EQ 0.
            WA_TP2-MATNR = WA_MAT1-MATNR.
            WA_TP2-CHARG = WA_MAT1-CHARG.
            WA_TP2-MATNR1 = MSEG-MATNR.
            WA_TP2-CHARG1 = MSEG-CHARG.
            IF WA_TP2-MATNR EQ WA_TP2-MATNR1.
              IF WA_TP2-CHARG EQ WA_TP2-CHARG1.
                DELETE IT_MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR.
                READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MATNR = WA_MAT1-MATNR CHARG = WA_MAT1-CHARG.
                IF SY-SUBRC EQ 0.
                  SELECT SINGLE * FROM MSEG WHERE MBLNR = WA_MSEG-MBLNR AND MJAHR = WA_MSEG-MJAHR AND XAUTO = ' '.
                  IF SY-SUBRC EQ 0.
                    WA_TP2-MATNR = WA_MAT1-MATNR.
                    WA_TP2-CHARG = WA_MAT1-CHARG.
                    WA_TP2-MATNR1 = MSEG-MATNR.
                    WA_TP2-CHARG1 = MSEG-CHARG.
                  ENDIF.
                ENDIF.
              ENDIF.
            ENDIF.
            COLLECT WA_TP2 INTO IT_TP2.
            CLEAR WA_TP2.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDLOOP.
  ENDIF.
  CLEAR : IT_MSEG,WA_MSEG,IT_EKPO,WA_EKPO.

  IF IT_TP2 IS NOT INITIAL.
*    SELECT * FROM MCHA INTO TABLE IT_MCHA FOR ALL ENTRIES IN IT_MAT2 WHERE CHARG EQ IT_MAT1-CHARG1.
*    IF SY-SUBRC EQ 0.
*      SELECT * FROM MKPF INTO TABLE IT_MKPF FOR ALL ENTRIES IN IT_MCHA WHERE BUDAT EQ IT_MCHA-LWEDT AND VGART EQ 'WE'.
*      IF SY-SUBRC EQ 0.
    SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN  IT_TP2 WHERE MATNR EQ IT_TP2-MATNR1 AND CHARG EQ IT_TP2-CHARG1 AND BWART IN ('101','102').
    IF SY-SUBRC EQ 0.
      SELECT * FROM EKPO INTO TABLE IT_EKPO FOR ALL ENTRIES IN IT_MSEG WHERE EBELN = IT_MSEG-EBELN AND EBELP = IT_MSEG-EBELP.
    ENDIF.
  ENDIF.


  IF IT_MSEG IS NOT INITIAL.
    LOOP AT IT_MSEG INTO WA_MSEG.
      IF WA_MSEG-SHKZG EQ 'H'.
        WA_MSEG-DMBTR = WA_MSEG-DMBTR * ( - 1 ).
        WA_MSEG-MENGE = WA_MSEG-MENGE * ( - 1 ).
      ENDIF.
      READ TABLE IT_TP2 INTO WA_TP2 WITH KEY MATNR1 = WA_MSEG-MATNR CHARG1 = WA_MSEG-CHARG.
      IF SY-SUBRC EQ 0.
*      WA_STK2-MATNR = WA_MSEG-MATNR.
*      WA_STK2-CHARG = WA_MSEG-CHARG.
        WA_STK2-MATNR = WA_TP2-MATNR.
        WA_STK2-CHARG = WA_TP2-CHARG.
        WA_STK2-DMBTR = WA_MSEG-DMBTR.
        WA_STK2-MENGE = WA_MSEG-MENGE.
        WA_STK2-EBELN = WA_MSEG-EBELN.
        WA_STK2-EBELP = WA_MSEG-EBELP.
        WA_STK2-WERKS = WA_MSEG-WERKS.
        WA_STK2-MBLNR = WA_MSEG-MBLNR.
        WA_STK2-MJAHR = WA_MSEG-MJAHR.
        WA_STK2-BWART = WA_MSEG-BWART.
        WA_STK2-MENGE = WA_MSEG-MENGE.
        WA_STK2-DMBTR = WA_MSEG-DMBTR.
        WA_STK2-LIFNR = WA_MSEG-LIFNR.
        WA_STK2-EMLIF = WA_MSEG-EMLIF.
        COLLECT WA_STK2 INTO IT_STK2.
        CLEAR WA_STK2.
      ENDIF.
    ENDLOOP.
  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  TRFVAL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM TRFVAL.

  LOOP AT IT_TAP1 INTO WA_TAP1.
    CLEAR : VAL11.
    WRITE:/ 'a',WA_TAP1-VBELN,WA_TAP1-BELNR,WA_TAP1-MATNR,WA_TAP1-CHARG,WA_TAP1-MENGE.
    SELECT SINGLE * FROM VBRK WHERE VBELN EQ WA_TAP1-VBELN.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM VBRP WHERE VBELN EQ VBRK-VBELN AND MATNR EQ WA_TAP1-MATNR AND CHARG EQ WA_TAP1-CHARG AND FKIMG GT 0.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM prcd_elements WHERE KNUMV EQ VBRK-KNUMV AND KPOSN EQ VBRP-POSNR AND KRECH EQ 'C'.
        IF SY-SUBRC EQ 0.
          VAL11 =  prcd_elements-KBETR / prcd_elements-KPEIN.
          VAL12 = VAL11 * VBRP-FKIMG.
          WRITE : prcd_elements-KSCHL,VAL11,VAL12.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDLOOP.

ENDFORM.
