*&---------------------------------------------------------------------*
*& Report  ZAC1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZAC11 .
*NO STANDARD PAGE HEADING line-SIZE 500. "
TABLES : AUFK,
         AFPO,
         MARA,
         MVKE,
         TVM5T,
         MAKT.

TYPES : BEGIN OF ITAB1,
          AUFNR TYPE AFPO-AUFNR,
          MATNR TYPE AFPO-MATNR,
          CHARG TYPE AFPO-CHARG,
          MAKTX TYPE MAKT-MAKTX,
          PSMNG TYPE AFPO-PSMNG,
          WEMNG TYPE AFPO-WEMNG,
          BEZEI TYPE TVM5T-BEZEI,
          RATE1 TYPE P DECIMALS 2,
          MTART TYPE MARA-MTART,
        END OF ITAB1.

TYPES : BEGIN OF ITAB2,

          MATNR TYPE AFPO-MATNR,
          CHARG TYPE AFPO-CHARG,
          AUFNR TYPE AFPO-AUFNR,
          MAKTX TYPE MAKT-MAKTX,
          PSMNG TYPE AFPO-PSMNG,
          WEMNG TYPE AFPO-WEMNG,
          BEZEI TYPE TVM5T-BEZEI,
          MENGE TYPE AUFM-MENGE,
          DMBTR TYPE AUFM-DMBTR,
        END OF ITAB2.

DATA : IT_TAB1 TYPE TABLE OF ITAB1,
       WA_TAB1 TYPE ITAB1,
       IT_TAB2 TYPE TABLE OF ITAB2,
       WA_TAB2 TYPE ITAB2.

DATA : IT_AFPO TYPE TABLE OF AFPO,
       WA_AFPO TYPE AFPO,
       IT_AUFK TYPE TABLE OF AUFK,
       WA_AUFK TYPE AUFK,
       IT_AUFM TYPE TABLE OF AUFM,
       WA_AUFM TYPE AUFM,
       IT_MARA TYPE TABLE OF MARA,
       WA_MARA TYPE MARA,
       IT_MAKT TYPE TABLE OF MAKT,
       WA_MAKT TYPE MAKT.

DATA : VAL    TYPE P DECIMALS 2,
       VAL1   TYPE P DECIMALS 2,
       VAL2   TYPE P DECIMALS 2,
       QTY    TYPE P DECIMALS 3,
       RATE1  TYPE P DECIMALS 2,
       RATE2  TYPE P DECIMALS 2,
       VAL_1  TYPE P DECIMALS 2,
       TYPE1  TYPE MARA-MTART,
       W_RATE TYPE P DECIMALS 2.

DATA : COUNT  TYPE I,
       COUNT1 TYPE I.
DATA : W_UMREN LIKE MARM-UMREN,
       W_UMREZ LIKE MARM-UMREZ.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001 .
SELECT-OPTIONS  : S_MATNR FOR   AFPO-MATNR.
SELECT-OPTIONS  : S_AUFNR FOR AFPO-AUFNR.
PARAMETERS : P_WERKS LIKE AFPO-DWERK OBLIGATORY.
SELECT-OPTIONS : BATCH FOR AFPO-CHARG.
*SELECT-OPTIONS : s_lgort FOR afpo-lgort .
SELECT-OPTIONS : S_BUDAT FOR AUFK-ERDAT OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

SELECT * FROM AUFK INTO TABLE IT_AUFK WHERE
  AUFNR IN S_AUFNR AND
  ERDAT IN S_BUDAT AND
  WERKS EQ P_WERKS.
IF SY-SUBRC NE 0.
  EXIT.
ENDIF.

SELECT * FROM AFPO INTO TABLE IT_AFPO FOR
  ALL ENTRIES IN IT_AUFK WHERE
  AUFNR EQ IT_AUFK-AUFNR AND
  MATNR IN S_MATNR AND
  CHARG IN BATCH.
*      AND lgort IN s_lgort.
IF SY-SUBRC NE 0.
  EXIT.
ENDIF.


SELECT * FROM AUFM INTO TABLE IT_AUFM FOR ALL
  ENTRIES IN IT_AFPO WHERE
  AUFNR EQ IT_AFPO-AUFNR.
IF SY-SUBRC NE 0.
  EXIT.
ENDIF.

SELECT * FROM MARA INTO TABLE IT_MARA
  FOR ALL ENTRIES IN IT_AUFM
  WHERE MATNR EQ IT_AUFM-MATNR AND
        MTART IN ('ZVRP','ZROH').
IF SY-SUBRC EQ 0.
  SELECT * FROM MAKT INTO TABLE IT_MAKT
    FOR ALL ENTRIES IN IT_AUFM
    WHERE MATNR EQ IT_AUFM-MATNR.
  IF SY-SUBRC NE 0.
  ENDIF.
ENDIF.



*SORT it_afpo BY charg ASCENDING matnr DESCENDING.
SORT IT_AFPO BY MATNR.
SORT IT_AUFM BY MATNR.


LOOP AT IT_AFPO INTO WA_AFPO.

  WA_TAB1-MATNR = WA_AFPO-MATNR.
*  READ TABLE it_makt INTO wa_makt WITH KEY matnr = wa_afpo-matnr.
*  IF sy-subrc EQ 0.
**    WRITE : 31(35) wa_makt-maktx.
*    wa_tab1-maktx = wa_makt-maktx.
*  ENDIF.
  SELECT SINGLE * FROM MAKT WHERE
    MATNR EQ WA_AFPO-MATNR AND
    SPRAS EQ 'EN'.
  IF SY-SUBRC EQ 0.
    WA_TAB1-MAKTX = MAKT-MAKTX.
  ENDIF.

  SELECT SINGLE * FROM MARA WHERE MATNR = WA_AFPO-MATNR.
  IF SY-SUBRC EQ 0.
    WA_TAB1-MTART = MARA-MTART.
  ENDIF.
*  WRITE : 68 'ORDER',wa_afpo-aufnr.
  WA_TAB1-AUFNR = WA_AFPO-AUFNR.
*  WRITE : / 'BATCH SIZE',12 wa_afpo-psmng LEFT-JUSTIFIED,68 'ACTUAL QTY RECD.',wa_afpo-wemng.
  VAL_1 = WA_AFPO-WEMNG.

  WA_TAB1-PSMNG = WA_AFPO-PSMNG.
  WA_TAB1-WEMNG = WA_AFPO-WEMNG.
  SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_AFPO-MATNR.
  IF SY-SUBRC EQ 0.
    SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
    IF SY-SUBRC EQ 0.
*          WRITE : /1 'PACK SIZE',12 tvm5t-bezei LEFT-JUSTIFIED.
      WA_TAB1-BEZEI = TVM5T-BEZEI.
    ENDIF.
  ENDIF.
*  WRITE : 68 'BATCH ', wa_afpo-charg .
  WA_TAB1-CHARG = WA_AFPO-CHARG.
*  wa_afpo-dnrel.
*  ULINE.
*  WRITE : /1 'MATERIAL',31 'DESCRIPTION',68 'ID NO.',80 'QUANTITY',97 'VALUE'.
*  ULINE.


  LOOP AT IT_AUFM INTO WA_AUFM WHERE
          AUFNR EQ WA_AFPO-AUFNR.
    IF WA_AUFM-SHKZG EQ 'S'.
      WA_AUFM-MENGE = WA_AUFM-MENGE * ( - 1 ).
      WA_AUFM-DMBTR = WA_AUFM-DMBTR * ( - 1 ).
    ENDIF.

    READ TABLE IT_MARA INTO WA_MARA WITH KEY
         MATNR = WA_AUFM-MATNR .
    IF SY-SUBRC EQ 0.
*        WRITE : /1 wa_aufm-matnr LEFT-JUSTIFIED.
      WA_TAB2-AUFNR = WA_AUFM-AUFNR.
      WA_TAB2-MATNR = WA_AUFM-MATNR.
      READ TABLE IT_MAKT INTO WA_MAKT WITH KEY
             MATNR = WA_AUFM-MATNR.
      IF SY-SUBRC EQ 0.
*              WRITE : 31(35) wa_makt-maktx LEFT-JUSTIFIED.
        WA_TAB2-MAKTX = WA_MAKT-MAKTX.
      ENDIF.
*           WRITE : 68 wa_aufm-charg LEFT-JUSTIFIED,80 wa_aufm-menge LEFT-JUSTIFIED,97 wa_aufm-dmbtr LEFT-JUSTIFIED.
*           wa_tab2-charg = wa_aufm-charg.
      WA_TAB2-MENGE = WA_AUFM-MENGE.
      WA_TAB2-DMBTR = WA_AUFM-DMBTR.

*           val = val + wa_aufm-dmbtr.
*           qty = qty + wa_aufm-menge.
    ENDIF.
    COLLECT WA_TAB2 INTO IT_TAB2.
    CLEAR WA_TAB2.
  ENDLOOP.


  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.
ENDLOOP.

SORT IT_TAB1 BY CHARG ASCENDING MATNR DESCENDING.

LOOP AT IT_TAB1 INTO WA_TAB1.
  ON CHANGE OF WA_TAB1-CHARG.
    RATE1 = 0.
  ENDON.
  ON CHANGE OF WA_TAB1-AUFNR.
    IF VAL NE 0.
      ULINE.
      WRITE : /69 VAL,VAL2.
      IF W_RATE NE 0.
        WRITE : W_RATE.
      ENDIF.
    ENDIF.
  ENDON.

  FORMAT COLOR 1.
  ULINE.
  SKIP.
  WRITE : /1 'PRODUCT    :',
           WA_TAB1-MATNR,
           WA_TAB1-MAKTX,70
           'ORDER :',90
           WA_TAB1-AUFNR LEFT-JUSTIFIED.
  WRITE : /1 'BATCH SIZE :',
           WA_TAB1-PSMNG LEFT-JUSTIFIED,
           70 'ACTUAL QTY. RECD.:',
           90 WA_TAB1-WEMNG LEFT-JUSTIFIED.
  WRITE : /1 'PACK SIZE  :',WA_TAB1-BEZEI,
            70 'BATCH :',90 WA_TAB1-CHARG LEFT-JUSTIFIED.
  ULINE.
  IF WA_TAB1-MTART NE 'ZHLB'.
    WRITE : /1 'MATERIAL',20 'DESCRIPTION',
             58 'QUANTITY',80 'VALUE',
             96 'PM_rate',115 'RM_rate'.
  ELSE.
    WRITE : /1 'MATERIAL',20 'DESCRIPTION',
             58 'QUANTITY',80 'VALUE',
             96 'RATE_per_tablet'.
  ENDIF.
  ULINE.
  CLEAR VAL.
  VAL1 = WA_TAB1-WEMNG.

  LOOP AT IT_TAB2 INTO WA_TAB2 WHERE AUFNR = WA_TAB1-AUFNR.
    FORMAT COLOR 2.
    IF WA_TAB2-MENGE GT 0.  "CONDITION GIVEN ON 3.4.2019 BY JYOTSNA
      WRITE : /1 WA_TAB2-MATNR,
               15 WA_TAB2-MAKTX,
               50 WA_TAB2-MENGE,
               70 WA_TAB2-DMBTR.
      VAL = VAL + WA_TAB2-DMBTR.
    ENDIF.
  ENDLOOP.

  IF VAL1 NE 0.
    VAL2 = VAL / VAL1.
  ELSE.
    VAL2 = 0.
  ENDIF.
*    WRITE : / 'A',val2.
  IF WA_TAB1-MTART EQ 'ZHLB'.
    RATE1 = VAL2.
  ENDIF.

  IF WA_TAB1-MTART NE 'ZHLB'.
    CLEAR : W_UMREN,W_UMREZ.
    SELECT SINGLE UMREN UMREZ  FROM MARM
      INTO (W_UMREN, W_UMREZ) WHERE
       MATNR = WA_TAB1-MATNR AND
      ( MEINH = 'L' OR MEINH = 'ST'
*    SELECT SINGLE UMREN UMREZ  FROM MARM INTO (W_UMREN, W_UMREZ) WHERE MATNR = WA_TAB1-MATNR AND ( GEWEI = 'L' OR GEWEI = 'PC'
      OR MEINH = 'KG').
*      OR GEWEI = 'KG').
    IF  SY-SUBRC = 0.
      W_RATE = ( RATE1 * W_UMREN ) / W_UMREZ.
*    WRITE : 'B', rate1,w_umren,w_umrez,'A', W_RATE.
*    WRITE :  W_RATE.
      RATE2 = W_RATE.
*    W_RRATE = 0.
    ENDIF.
*       RATE2 = RATE1 * 10.
******************************************
*        ENDIF.
*      ENDIF.
  ELSE.
    RATE2 = 0.
  ENDIF.
  IF WA_TAB1-MTART EQ 'ZHLB'.
    W_RATE = 0.
  ENDIF.

  AT LAST.
    IF VAL NE 0.
      ULINE.
      WRITE : /69 VAL,VAL2.
      IF W_RATE NE 0.
        WRITE : W_RATE.
      ENDIF.
    ENDIF.
  ENDAT.
ENDLOOP.
