*&---------------------------------------------------------------------*
*& Report  ZBCLL_COSTING_ANALY1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZBCLL_COSTING_ANALY1_N1.
TABLES : MARA,
         KONP,
         MVKE,
         TVM5T,
         MAKT,
         LFA1.

TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.

DATA: IT_MARA       TYPE TABLE OF MARA,
      WA_MARA       TYPE MARA,
      IT_ZTP_COST11 TYPE TABLE OF ZTP_COST11,
      WA_ZTP_COST11 TYPE ZTP_COST11.
TYPES: BEGIN OF MAT1,
         MATNR TYPE MARA-MATNR,
       END OF MAT1.
TYPES: BEGIN OF MAT2,
         MATNR TYPE MARA-MATNR,
         MRP   TYPE KONP-KBETR,
         PTS   TYPE KONP-KBETR,
       END OF MAT2.

TYPES: BEGIN OF SMAT2,
         MATNR TYPE MARA-MATNR,
         ZSAM  TYPE KONP-KBETR,
       END OF SMAT2.
TYPES: BEGIN OF ITAB1,
         MATNR     TYPE ZTP_COST11-MATNR,
         WERKS     TYPE ZTP_COST11-WERKS,
         VBELN     TYPE ZTP_COST11-VBELN,
         GJAHR     TYPE ZTP_COST11-GJAHR,
         FGLIFNR   TYPE ZTP_COST11-FGLIFNR,
         MAKTX     TYPE MAKT-MAKTX,
         NAME1     TYPE LFA1-NAME1,
         VAL1      TYPE P DECIMALS 2,
         VAL2      TYPE P DECIMALS 2,
         VAL3      TYPE P DECIMALS 2,
         VAL4      TYPE P DECIMALS 2,
         VAL5      TYPE P DECIMALS 2,
         VAL6      TYPE P DECIMALS 2,
         MRP       TYPE KONP-KBETR,
         PTS       TYPE KONP-KBETR,
         BEZEI     TYPE TVM5T-BEZEI,
         SAMPCODE  TYPE MARA-MATNR,
         ZSAM      TYPE KONP-KBETR,
         SAMPBEZEI TYPE TVM5T-BEZEI,
       END OF ITAB1.

DATA: IT_MAT1         TYPE TABLE OF MAT1,
      WA_MAT1         TYPE MAT1,
      IT_SMAT1        TYPE TABLE OF MAT1,
      WA_SMAT1        TYPE MAT1,
      IT_SMAT2        TYPE TABLE OF SMAT2,
      WA_SMAT2        TYPE SMAT2,
      IT_MAT2         TYPE TABLE OF MAT2,
      WA_MAT2         TYPE MAT2,
      IT_TAB1         TYPE TABLE OF ITAB1,
      WA_TAB1         TYPE ITAB1,
      IT_A602         TYPE TABLE OF A602,
      WA_A602         TYPE A602,
      IT_ZPRODBATCHES TYPE TABLE OF ZPRODBATCHES,
      WA_ZPRODBATCHES TYPE ZPRODBATCHES.

DATA: VAL1 TYPE P DECIMALS 2.
DATA: GST1 TYPE P DECIMALS 2,
      VAL2 TYPE P DECIMALS 2,
      VAL3 TYPE P DECIMALS 2,
      VAL4 TYPE P DECIMALS 2,
      VAL5 TYPE P DECIMALS 2,
      VAL6 TYPE P DECIMALS 2,
      PTS  TYPE KONP-KBETR.
DATA: DATE1 TYPE SY-DATUM.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
PARAMETERS : R1 RADIOBUTTON GROUP R1 USER-COMMAND R3 DEFAULT 'X',
             R2 RADIOBUTTON GROUP R1.

SELECTION-SCREEN END OF BLOCK MERKMALE1.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE2 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: MATNR FOR MARA-MATNR.
PARAMETERS : FYEAR TYPE GJAHR.

SELECTION-SCREEN END OF BLOCK MERKMALE2.

AT SELECTION-SCREEN OUTPUT.
  IF R1 EQ 'X'.
*    CALL TRANSACTION 'ZCOST17'.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*MATNR*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*FYEAR*'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.


  ELSEIF R2 EQ 'X'.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*MATNR*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
    LOOP AT SCREEN.
      IF SCREEN-NAME CP '*FYEAR*'.
        SCREEN-ACTIVE = 1.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.
  ENDIF.

INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION.

  IF R1 EQ 'X'.
    CALL  TRANSACTION 'ZCOST17'.
  ELSEIF R2 EQ 'X'.
    PERFORM FORM11.
  ENDIF.

FORM FORM11.
  SELECT * FROM MARA INTO TABLE IT_MARA WHERE MATNR IN MATNR.
  SELECT * FROM ZTP_COST11 INTO TABLE IT_ZTP_COST11 WHERE GJAHR EQ FYEAR AND MATNR IN MATNR.
  IF IT_ZTP_COST11 IS INITIAL.
    MESSAGE 'NO DATA FOUND' TYPE 'E'.
  ENDIF.
  LOOP AT IT_MARA INTO WA_MARA.
    READ TABLE IT_ZTP_COST11 INTO WA_ZTP_COST11 WITH KEY MATNR = WA_MARA-MATNR.
    IF SY-SUBRC EQ 0.
      WA_MAT1-MATNR = WA_ZTP_COST11-MATNR.
      COLLECT WA_MAT1 INTO IT_MAT1.
      CLEAR WA_MAT1.
    ENDIF.
  ENDLOOP.
  SORT IT_MAT1 BY MATNR.
  DELETE ADJACENT DUPLICATES FROM IT_MAT1 COMPARING MATNR.
  IF IT_MAT1 IS NOT INITIAL.
    SELECT * FROM ZPRODBATCHES INTO TABLE IT_ZPRODBATCHES FOR ALL ENTRIES IN IT_MAT1 WHERE MATNR EQ IT_MAT1-MATNR AND ENDDA GE SY-DATUM.
    SORT IT_ZPRODBATCHES DESCENDING BY BEGDA.
  ENDIF.
  PERFORM MRP.
  PERFORM SAMPRATE.


  SORT IT_ZTP_COST11 DESCENDING BY VBELN.
  GST1 = 12 / 100.
  LOOP AT IT_MARA INTO WA_MARA.
    READ TABLE IT_ZTP_COST11 INTO WA_ZTP_COST11 WITH KEY MATNR = WA_MARA-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB1-MATNR = WA_ZTP_COST11-MATNR.
      WA_TAB1-WERKS = WA_ZTP_COST11-WERKS.
      WA_TAB1-VBELN = WA_ZTP_COST11-VBELN.
      WA_TAB1-GJAHR = WA_ZTP_COST11-GJAHR.
      WA_TAB1-FGLIFNR = WA_ZTP_COST11-FGLIFNR.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MARA-MATNR AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        WA_TAB1-MAKTX = MAKT-MAKTX.
      ENDIF.
      SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_ZTP_COST11-FGLIFNR.
      IF SY-SUBRC EQ 0.
        WA_TAB1-NAME1 = LFA1-NAME1.
      ENDIF.
      CLEAR: VAL1,VAL2.
      VAL1 = WA_ZTP_COST11-RP1 + WA_ZTP_COST11-M1 + WA_ZTP_COST11-CCPC + WA_ZTP_COST11-ANART.
      WA_TAB1-VAL1 = VAL1. "A
      VAL2 = GST1 * VAL1.
      WA_TAB1-VAL2 = VAL2. "B
      VAL3 = VAL1 + VAL2.
      WA_TAB1-VAL3 = VAL3.  "C
      VAL4 = ( 334 / 10000 ) * VAL3.  "D
      WA_TAB1-VAL4 = VAL4.
      VAL5 = ( VAL3 + VAL4 ) - VAL2.
      WA_TAB1-VAL5 = VAL5. "F

      READ TABLE IT_MAT2 INTO WA_MAT2 WITH KEY MATNR = WA_MARA-MATNR.
      IF SY-SUBRC EQ 0.
        WA_TAB1-MRP = WA_MAT2-MRP.
        WA_TAB1-PTS = WA_MAT2-PTS.
      ENDIF.
      IF WA_TAB1-PTS GT 0.
        VAL6 = ( VAL5 / WA_TAB1-PTS ) * 100.
      ENDIF.
      WA_TAB1-VAL6 = VAL6.
      SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_MARA-MATNR.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
        IF SY-SUBRC EQ 0.
          WA_TAB1-BEZEI = TVM5T-BEZEI.
        ENDIF.
      ENDIF.

      READ TABLE IT_ZPRODBATCHES INTO WA_ZPRODBATCHES WITH KEY MATNR = WA_MARA-MATNR.
      IF SY-SUBRC EQ 0.
        WA_TAB1-SAMPCODE = WA_ZPRODBATCHES-COMB_MATNR1.
        READ TABLE IT_SMAT2 INTO WA_SMAT2 WITH KEY MATNR = WA_ZPRODBATCHES-COMB_MATNR1.
        IF SY-SUBRC EQ 0.
          WA_TAB1-ZSAM = WA_SMAT2-ZSAM.
        ENDIF.
        SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_ZPRODBATCHES-COMB_MATNR1.
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
          IF SY-SUBRC EQ 0.
            WA_TAB1-SAMPBEZEI = TVM5T-BEZEI.
          ENDIF.
        ENDIF.
      ENDIF.
      COLLECT WA_TAB1 INTO IT_TAB1.
      CLEAR WA_TAB1.
    ENDIF.

  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FGLIFNR'.
  WA_FIELDCAT-SELTEXT_L = 'FG VENDOR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'FG VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VBELN'.
  WA_FIELDCAT-SELTEXT_L = 'COST SHEET NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GJAHR'.
  WA_FIELDCAT-SELTEXT_L = 'CS YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL1'.
  WA_FIELDCAT-SELTEXT_L = 'BASIC'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL2'.
  WA_FIELDCAT-SELTEXT_L = 'GST 12%'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL3'.
  WA_FIELDCAT-SELTEXT_L = 'TOTAL COST'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL4'.
  WA_FIELDCAT-SELTEXT_L = 'O/H ABS (3.34%)'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL2'.
  WA_FIELDCAT-SELTEXT_L = 'LESS ITC'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL5'.
  WA_FIELDCAT-SELTEXT_L = 'TOTAL COG'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL6'.
  WA_FIELDCAT-SELTEXT_L = 'COG %'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MRP'.
  WA_FIELDCAT-SELTEXT_L = 'MRP'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PTS'.
  WA_FIELDCAT-SELTEXT_L = 'PTS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'PACK'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SAMPCODE'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SAMPBEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE PACK'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ZSAM'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE COST'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'THIRD PARTY COST SHEET SUMMARY'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.                    "SUMMARY

*&---------------------------------------------------------------------*
*&      Form  TOP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'THIRD PARTY COST SHEET SUMMARY'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'VBELN'.
      SET PARAMETER ID 'VF' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VF03' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM


*&---------------------------------------------------------------------*
*&      Form  MRP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM MRP .

  DATE1 = SY-DATUM - 180.
  IF IT_MAT1 IS NOT INITIAL.
    SELECT * FROM A602 INTO TABLE IT_A602  FOR ALL ENTRIES IN IT_MAT1 WHERE KAPPL EQ 'V' AND KSCHL EQ 'Z001' AND MATNR EQ IT_MAT1-MATNR AND
    DATAB GE DATE1 AND DATBI GE SY-DATUM.
  ENDIF.
  SORT IT_A602 DESCENDING BY KNUMH.
  LOOP AT IT_MAT1 INTO WA_MAT1.
    READ TABLE IT_A602 INTO WA_A602 WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM KONP WHERE KNUMH EQ WA_A602-KNUMH AND KBETR GT 0.
      IF SY-SUBRC EQ 0.
        CLEAR : PTS.
*        WRITE : / 'mrp',WA_MAT1-MATNR,WA_A602-CHARG,KONP-KBETR.
        PTS = ( ( 6429 / 100 ) * KONP-KBETR ) / 100.
*        WRITE : 'pts',PTS.
        WA_MAT2-MATNR = WA_MAT1-MATNR.
        WA_MAT2-MRP = KONP-KBETR.
        WA_MAT2-PTS = PTS.
        COLLECT WA_MAT2 INTO IT_MAT2.
        CLEAR WA_MAT2.
      ENDIF.
    ENDIF.

    READ TABLE IT_ZPRODBATCHES INTO WA_ZPRODBATCHES WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_SMAT1-MATNR = WA_ZPRODBATCHES-COMB_MATNR1.
      COLLECT WA_SMAT1 INTO IT_SMAT1.
      CLEAR WA_SMAT1.
    ENDIF.
  ENDLOOP.

  SORT IT_SMAT1 BY MATNR.
  DELETE ADJACENT DUPLICATES FROM IT_SMAT1 COMPARING MATNR.
  CLEAR: IT_A602,WA_A602.
  IF IT_SMAT1 IS NOT INITIAL.
    SELECT * FROM A602 INTO TABLE IT_A602  FOR ALL ENTRIES IN IT_SMAT1 WHERE KAPPL EQ 'V' AND KSCHL EQ 'ZSAM' AND MATNR EQ IT_SMAT1-MATNR AND
    DATAB GE DATE1 AND DATBI GE SY-DATUM.
  ENDIF.
  SORT IT_A602 DESCENDING BY KNUMH.

  LOOP AT IT_SMAT1 INTO WA_SMAT1.
    READ TABLE IT_A602 INTO WA_A602 WITH KEY MATNR = WA_SMAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM KONP WHERE KNUMH EQ WA_A602-KNUMH AND KBETR GT 0.
      IF SY-SUBRC EQ 0.
        WA_SMAT2-MATNR = WA_SMAT1-MATNR.
        WA_SMAT2-ZSAM = KONP-KBETR.
        COLLECT WA_SMAT2 INTO IT_SMAT2.
        CLEAR WA_SMAT2.
      ENDIF.
    ENDIF.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SAMPRATE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM SAMPRATE.


ENDFORM.
