PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBUDGET_PRICE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBUDGET_PRICE-WERKS .
    FIELD ZBUDGET_PRICE-MATNR .
    FIELD ZBUDGET_PRICE-MEINS .
    FIELD ZBUDGET_PRICE-BUD_MON .
    FIELD ZBUDGET_PRICE-BUD_YEAR .
    FIELD ZBUDGET_PRICE-BUD_PRICE .
    FIELD ZBUDGET_PRICE-CURRENCY .
    FIELD ZBUDGET_PRICE-LIFNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBUDGET_PRICE-WERKS .
    FIELD ZBUDGET_PRICE-MATNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
