class ZCL_ZF_RGP_APPROVE_AUT_DPC_EXT definition
  public
  inheriting from ZCL_ZF_RGP_APPROVE_AUT_DPC
  create public .

public section.
protected section.

  methods ADMINPANELSET_GET_ENTITYSET
    redefinition .
  methods ADMINPANELSET_GET_ENTITY
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZF_RGP_APPROVE_AUT_DPC_EXT IMPLEMENTATION.


  METHOD ADMINPANELSET_GET_ENTITY.

*    DATA(LS_KEY) = IO_TECH_REQUEST_CONTEXT->GET_KEYS( ).
*    DATA(LS_KEY) = KEYS[ 1 ]-VALUE.
*    SELECT SINGLE FROM AGR_USERS FIELDS UNAME WHERE AGR_NAME = @LS_KEY AND UNAME INTO @DATA(UNAME).
*    "select single Agr_Users fields UNAME where AGR_NAME = LS_KEY INTO table @data(uname).
*    ER_ENTITY-ROLE = LS_KEY.
*    ER_ENTITY-USER = UNAME.


    DATA(KEYS) = IO_TECH_REQUEST_CONTEXT->GET_KEYS( ).

    READ TABLE KEYS INTO DATA(WA_KEYS) WITH KEY NAME = 'ROLE'.
    IF SY-SUBRC EQ 0.
      DATA(LS_KEY1) = WA_KEYS-VALUE .
    ENDIF.
    CLEAR:WA_KEYS .
    READ TABLE KEYS INTO WA_KEYS WITH KEY NAME = 'USER'.
    IF SY-SUBRC EQ 0.
      DATA(LS_KEY2) = WA_KEYS-VALUE .
    ENDIF.


*    IF  WA_SEL-LOW IS NOT INITIAL OR WA_SEL-HIGH IS NOT INITIAL .
    SELECT  SINGLE FROM AGR_USERS FIELDS UNAME ,AGR_NAME
       WHERE AGR_NAME  = @LS_KEY1
           AND UNAME = @LS_KEY2
              INTO @DATA(WA_AGR_NAME).
    IF SY-SUBRC EQ 0 .
      ER_ENTITY-USER = WA_AGR_NAME-UNAME.
      ER_ENTITY-ROLE = WA_AGR_NAME-AGR_NAME.
      ER_ENTITY-FLAG = 'X'.
    ELSE.
      ER_ENTITY-USER = LS_KEY2.
      ER_ENTITY-ROLE = LS_KEY1.
      ER_ENTITY-FLAG = ' '.
    ENDIF.
*    ENDIF.

  ENDMETHOD.


  METHOD ADMINPANELSET_GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->ADMINPANELSET_GET_ENTITYSET
*  EXPORTING
*    IV_ENTITY_NAME           =
*    IV_ENTITY_SET_NAME       =
*    IV_SOURCE_NAME           =
*    IT_FILTER_SELECT_OPTIONS =
*    IS_PAGING                =
*    IT_KEY_TAB               =
*    IT_NAVIGATION_PATH       =
*    IT_ORDER                 =
*    IV_FILTER_STRING         =
*    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ET_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.


    DATA(LT_KEY) = IT_FILTER_SELECT_OPTIONS.
*    DATA(LS_KEY1) = LS_KEY[ 1 ]-SELECT_OPTIONS.
*
*    READ TABLE LS_KEY INTO DATA(LT_USER) INDEX 2 .
*
*    READ TABLE lt_USER-SELECT_OPTIONS INTO DATA(wa_sel) INDEX 1 .
*
*    if  wa_sel-LOW is NOT INITIAL or wa_sel-HIGH is NOT INITIAL .
*
*    SELECT FROM AGR_USERS FIELDS UNAME
*       WHERE AGR_NAME  IN @LS_KEY1
*           AND UNAME IN @lt_USER-SELECT_OPTIONS
*              INTO TABLE @DATA(UNAME).
*
*      else.
*     SELECT FROM AGR_USERS FIELDS UNAME
*       WHERE AGR_NAME  IN @LS_KEY1
**           AND UNAME IN @lt_USER-SELECT_OPTIONS
*              INTO TABLE @UNAME .
*
*        endif.
**ER_ENTITY-ROLE = LS_KEY.
**ER_ENTITY-USER = UNAME.
*
*
*
*    ET_ENTITYSET = VALUE #( FOR LS_ENTITY IN UNAME
*                            ( ROLE = LS_ENTITY-UNAME ) ).

    DATA: ER_ENTITYSET LIKE LINE OF  ET_ENTITYSET .
*    DATA(KEYS) = IO_TECH_REQUEST_CONTEXT->GET_KEYS( ).

    READ TABLE LT_KEY INTO DATA(WA_KEYS) WITH KEY PROPERTY = 'Role'.
    IF SY-SUBRC EQ 0.
      DATA(LS_KEY1) = WA_KEYS-SELECT_OPTIONS .
    ENDIF.
    CLEAR:WA_KEYS .
    READ TABLE LT_KEY INTO WA_KEYS WITH KEY PROPERTY = 'User'.
    IF SY-SUBRC EQ 0.
      DATA(LS_KEY2) =  WA_KEYS-SELECT_OPTIONS .
    ENDIF.


   READ TABLE LS_KEY1 INTO DATA(LS_KEY11) INDEX 1 .
   READ TABLE LS_KEY2 INTO DATA(LS_KEY22) INDEX 1  .

*    IF  WA_SEL-LOW IS NOT INITIAL OR WA_SEL-HIGH IS NOT INITIAL .
    SELECT  SINGLE FROM AGR_USERS FIELDS UNAME ,AGR_NAME
       WHERE AGR_NAME  = @LS_KEY11-LOW
           AND UNAME = @LS_KEY22-LOW
              INTO @DATA(WA_AGR_NAME).
    IF SY-SUBRC EQ 0 .
      ER_ENTITYSET-USER = WA_AGR_NAME-UNAME.
      ER_ENTITYSET-ROLE = WA_AGR_NAME-AGR_NAME.
      ER_ENTITYSET-FLAG = 'X'.
    ELSE.
      ER_ENTITYSET-USER = LS_KEY22-LOW.
      ER_ENTITYSET-ROLE = LS_KEY11-LOW.
      ER_ENTITYSET-FLAG = ' '.
    ENDIF.

    APPEND ER_ENTITYSET TO  ET_ENTITYSET .
    CLEAR : ER_ENTITYSET .
  ENDMETHOD.
ENDCLASS.
