"Name: \PR:SAPLCOBC\FO:READ_RESB_IND_CONV\SE:BEGIN\EI
ENHANCEMENT 0 ZCO01_4.
***ENHANCED BY JYOTSNA ON 17.2.25 TO RESTRCIT PM IN CO01/CO02 IF NOT IN BOM
DATA: RG_AUART TYPE RANGE OF AUFART.

RG_AUART = VALUE #( ( SIGN = 'I' OPTION = 'EQ' LOW = 'ZGP1' )
                    ( SIGN = 'I' OPTION = 'EQ' LOW = 'ZGR1' )
                    ( SIGN = 'I' OPTION = 'EQ' LOW = 'ZNP1' )
                    ( SIGN = 'I' OPTION = 'EQ' LOW = 'ZNR1' ) ).

IF CAUFVD-AUART NOT IN RG_AUART.
  IF RESB_BT IS NOT INITIAL.
    IF RESB_BT-MATNR CS 'H'.
    ELSE.
      DATA: ZMTART1 TYPE MARA-MTART.
      DATA: ZIDNRK TYPE MARA-MATNR.
      CLEAR : ZMTART1,ZIDNRK.
      SELECT SINGLE MTART INTO ZMTART1 FROM MARA WHERE MATNR EQ RESB_BT-MATNR.
      IF ZMTART1 EQ 'ZVRP'.

*
        DATA: STLNR TYPE STAS-STLNR.
        DATA: STLAL TYPE STAS-STLAL.
        CLEAR : STLNR,STLAL.
        DATA: IT_STAS TYPE TABLE OF STAS,
              IT_STPO TYPE TABLE OF STPO.

        READ TABLE RESB_BT WITH KEY MATNR = RESB_BT-MATNR.
        IF SY-SUBRC EQ 0.
          STLNR = RESB_BT-STLNR.
          STLAL = RESB_BT-STLAL.
        ENDIF.

        IF STLNR EQ SPACE AND ZMTART1 EQ 'ZVRP'.
          CLEAR : ZIDNRK.
          IF ZMTART1 EQ 'ZVRP'.
            SELECT * FROM STAS INTO TABLE IT_STAS WHERE STLNR EQ  STLNR AND STLAL EQ STLAL.
            IF IT_STAS IS NOT INITIAL.
              SELECT * FROM STPO INTO TABLE IT_STPO FOR ALL ENTRIES IN IT_STAS WHERE STLNR EQ IT_STAS-STLNR AND
                STLKN EQ IT_STAS-STLKN AND IDNRK EQ RESB_BT-MATNR..
            ENDIF.
            IF IT_STPO IS INITIAL.
*         BREAK-POINT  .
*         MESSAGE E971(ZHR_MESSAGE) WITH resb_bt-MATNR. "it shall be allowed for other halb code.
              IF SY-TCODE EQ 'COR1'.
                MESSAGE E971(ZHR_MESSAGE) WITH RESB_BT-MATNR.
              ELSEIF SY-TCODE EQ 'COR2'.
                MESSAGE E971(ZHR_MESSAGE) WITH RESB_BT-MATNR.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDIF.

      ENDIF.
    ENDIF.
  ENDIF.
ENDIF.


*DATA: LV_LEN_HEADER TYPE I,
*      LV_LEN_COMP   TYPE I.
*
*
*IF SY-TCODE = 'COR1' OR SY-TCODE = 'COR2'.
*  IF RESB_BT[] IS NOT INITIAL.
*    SELECT MATNR,
*           MTART
*      FROM MARA
*      INTO TABLE @DATA(LI_MTART)
*      FOR ALL ENTRIES IN @RESB_BT
*      WHERE MATNR = @RESB_BT-MATNR AND MTART = 'ZHLB'.
*  ENDIF.
*
*  LOOP AT RESB_BT INTO DATA(LWA_COMPONENT).
*    READ TABLE LI_MTART INTO DATA(LW_MTART) WITH  KEY MATNR = LWA_COMPONENT-MATNR.
*    IF SY-SUBRC = 0.
*
*      SHIFT LWA_COMPONENT-MATNR LEFT DELETING LEADING '0'.
*      SHIFT LWA_COMPONENT-BAUGR LEFT DELETING LEADING '0'.
*      LV_LEN_HEADER = STRLEN( LWA_COMPONENT-BAUGR ).
*      LV_LEN_COMP   = STRLEN( LWA_COMPONENT-MATNR ).
*      IF   LV_LEN_HEADER > LV_LEN_COMP.
**        IF SY-UCOMM = '' OR SY-UCOMM = 'BU'.
*         MESSAGE E975(ZHR_MESSAGE).
**        ENDIF.
*      ENDIF.
*    ENDIF.
*  ENDLOOP.
*ENDIF.















ENDENHANCEMENT.
