"Name: \PR:SAPLCSDI\FO:RC29N_MATNR_CHECK\SE:BEGIN\EI
ENHANCEMENT 0 ZCS02.
*Restrict semi finished bom change for QA- Jyotsna 4.8.25
IF SY-TCODE EQ 'CS01' OR SY-TCODE EQ 'CS02'.
  if sy-uname eq 'QANSK01' OR sy-uname eq 'QANSK02' OR sy-uname eq 'QANSK03'.
   DATA: MTART TYPE MARA-MTART.
   CLEAR: MTART.
   SELECT SINGLE MTART INTO MTART FROM MARA WHERE MATNR EQ RC29N-MATNR.
     IF MTART EQ 'ZHLB'.
       MESSAGE 'SEMI FINISHED BOM CHANGES : NOT ALLOWED BY QA' TYPE 'E'.
     ENDIF.
 ENDIF.
 ENDIF.
ENDENHANCEMENT.
