PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDEPT_UAUTH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDEPT_UAUTH-DEPT .
    FIELD ZDEPT_UAUTH-ZUSER .
    FIELD ZDEPT_UAUTH-CR_DT .
    FIELD ZDEPT_UAUTH-CR_TM .
    FIELD ZDEPT_UAUTH-CH_DT .
    FIELD ZDEPT_UAUTH-CH_TM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDEPT_UAUTH-DEPT .
    FIELD ZDEPT_UAUTH-ZUSER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
