PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDIST_SALE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDIST_SALE-KUNRG .
    FIELD ZDIST_SALE-KUNAG .
    FIELD ZDIST_SALE-BUDAT .
    FIELD ZDIST_SALE-UZEIT .
    FIELD ZDIST_SALE-BUZEI .
    FIELD ZDIST_SALE-MATNR .
    FIELD ZDIST_SALE-CHARG .
    FIELD ZDIST_SALE-FKIMG .
    FIELD ZDIST_SALE-FKDAT .
    FIELD ZDIST_SALE-KBETR .
    FIELD ZDIST_SALE-NETWR .
    FIELD ZDIST_SALE-UNAME .
    FIELD ZDIST_SALE-FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDIST_SALE-KUNRG .
    FIELD ZDIST_SALE-KUNAG .
    FIELD ZDIST_SALE-BUDAT .
    FIELD ZDIST_SALE-UZEIT .
    FIELD ZDIST_SALE-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
