PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZISD_INVOICE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZISD_INVOICE-VBELN .
    FIELD ZISD_INVOICE-GJAHR .
    FIELD ZISD_INVOICE-POSNR .
    FIELD ZISD_INVOICE-INVOICE .
    FIELD ZISD_INVOICE-FKDAT .
    FIELD ZISD_INVOICE-XEGDR .
    FIELD ZISD_INVOICE-WERKS .
    FIELD ZISD_INVOICE-AIGST .
    FIELD ZISD_INVOICE-ACGST .
    FIELD ZISD_INVOICE-ASGST .
    FIELD ZISD_INVOICE-ACESS .
    FIELD ZISD_INVOICE-DIGST .
    FIELD ZISD_INVOICE-DCGST .
    FIELD ZISD_INVOICE-DSGST .
    FIELD ZISD_INVOICE-DCESS .
    FIELD ZISD_INVOICE-FORDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZISD_INVOICE-VBELN .
    FIELD ZISD_INVOICE-GJAHR .
    FIELD ZISD_INVOICE-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
