PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLLM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLLM-CHARG .
    FIELD ZLLM-STYPE .
    FIELD ZLLM-MATNR .
    FIELD ZLLM-FKIMG .
    FIELD ZLLM-LIFNR .
    FIELD ZLLM-EBELN .
    FIELD ZLLM-STATUS .
    FIELD ZLLM-REMARK .
    FIELD ZLLM-UNAME .
    FIELD ZLLM-CPUDT .
    FIELD ZLLM-CPUTM .
    FIELD ZLLM-QASTATUS .
    FIELD ZLLM-QAREMARK .
    FIELD ZLLM-CHGUM .
    FIELD ZLLM-CHGDT .
    FIELD ZLLM-CHGTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLLM-CHARG .
    FIELD ZLLM-STYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
