PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZLLM_DSP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZLLM_DSP-STYPE .
    FIELD ZLLM_DSP-CHARG .
    FIELD ZLLM_DSP-BUZEI .
    FIELD ZLLM_DSP-MATNR .
    FIELD ZLLM_DSP-LIFNR .
    FIELD ZLLM_DSP-FKIMG .
    FIELD ZLLM_DSP-FKDAT .
    FIELD ZLLM_DSP-GJAHR .
    FIELD ZLLM_DSP-XBLNR .
    FIELD ZLLM_DSP-BLDAT .
    FIELD ZLLM_DSP-REMARK .
    FIELD ZLLM_DSP-UNAME .
    FIELD ZLLM_DSP-CPUDT .
    FIELD ZLLM_DSP-CPUTM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZLLM_DSP-STYPE .
    FIELD ZLLM_DSP-CHARG .
    FIELD ZLLM_DSP-BUZEI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
