*&---------------------------------------------------------------------*
*& Report  ZLLM_RM_PM_REGISTER_NEW1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZLLM_RM_PM_REGISTER_NEW3.

TABLES : MKPF,MSEG,MARA,
         MAKT,LFA1,EKPO,
         ADRC,T001W,RSEG,
         BKPF, BSET, ZGSTNUM1,
         EKKO,KNA1, VBRK.
*data: c_ccont   type ref to cl_gui_custom_container,         "Custom container object
*      c_alvgd   type ref to cl_gui_alv_grid,         "ALV grid object
*      it_fcat   type lvc_t_fcat,                  "Field catalogue
*      it_layout type lvc_s_layo.                  "Layout

DATA: IT_MKPF             TYPE TABLE OF MKPF,
      WA_MKPF             TYPE MKPF,
      IT_MSEG             TYPE TABLE OF MSEG,
      WA_MSEG             TYPE MSEG,
      IT_MSEG1            TYPE TABLE OF MSEG,
      WA_MSEG1            TYPE MSEG,
      IT_MSEG2            TYPE TABLE OF MSEG,
      WA_MSEG2            TYPE MSEG,
      IT_WB2_V_VBRK_VBRP2 TYPE TABLE OF WB2_V_VBRK_VBRP2,
      WA_WB2_V_VBRK_VBRP2 TYPE WB2_V_VBRK_VBRP2,
      IT_RSEG             TYPE TABLE OF RSEG,
      WA_RSEG             TYPE RSEG,
      IT_BSET             TYPE TABLE OF BSET,
      WA_BSET             TYPE BSET,
      IT_VBFA             TYPE TABLE OF VBFA,
      WA_VBFA             TYPE VBFA.

TYPES : BEGIN OF ITAB1,
          WERKS TYPE MSEG-WERKS,
          BWART TYPE MSEG-BWART,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          MENGE TYPE MSEG-MENGE,
          MEINS TYPE MSEG-MEINS,
          EBELN TYPE MSEG-EBELN,
          EBELP TYPE MSEG-EBELP,
          LIFNR TYPE MSEG-LIFNR,
          DMBTR TYPE MSEG-DMBTR,
        END OF ITAB1.

TYPES : BEGIN OF ITAB2,
          WERKS   TYPE MSEG-WERKS,
          BWART   TYPE MSEG-BWART,
          MATNR   TYPE MSEG-MATNR,
          CHARG   TYPE MSEG-CHARG,
          MENGE   TYPE MSEG-MENGE,
          MEINS   TYPE MSEG-MEINS,
          EBELN   TYPE MSEG-EBELN,
          EBELP   TYPE MSEG-EBELP,
          LIFNR   TYPE MSEG-LIFNR,
          DMBTR   TYPE MSEG-DMBTR,
          FKART   TYPE WB2_V_VBRK_VBRP2-FKART,
          VBELN   TYPE WB2_V_VBRK_VBRP2-VBELN,
          FKDAT   TYPE WB2_V_VBRK_VBRP2-FKDAT,
          FKIMG_I TYPE WB2_V_VBRK_VBRP2-FKIMG_I,
          NETWR_I TYPE WB2_V_VBRK_VBRP2-NETWR_I,
          MWSBP_I TYPE WB2_V_VBRK_VBRP2-MWSBP_I,
        END OF ITAB2.

TYPES : BEGIN OF GRN1,
          MJAHR TYPE MSEG-MJAHR,
          MBLNR TYPE MSEG-MBLNR,
          WERKS TYPE MSEG-WERKS,
          BWART TYPE MSEG-BWART,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          MENGE TYPE MSEG-MENGE,
          MEINS TYPE MSEG-MEINS,
          LGORT TYPE MSEG-LGORT,
          EBELN TYPE MSEG-EBELN,
          EBELP TYPE MSEG-EBELP,
          LIFNR TYPE MSEG-LIFNR,
          DMBTR TYPE MSEG-DMBTR,
          MAKTX TYPE  MAKT-MAKTX,
          NAME1 TYPE LFA1-NAME1,
          ORT01 TYPE LFA1-ORT01,
        END OF GRN1.

TYPES : BEGIN OF RPM1,
          MJAHR         TYPE MSEG-MJAHR,
          MBLNR         TYPE MSEG-MBLNR,
          WERKS         TYPE MSEG-WERKS,
          BWART         TYPE MSEG-BWART,
          MATNR         TYPE MSEG-MATNR,
          CHARG         TYPE MSEG-CHARG,
          MENGE         TYPE MSEG-MENGE,
          MEINS         TYPE MSEG-MEINS,
          LGORT         TYPE MSEG-LGORT,
          EBELN         TYPE MSEG-EBELN,
          EBELP         TYPE MSEG-EBELP,
          LIFNR         TYPE MSEG-LIFNR,
          DMBTR         TYPE MSEG-DMBTR,
          MAKTX         TYPE  MAKT-MAKTX,
          NAME1         TYPE LFA1-NAME1,
          ORT01         TYPE LFA1-ORT01,
          STCD3         TYPE LFA1-STCD3,
          MWSKZ         TYPE  EKPO-MWSKZ,
          DELADDR1(100) TYPE C,
          DELADDR2(100) TYPE C,
        END OF RPM1.

TYPES : BEGIN OF RPM2,
          MJAHR         TYPE MSEG-MJAHR,
          MBLNR         TYPE MSEG-MBLNR,
          WERKS         TYPE MSEG-WERKS,
          BWART         TYPE MSEG-BWART,
          MATNR         TYPE MSEG-MATNR,
          CHARG         TYPE MSEG-CHARG,
          FGMATNR       TYPE MSEG-MATNR,
          FGCHARG       TYPE MSEG-CHARG,
          MENGE         TYPE MSEG-MENGE,
          MEINS         TYPE MSEG-MEINS,
          LGORT         TYPE MSEG-LGORT,
          EBELN         TYPE MSEG-EBELN,
          EBELP         TYPE MSEG-EBELP,
          LIFNR         TYPE MSEG-LIFNR,
          DMBTR         TYPE MSEG-DMBTR,
          MAKTX         TYPE  MAKT-MAKTX,
          NAME1         TYPE LFA1-NAME1,
          ORT01         TYPE LFA1-ORT01,
          STCD3         TYPE LFA1-STCD3,
          DELADDR1(100) TYPE C,
          DELADDR2(100) TYPE C,
          MWSKZ         TYPE EKPO-MWSKZ,
          BELNR         TYPE RSEG-BELNR,
          GJAHR         TYPE RSEG-GJAHR,
          RPMBLNR       TYPE MSEG-MBLNR,
          RPMJAHR       TYPE MSEG-MJAHR,
          RPLIFNR       TYPE MSEG-LIFNR,
          RPEBELN       TYPE MSEG-EBELN,
          RPEBELP       TYPE MSEG-EBELP,
          RPMENGE       TYPE MSEG-MENGE,
*          RPLINE_ID     TYPE MSEG-LINE_ID,
        END OF RPM2.

TYPES : BEGIN OF RPM3,
          MJAHR         TYPE MSEG-MJAHR,
          MBLNR         TYPE MSEG-MBLNR,
          WERKS         TYPE MSEG-WERKS,
          BWART         TYPE MSEG-BWART,
          MATNR         TYPE MSEG-MATNR,
          CHARG         TYPE MSEG-CHARG,
          FGMATNR       TYPE MSEG-MATNR,
          FGCHARG       TYPE MSEG-CHARG,
          MENGE         TYPE MSEG-MENGE,
          MEINS         TYPE MSEG-MEINS,
          LGORT         TYPE MSEG-LGORT,
          EBELN         TYPE MSEG-EBELN,
          EBELP         TYPE MSEG-EBELP,
          LIFNR         TYPE MSEG-LIFNR,
          DMBTR         TYPE MSEG-DMBTR,
          MAKTX         TYPE  MAKT-MAKTX,
          NAME1         TYPE LFA1-NAME1,
          ORT01         TYPE LFA1-ORT01,
          STCD3         TYPE LFA1-STCD3,
          DELADDR1(100) TYPE C,
          DELADDR2(100) TYPE C,
          MWSKZ         TYPE EKPO-MWSKZ,
          BELNR         TYPE RSEG-BELNR,
          GJAHR         TYPE RSEG-GJAHR,
          RPMBLNR       TYPE MSEG-MBLNR,
          RPMJAHR       TYPE MSEG-MJAHR,
          RPLIFNR       TYPE MSEG-LIFNR,
          RPEBELN       TYPE MSEG-EBELN,
          RPEBELP       TYPE MSEG-EBELP,
          RPBELNR       TYPE RSEG-BELNR,
          RPGJAHR       TYPE RSEG-GJAHR,
          RPXBLNR       TYPE RSEG-XBLNR,
          RPMWSKZ       TYPE RSEG-MWSKZ,
*          WRBTR         TYPE RSEG-WRBTR,
  WRBTR         TYPE p,
          RPFIDOC       TYPE BKPF-BELNR,
          RPFIDOCYR     TYPE BKPF-GJAHR,
          HWSTE         TYPE BSET-HWSTE,
          IGST          TYPE BSET-HWSTE,
          CGST          TYPE BSET-HWSTE,
          SGST          TYPE BSET-HWSTE,
          CESS          TYPE BSET-HWSTE,
          OTHR          TYPE BSET-HWSTE,
          RPMENGE       TYPE MSEG-MENGE,
*          RPLINE_ID     TYPE MSEG-LINE_ID,
          XBLNR         TYPE BKPF-XBLNR,
          BLDAT         TYPE BKPF-BLDAT,
          GRNINV        TYPE BKPF-XBLNR,
          GRNINVDT      TYPE BKPF-BLDAT,
          BUDAT         TYPE BKPF-BUDAT,
          VBELN         TYPE ZGSTNUM1-VBELN,
          FKDAT         TYPE SY-DATUM,
          GRNBUDAT      TYPE MKPF-BUDAT,
          GRBELNR       TYPE BKPF-BELNR,
          MBLNR541      TYPE MSEG-MBLNR,
          MJAHR541      TYPE MSEG-MJAHR,
          WERKS541      TYPE MSEG-WERKS,
          BELNR541      TYPE BKPF-BELNR,
          GJAHR541      TYPE BKPF-GJAHR,
          GRGJAHR       TYPE BKPF-GJAHR,
          CHK1(1)       TYPE C,
        END OF RPM3.

TYPES : BEGIN OF TAX1,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          LFGJA TYPE RSEG-LFGJA,
          LFPOS TYPE RSEG-LFPOS,
          BELNR TYPE RSEG-BELNR,
          GJAHR TYPE RSEG-GJAHR,
*          wrbtr type rseg-wrbtr,
          WRBTR TYPE P DECIMALS 2,
          MENGE TYPE RSEG-MENGE,
          PEINH TYPE EKPO-PEINH,
        END OF TAX1.

TYPES : BEGIN OF TAX2,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          LFGJA TYPE RSEG-LFGJA,
          LFPOS TYPE RSEG-LFPOS,
          BELNR TYPE BKPF-BELNR,
          GJAHR TYPE BKPF-GJAHR,
*          wrbtr type rseg-wrbtr,
          WRBTR TYPE P DECIMALS 2,
          XBLNR TYPE BKPF-XBLNR,
          BLDAT TYPE BKPF-BLDAT,
          BUDAT TYPE BKPF-BUDAT,
          MENGE TYPE RSEG-MENGE,
          PEINH TYPE EKPO-PEINH,
        END OF TAX2.

TYPES : BEGIN OF TAX3,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          LFGJA TYPE RSEG-LFGJA,
          LFPOS TYPE RSEG-LFPOS,
          BELNR TYPE BKPF-BELNR,
          GJAHR TYPE BKPF-GJAHR,
          HWSTE TYPE BSET-HWSTE,
*          wrbtr type rseg-wrbtr,
          WRBTR TYPE P DECIMALS 2,
          CGST  TYPE BSET-HWSTE,
          SGST  TYPE BSET-HWSTE,
          IGST  TYPE BSET-HWSTE,
          CESS  TYPE BSET-HWSTE,
          OTHR  TYPE BSET-HWSTE,
          XBLNR TYPE BKPF-XBLNR,
          BLDAT TYPE BKPF-BLDAT,
          BUDAT TYPE BKPF-BUDAT,
        END OF TAX3.

TYPES : BEGIN OF TRF1,
          MBLNR    TYPE MSEG-MBLNR,
          MJAHR    TYPE RPM1-MJAHR,
          MATNR    TYPE MSEG-MATNR,
          CHARG    TYPE MSEG-CHARG,
          VBELN_IM TYPE MSEG-VBELN_IM,
        END OF TRF1.

TYPES : BEGIN OF TRF2,
          MBLNR    TYPE MSEG-MBLNR,
          MJAHR    TYPE RPM1-MJAHR,
          MATNR    TYPE MSEG-MATNR,
          CHARG    TYPE MSEG-CHARG,
          VBELN_IM TYPE MSEG-VBELN_IM,
          VBELN    TYPE VBFA-VBELN,
          FKDAT    TYPE VBRK-FKDAT,
        END OF TRF2.
TYPES: BEGIN OF DET2,
         MJAHR TYPE RPM1-MJAHR,
         MATNR TYPE MSEG-MATNR,
         CHARG TYPE MSEG-CHARG,
       END OF DET2.

TYPES: BEGIN OF DET3,
         MBLNR TYPE MSEG-MBLNR,
         MJAHR TYPE MSEG-MJAHR,
         MATNR TYPE MSEG-MATNR,
         CHARG TYPE MSEG-CHARG,
         DMBTR TYPE MSEG-DMBTR,
         BWART TYPE MSEG-BWART,
       END OF DET3.

DATA: IT_TAB1 TYPE TABLE OF ITAB1,
      WA_TAB1 TYPE ITAB1,
      IT_TAB2 TYPE TABLE OF ITAB2,
      WA_TAB2 TYPE ITAB2,
      IT_GRN1 TYPE TABLE OF GRN1,
      WA_GRN1 TYPE  GRN1,
      IT_RPM1 TYPE TABLE OF RPM1,
      WA_RPM1 TYPE RPM1,
      IT_RPM2 TYPE TABLE OF RPM2,
      WA_RPM2 TYPE RPM2,
      IT_RPM3 TYPE TABLE OF RPM3,
      WA_RPM3 TYPE RPM3,
      IT_RPM4 TYPE TABLE OF RPM3,
      WA_RPM4 TYPE RPM3,
      IT_RPM5 TYPE TABLE OF RPM3,
      WA_RPM5 TYPE RPM3,
      IT_RPM6 TYPE TABLE OF RPM3,
      WA_RPM6 TYPE RPM3,
      IT_RPM7 TYPE TABLE OF RPM3,
      WA_RPM7 TYPE RPM3,
      IT_TAX1 TYPE TABLE OF TAX1,
      WA_TAX1 TYPE TAX1,
      IT_TAX2 TYPE TABLE OF TAX2,
      WA_TAX2 TYPE TAX2,
      IT_TAX3 TYPE TABLE OF TAX3,
      WA_TAX3 TYPE TAX3,
      IT_TRF1 TYPE TABLE OF TRF1,
      WA_TRF1 TYPE TRF1,
      IT_TRF2 TYPE TABLE OF TRF2,
      WA_TRF2 TYPE TRF2,
      IT_DET2 TYPE TABLE OF DET2,
      WA_DET2 TYPE DET2,
      IT_DET3 TYPE TABLE OF DET3,
      WA_DET3 TYPE DET3.

DATA: IT_MSEG11 TYPE TABLE OF MSEG,
      WA_MSEG11 TYPE MSEG.
TYPES : BEGIN OF DET1,
          MBLNR   TYPE MSEG-MBLNR,
          MJAHR   TYPE RPM1-MJAHR,
          BWART   TYPE MSEG-BWART,
          MATNR   TYPE MSEG-MATNR,
          CHARG   TYPE MSEG-CHARG,
          FGCHARG TYPE MSEG-CHARG,
          BELNR   TYPE BKPF-BELNR,
          GJAHR   TYPE BKPF-GJAHR,
          MAKTX   TYPE MAKT-MAKTX,
          DMBTR   TYPE MSEG-DMBTR,
          WERKS   TYPE MSEG-WERKS,
        END OF DET1.
DATA: IT_DET1 TYPE TABLE OF DET1,
      WA_DET1 TYPE DET1.

TYPES: BEGIN OF TYP_T001W,
         WERKS TYPE WERKS_D,
         NAME1 TYPE NAME1,
       END OF TYP_T001W.

DATA : ITAB_T001W TYPE TABLE OF TYP_T001W,
       WA_T001W   TYPE TYP_T001W.
DATA :
*      mesg(40) type c,
      MSG TYPE STRING.
DATA: AWKEY TYPE BKPF-AWKEY.
DATA: MENGE TYPE MSEG-MENGE.

DATA: QTY1 TYPE P.
DATA: DELADDR1(100) TYPE C,
      DELADDR2(100) TYPE C.
DATA: VAL  TYPE P DECIMALS 2,
      VAL1 TYPE P DECIMALS 2.
DATA: DOC1 TYPE VBRK-VBELN.
DATA : T_MAT TYPE MSEG-MBLNR.
DATA: DOC  TYPE BKPF-AWKEY,
      DOC2 TYPE BKPF-AWKEY.
DATA:
  OK_CODE       TYPE UI_FUNC.

DATA: CHARG TYPE MCHA-CHARG,
      MATNR TYPE MCHA-MATNR,
      MJAHR TYPE MSEG-MJAHR.
DATA: DOC3 TYPE BKPF-AWKEY.

*********************************
TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV,
      L_GLAY      TYPE LVC_S_GLAY.

DATA: G_REPID1     LIKE SY-REPID,
      FIELDCAT1    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT1 LIKE LINE OF FIELDCAT,
      SORT1        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT1     LIKE LINE OF SORT,
      LAYOUT1      TYPE SLIS_LAYOUT_ALV,
      L_GLAY1      TYPE LVC_S_GLAY.


*******************************************

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : MATERIAL FOR MSEG-MATNR,
                 DATE1 FOR MKPF-BUDAT,
                 PLANT FOR MSEG-WERKS.
*PARAMETERS : VEN LIKE MSEG-LIFNR.
*                 MTART FOR MARA-MTART.
PARAMETERS : C1 AS CHECKBOX.
SELECTION-SCREEN END OF BLOCK MERKMALE1 .

INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION .

  SELECT * FROM MKPF INTO TABLE IT_MKPF WHERE VGART EQ 'WE' AND BUDAT IN DATE1.
  IF SY-SUBRC EQ 0.
    SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN IT_MKPF WHERE MBLNR EQ IT_MKPF-MBLNR AND MJAHR EQ IT_MKPF-MJAHR AND MATNR IN MATERIAL
    AND WERKS IN PLANT .
*      AND SOBKZ EQ 'O'.
    IF SY-SUBRC NE 0.
      MESSAGE 'NO DATA FOUND' TYPE 'E'.
    ENDIF.
  ENDIF.

  DELETE IT_MSEG WHERE SOBKZ EQ SPACE AND LIFNR NE SPACE.

  PERFORM RMPM.
*&---------------------------------------------------------------------*
*&      Form  RMPM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM RMPM .
  LOOP AT IT_MSEG INTO WA_MSEG.
    SELECT SINGLE * FROM EKKO WHERE EBELN EQ WA_MSEG-EBELN AND BSART EQ 'ZSBC'.
    IF SY-SUBRC EQ 4.
      SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_MSEG-MATNR AND MTART IN ('ZROH','ZVRP').
      IF SY-SUBRC EQ 0.
*        write : / 'A',wa_mseg-mblnr,wa_mseg-matnr,wa_mseg-charg,wa_mseg-menge,wa_mseg-meins.
        WA_RPM1-MJAHR = WA_MSEG-MJAHR.
        WA_RPM1-MBLNR = WA_MSEG-MBLNR.
        WA_RPM1-WERKS = WA_MSEG-WERKS.
        WA_RPM1-BWART = WA_MSEG-BWART.
        WA_RPM1-MATNR = WA_MSEG-MATNR.
        SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MSEG-MATNR AND SPRAS EQ 'EN'.
        IF SY-SUBRC EQ 0.
          WA_RPM1-MAKTX = MAKT-MAKTX.
        ENDIF.
        WA_RPM1-CHARG = WA_MSEG-CHARG.
        WA_RPM1-MENGE = WA_MSEG-MENGE.
        WA_RPM1-MEINS = WA_MSEG-MEINS.
        WA_RPM1-LGORT = WA_MSEG-LGORT.
        WA_RPM1-EBELN = WA_MSEG-EBELN.
        WA_RPM1-EBELP = WA_MSEG-EBELP.
        SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_MSEG-EBELN AND EBELP EQ WA_MSEG-EBELP.
        IF SY-SUBRC EQ 0.
          WA_RPM1-MWSKZ = EKPO-MWSKZ.
********************************************
          SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ EKPO-EMLIF.
          IF SY-SUBRC EQ 0.
            CLEAR : DELADDR1.
            CONCATENATE LFA1-NAME1 LFA1-ORT01 INTO DELADDR1 SEPARATED BY SPACE.
            WA_RPM1-DELADDR1 = DELADDR1.
            IF LFA1-NAME2 EQ SPACE.
              SELECT SINGLE * FROM ADRC WHERE ADDRNUMBER EQ LFA1-ADRNR.
              IF SY-SUBRC EQ 0.
                CLEAR : DELADDR2.
                CONCATENATE ADRC-STR_SUPPL1 ADRC-STR_SUPPL2 INTO DELADDR2 SEPARATED BY SPACE.
                WA_RPM1-DELADDR2 = DELADDR2.
              ELSE.
                CLEAR : DELADDR2.
                CONCATENATE ADRC-NAME2 ADRC-NAME3 INTO DELADDR2 SEPARATED BY SPACE.
                WA_RPM1-DELADDR2 = DELADDR2.
              ENDIF.
            ENDIF.
          ENDIF.
          IF WA_RPM1-DELADDR1 EQ SPACE.
            SELECT SINGLE * FROM T001W WHERE WERKS EQ WA_RPM1-WERKS.
            IF SY-SUBRC EQ 0.
              CLEAR : DELADDR1.
              CONCATENATE T001W-NAME1 T001W-ORT01 INTO DELADDR1 SEPARATED BY SPACE.
              WA_RPM1-DELADDR1 = DELADDR1.
              IF T001W-NAME2 EQ SPACE.
                SELECT SINGLE * FROM ADRC WHERE ADDRNUMBER EQ T001W-ADRNR.
                IF SY-SUBRC EQ 0.
                  CLEAR : DELADDR2.
                  CONCATENATE ADRC-STR_SUPPL1 ADRC-STR_SUPPL2 INTO DELADDR2 SEPARATED BY SPACE.
                  WA_RPM1-DELADDR2 = DELADDR2.
                ELSE.
                  CLEAR : DELADDR2.
                  CONCATENATE ADRC-NAME2 ADRC-NAME3 INTO DELADDR2 SEPARATED BY SPACE.
                  WA_RPM1-DELADDR2 = DELADDR2.
                ENDIF.
              ENDIF.
            ENDIF.
          ENDIF.
*************************************************
        ENDIF.
        WA_RPM1-LIFNR = WA_MSEG-LIFNR.
        WA_RPM1-DMBTR = WA_MSEG-DMBTR.
        SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_MSEG-LIFNR.
        IF SY-SUBRC EQ 0.
          WA_RPM1-NAME1 = LFA1-NAME1.
          WA_RPM1-ORT01 = LFA1-ORT01.
          WA_RPM1-STCD3 = LFA1-STCD3.
        ENDIF.
        IF WA_RPM1-LIFNR EQ SPACE.
          SELECT SINGLE * FROM EKKO WHERE EBELN EQ WA_MSEG-EBELN.
          IF SY-SUBRC EQ 0.
            SELECT SINGLE * FROM T001W WHERE WERKS EQ EKKO-RESWK.
            IF SY-SUBRC EQ 0.
              WA_RPM1-NAME1 = T001W-NAME1.
              WA_RPM1-ORT01 = T001W-ORT01.
              SELECT SINGLE * FROM KNA1 WHERE KUNNR EQ T001W-KUNNR.
              IF SY-SUBRC EQ 0.
                WA_RPM1-STCD3 = KNA1-STCD3.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDIF.
        COLLECT WA_RPM1 INTO IT_RPM1.
        CLEAR WA_RPM1.
      ENDIF.
    ENDIF.
  ENDLOOP.

  IF IT_RPM1 IS NOT INITIAL.
    LOOP AT IT_RPM1 INTO WA_RPM1 WHERE LIFNR EQ SPACE.
      WA_TRF1-MBLNR = WA_RPM1-MBLNR.
      WA_TRF1-MJAHR = WA_RPM1-MJAHR.
      WA_TRF1-MATNR = WA_RPM1-MATNR.
      WA_TRF1-CHARG = WA_RPM1-CHARG.
      READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MBLNR = WA_RPM1-MBLNR MJAHR = WA_RPM1-MJAHR.
      IF SY-SUBRC EQ 0.
        WA_TRF1-VBELN_IM = WA_MSEG-VBELN_IM.
      ENDIF.
      IF WA_TRF1-VBELN_IM IS INITIAL.
        READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MBLNR = WA_RPM1-MBLNR MJAHR = WA_RPM1-MJAHR.
        IF SY-SUBRC EQ 0.
          WA_TRF1-VBELN_IM = WA_MSEG-XBLNR_MKPF.
        ENDIF.
      ENDIF.
      COLLECT WA_TRF1 INTO IT_TRF1.
      CLEAR WA_TRF1.
    ENDLOOP.
  ENDIF.
  IF IT_TRF1 IS NOT INITIAL.
    SELECT * FROM VBFA INTO TABLE IT_VBFA FOR ALL ENTRIES IN IT_TRF1 WHERE VBELV EQ IT_TRF1-VBELN_IM AND VBTYP_N EQ 'M'.
  ENDIF.
  SORT IT_VBFA DESCENDING BY VBELN.
  LOOP AT IT_TRF1 INTO WA_TRF1.
    WA_TRF2-MBLNR = WA_TRF1-MBLNR.
    WA_TRF2-MJAHR = WA_TRF1-MJAHR.
    WA_TRF2-MATNR = WA_TRF1-MATNR.
    WA_TRF2-CHARG = WA_TRF1-CHARG.
    WA_TRF2-VBELN_IM = WA_TRF1-VBELN_IM.
    READ TABLE IT_VBFA INTO WA_VBFA WITH KEY VBELV = WA_TRF1-VBELN_IM.
    IF SY-SUBRC EQ 0.
      WA_TRF2-VBELN = WA_VBFA-VBELN.
      SELECT SINGLE * FROM VBRK WHERE VBELN EQ WA_VBFA-VBELN.
      IF SY-SUBRC EQ 0.
        WA_TRF2-FKDAT = VBRK-FKDAT.
      ENDIF.
    ENDIF.
    IF WA_TRF2-VBELN IS INITIAL.
      SELECT SINGLE * FROM VBRK WHERE VBELN EQ WA_TRF1-VBELN_IM.
      IF SY-SUBRC EQ 0.
        WA_TRF2-VBELN = VBRK-VBELN.
        WA_TRF2-FKDAT = VBRK-FKDAT.
      ENDIF.
    ENDIF.
    IF WA_TRF2-VBELN IS INITIAL.
      CLEAR : DOC1.
      CONCATENATE '0' WA_TRF1-VBELN_IM INTO DOC1.
      SELECT SINGLE * FROM VBRK WHERE VBELN EQ DOC1.
      IF SY-SUBRC EQ 0.
        WA_TRF2-VBELN = VBRK-VBELN.
        WA_TRF2-FKDAT = VBRK-FKDAT.
      ENDIF.
    ENDIF.
    IF WA_TRF2-VBELN IS INITIAL.
      CLEAR : DOC1.
      CONCATENATE '00' WA_TRF1-VBELN_IM INTO DOC1.
      SELECT SINGLE * FROM VBRK WHERE VBELN EQ DOC1.
      IF SY-SUBRC EQ 0.
        WA_TRF2-VBELN = VBRK-VBELN.
        WA_TRF2-FKDAT = VBRK-FKDAT.
      ENDIF.
    ENDIF.

    COLLECT WA_TRF2 INTO IT_TRF2.
    CLEAR WA_TRF2.
  ENDLOOP.
  SORT IT_TRF2 DESCENDING BY VBELN FKDAT.

  PERFORM TAX1.

  LOOP AT IT_RPM1 INTO WA_RPM1.
    WA_RPM3-MJAHR = WA_RPM1-MJAHR.
    WA_RPM3-MBLNR = WA_RPM1-MBLNR.
    WA_RPM3-WERKS = WA_RPM1-WERKS.
    WA_RPM3-BWART = WA_RPM1-BWART.
    WA_RPM3-MATNR = WA_RPM1-MATNR.
    WA_RPM3-MAKTX = WA_RPM1-MAKTX.
    WA_RPM3-CHARG = WA_RPM1-CHARG.
    WA_RPM3-MENGE = WA_RPM1-MENGE.
    WA_RPM3-MEINS = WA_RPM1-MEINS.
    WA_RPM3-LGORT = WA_RPM1-LGORT.
    WA_RPM3-EBELN = WA_RPM1-EBELN.
    WA_RPM3-EBELP = WA_RPM1-EBELP.
    WA_RPM3-LIFNR = WA_RPM1-LIFNR.
    WA_RPM3-NAME1 = WA_RPM1-NAME1.
    WA_RPM3-ORT01 = WA_RPM1-ORT01.
    WA_RPM3-DMBTR = WA_RPM1-DMBTR.
    WA_RPM3-STCD3 = WA_RPM1-STCD3.
    WA_RPM3-MWSKZ = WA_RPM1-MWSKZ.
    WA_RPM3-DELADDR1 = WA_RPM1-DELADDR1.
    WA_RPM3-DELADDR2 = WA_RPM1-DELADDR2.
*    WA_RPM3-BELNR = WA_RPM1-BELNR.
*    WA_RPM3-GJAHR = WA_RPM1-GJAHR.
    SELECT SINGLE * FROM ZGSTNUM1 WHERE MBLNR EQ WA_RPM1-MBLNR.
    IF SY-SUBRC EQ 0.
      WA_RPM3-VBELN = ZGSTNUM1-VBELN.
      WA_RPM3-FKDAT = ZGSTNUM1-FKDAT.
    ENDIF.
    READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY MBLNR = WA_RPM1-MBLNR MJAHR = WA_RPM1-MJAHR MATNR = WA_RPM1-MATNR CHARG = WA_RPM1-CHARG.
    IF SY-SUBRC EQ 0.
      WA_RPM3-BELNR = WA_TAX3-BELNR.
      WA_RPM3-GJAHR =  WA_TAX3-GJAHR.
      WA_RPM3-XBLNR =  WA_TAX3-XBLNR.
      WA_RPM3-BLDAT =  WA_TAX3-BLDAT.
      WA_RPM3-BUDAT =  WA_TAX3-BUDAT.
*        WA_RPM3-RPXBLNR =  WA_RSEG-XBLNR.
*        WA_RPM3-RPMWSKZ =  WA_RSEG-MWSKZ.
      WA_RPM3-WRBTR =  WA_TAX3-WRBTR.
      WA_RPM3-HWSTE =  WA_TAX3-HWSTE.

      WA_RPM3-IGST =  WA_TAX3-IGST.
      WA_RPM3-CGST =  WA_TAX3-CGST.
      WA_RPM3-SGST =  WA_TAX3-SGST.
      WA_RPM3-CESS =  WA_TAX3-CESS.
      WA_RPM3-OTHR =  WA_TAX3-OTHR.
    ENDIF.
*  ENDIF.
*    ENDIF.
    COLLECT WA_RPM3 INTO IT_RPM3.
    CLEAR WA_RPM3.
  ENDLOOP.


  PERFORM ORITAX.

  LOOP AT IT_RPM3 INTO WA_RPM3.
    WA_RPM5-MJAHR = WA_RPM3-MJAHR.
    WA_RPM5-MBLNR = WA_RPM3-MBLNR.
    WA_RPM5-WERKS = WA_RPM3-WERKS.
    WA_RPM5-BWART = WA_RPM3-BWART.
    WA_RPM5-MATNR = WA_RPM3-MATNR.
    WA_RPM5-MAKTX = WA_RPM3-MAKTX.
    WA_RPM5-CHARG = WA_RPM3-CHARG.
    WA_RPM5-MENGE = WA_RPM3-MENGE.
    WA_RPM5-MEINS = WA_RPM3-MEINS.
    WA_RPM5-LGORT = WA_RPM3-LGORT.
    WA_RPM5-EBELN = WA_RPM3-EBELN.
    WA_RPM5-EBELP = WA_RPM3-EBELP.
    WA_RPM5-LIFNR = WA_RPM3-LIFNR.
    WA_RPM5-NAME1 = WA_RPM3-NAME1.
    WA_RPM5-ORT01 = WA_RPM3-ORT01.
    WA_RPM5-DMBTR = WA_RPM3-DMBTR.
    WA_RPM5-STCD3 = WA_RPM3-STCD3.
    WA_RPM5-MWSKZ = WA_RPM3-MWSKZ.
    WA_RPM5-DELADDR1 = WA_RPM3-DELADDR1.
    WA_RPM5-DELADDR2 = WA_RPM3-DELADDR2.
    WA_RPM5-VBELN = WA_RPM3-VBELN.
    WA_RPM5-FKDAT = WA_RPM3-FKDAT.
    IF WA_RPM3-BELNR GT 0.
      WA_RPM5-BELNR = WA_RPM3-BELNR.
      WA_RPM5-GJAHR =  WA_RPM3-GJAHR.
      WA_RPM5-XBLNR =  WA_RPM3-XBLNR.
      WA_RPM5-BLDAT =  WA_RPM3-BLDAT.
      WA_RPM5-BUDAT =  WA_RPM3-BUDAT.
      WA_RPM5-WRBTR =  WA_RPM3-WRBTR.
      WA_RPM5-HWSTE =  WA_RPM3-HWSTE.
      WA_RPM5-IGST =  WA_RPM3-IGST.
      WA_RPM5-CGST =  WA_RPM3-CGST.
      WA_RPM5-SGST =  WA_RPM3-SGST.
      WA_RPM5-CESS =  WA_RPM3-CESS.
      WA_RPM5-OTHR =  WA_RPM3-OTHR.
    ELSE.
      READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY MATNR = WA_RPM3-MATNR CHARG = WA_RPM3-CHARG.
      IF SY-SUBRC EQ 0.
        WA_RPM5-BELNR = WA_TAX3-BELNR.
        WA_RPM5-GJAHR =  WA_TAX3-GJAHR.
        WA_RPM5-XBLNR =  WA_TAX3-XBLNR.
        WA_RPM5-BLDAT =  WA_TAX3-BLDAT.
        WA_RPM5-BUDAT =  WA_TAX3-BUDAT.
        CLEAR : MENGE.
        SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_RPM3-EBELN AND EBELP EQ WA_RPM3-EBELP.
        IF SY-SUBRC EQ 0.
          MENGE = WA_RPM3-MENGE / EKPO-PEINH.
        ENDIF.
        IF MENGE LE 0.
          BREAK-POINT.
        ENDIF.
        WA_RPM5-WRBTR =  WA_TAX3-WRBTR * MENGE.
        WA_RPM5-HWSTE =  WA_TAX3-HWSTE * MENGE.
        WA_RPM5-IGST =  WA_TAX3-IGST * MENGE.
        WA_RPM5-CGST =  WA_TAX3-CGST * MENGE.
        WA_RPM5-SGST =  WA_TAX3-SGST * MENGE.
        WA_RPM5-CESS =  WA_TAX3-CESS * MENGE.
        WA_RPM5-OTHR =  WA_TAX3-OTHR * MENGE.
      ENDIF.
      READ TABLE IT_TRF2 INTO WA_TRF2 WITH KEY MBLNR = WA_RPM3-MBLNR MJAHR = WA_RPM3-MJAHR.
      IF SY-SUBRC EQ 0.
        WA_RPM5-XBLNR =  WA_TRF2-VBELN.
        WA_RPM5-BLDAT =  WA_TRF2-FKDAT.
      ENDIF.

    ENDIF.
*  ENDIF.
*    ENDIF.
    COLLECT WA_RPM5 INTO IT_RPM5.
    CLEAR WA_RPM5.
  ENDLOOP.


  PERFORM ORITAX1.


  LOOP AT IT_RPM5 INTO WA_RPM5.
    WA_RPM7-MJAHR = WA_RPM5-MJAHR.
    WA_RPM7-MBLNR = WA_RPM5-MBLNR.
    CLEAR : DOC.
    CONCATENATE WA_RPM5-MBLNR WA_RPM5-MJAHR INTO DOC.
    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_RPM5-MBLNR AND MJAHR EQ WA_RPM5-MJAHR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ MSEG-GJAHR AND AWKEY EQ DOC.
      IF SY-SUBRC EQ 0.
        WA_RPM7-GRBELNR = BKPF-BELNR.
        WA_RPM7-GRGJAHR = BKPF-GJAHR.
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM MSEG WHERE MJAHR GE WA_RPM5-MJAHR AND BWART EQ '541' AND MATNR EQ WA_RPM5-MATNR AND CHARG EQ WA_RPM5-CHARG.
    IF SY-SUBRC EQ 0.
      WA_RPM7-MBLNR541 = MSEG-MBLNR.
      WA_RPM7-MJAHR541 = MSEG-MJAHR.
**********************************************************************************************************
      CLEAR :  DOC2.
      CONCATENATE WA_RPM7-MBLNR541 WA_RPM7-MJAHR541 INTO DOC2.
      SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ MSEG-GJAHR AND AWKEY EQ DOC2.
      IF SY-SUBRC EQ 0.
        WA_RPM7-BELNR541 = BKPF-BELNR.
        WA_RPM7-GJAHR541 = BKPF-GJAHR.
      ENDIF.
**********************************************************************************************************
      SELECT SINGLE * FROM MSEG WHERE MBLNR EQ  WA_RPM7-MBLNR541 AND MJAHR GE WA_RPM5-MJAHR AND BWART EQ '541' AND XAUTO EQ 'X'.
      IF SY-SUBRC EQ 0.
        WA_RPM7-WERKS541 = MSEG-WERKS.
      ENDIF.
    ENDIF.

    READ TABLE IT_MKPF INTO WA_MKPF WITH KEY MBLNR = WA_RPM5-MBLNR MJAHR = WA_RPM5-MJAHR.
    IF SY-SUBRC EQ 0.
      WA_RPM7-GRNBUDAT = WA_MKPF-CPUDT.
      WA_RPM7-GRNINV = WA_MKPF-XBLNR.
      WA_RPM7-GRNINVDT = WA_MKPF-BLDAT.
    ENDIF.
    WA_RPM7-WERKS = WA_RPM5-WERKS.
    WA_RPM7-BWART = WA_RPM5-BWART.
    WA_RPM7-MATNR = WA_RPM5-MATNR.
    WA_RPM7-MAKTX = WA_RPM5-MAKTX.
    WA_RPM7-CHARG = WA_RPM5-CHARG.
    WA_RPM7-MENGE = WA_RPM5-MENGE.
    WA_RPM7-MEINS = WA_RPM5-MEINS.
    WA_RPM7-LGORT = WA_RPM5-LGORT.
    WA_RPM7-EBELN = WA_RPM5-EBELN.
    WA_RPM7-EBELP = WA_RPM5-EBELP.
    WA_RPM7-LIFNR = WA_RPM5-LIFNR.
    WA_RPM7-NAME1 = WA_RPM5-NAME1.
    WA_RPM7-ORT01 = WA_RPM5-ORT01.
    WA_RPM7-DMBTR = WA_RPM5-DMBTR.
    WA_RPM7-STCD3 = WA_RPM5-STCD3.
    WA_RPM7-MWSKZ = WA_RPM5-MWSKZ.
    WA_RPM7-DELADDR1 = WA_RPM5-DELADDR1.
    WA_RPM7-DELADDR2 = WA_RPM5-DELADDR2.
    WA_RPM7-VBELN = WA_RPM5-VBELN.
    WA_RPM7-FKDAT = WA_RPM5-FKDAT.

    IF WA_RPM5-BELNR GT 0.
      WA_RPM7-BELNR = WA_RPM5-BELNR.
      WA_RPM7-GJAHR =  WA_RPM5-GJAHR.
      WA_RPM7-XBLNR =  WA_RPM5-XBLNR.
      WA_RPM7-BLDAT =  WA_RPM5-BLDAT.
      WA_RPM7-BUDAT =  WA_RPM5-BUDAT.
      WA_RPM7-WRBTR =  WA_RPM5-WRBTR.
      WA_RPM7-HWSTE =  WA_RPM5-HWSTE.
      WA_RPM7-IGST =  WA_RPM5-IGST.
      WA_RPM7-CGST =  WA_RPM5-CGST.
      WA_RPM7-SGST =  WA_RPM5-SGST.
      WA_RPM7-CESS =  WA_RPM5-CESS.
      WA_RPM7-OTHR =  WA_RPM5-OTHR.
    ELSE.
      READ TABLE IT_TAX3 INTO WA_TAX3 WITH KEY CHARG = WA_RPM5-CHARG.
      IF SY-SUBRC EQ 0.
        WA_RPM7-BELNR = WA_TAX3-BELNR.
        WA_RPM7-GJAHR =  WA_TAX3-GJAHR.
        WA_RPM7-XBLNR =  WA_TAX3-XBLNR.
        WA_RPM7-BLDAT =  WA_TAX3-BLDAT.
        WA_RPM7-BUDAT =  WA_TAX3-BUDAT.

        CLEAR : MENGE.
        SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_RPM5-EBELN AND EBELP EQ WA_RPM5-EBELP.
        IF SY-SUBRC EQ 0.
          MENGE = WA_RPM5-MENGE / EKPO-PEINH.
        ENDIF.

        WA_RPM7-WRBTR =  WA_TAX3-WRBTR * MENGE.
        WA_RPM7-HWSTE =  WA_TAX3-HWSTE * MENGE.
        WA_RPM7-IGST =  WA_TAX3-IGST * MENGE.
        WA_RPM7-CGST =  WA_TAX3-CGST * MENGE.
        WA_RPM7-SGST =  WA_TAX3-SGST * MENGE.
        WA_RPM7-CESS =  WA_TAX3-CESS * MENGE.
        WA_RPM7-OTHR =  WA_TAX3-OTHR * MENGE.
      ENDIF.
      READ TABLE IT_TRF2 INTO WA_TRF2 WITH KEY MBLNR = WA_RPM5-MBLNR MJAHR = WA_RPM5-MJAHR.
      IF SY-SUBRC EQ 0.
        WA_RPM7-XBLNR =  WA_TRF2-VBELN.
        WA_RPM7-BLDAT =  WA_TRF2-FKDAT.
      ENDIF.
    ENDIF.
*  ENDIF.
*    ENDIF.
    IF C1 EQ 'X'.
      WA_RPM7-CHK1 = 'X'.
    ENDIF.
    COLLECT WA_RPM7 INTO IT_RPM7.
    CLEAR WA_RPM7.
  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'MBLNR'.
  WA_FIELDCAT-SELTEXT_L = 'GRN NO'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

***************************************************

  WA_FIELDCAT-FIELDNAME = 'MJAHR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
*  WA_FIELDCAT-outputlen = 8.
  WA_FIELDCAT-SELTEXT_L = 'GRN YEAR'.
*  WA_FIELDCAT-icon = 'X'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-ROW_POS   = '1'.
*  WA_FIELDCAT-COL_POS   = '2'.
  WA_FIELDCAT-FIELDNAME = 'MBLNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRN NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRNBUDAT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRN POSTING DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-ROW_POS   = '1'.
*  WA_FIELDCAT-COL_POS   = '2'.
  WA_FIELDCAT-FIELDNAME = 'WERKS'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BWART'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'MOVEMENT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELN'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'PO'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELP'.
  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'PO ITEM'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MWSKZ'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'PO TAX CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LIFNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ORT01'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR PLACE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'STCD3'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR GSTN'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DELADDR1'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'DELIVERY ADDRESS1'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DELADDR2'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'DELIVERY ADDRESS2'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BELNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'FI DOC'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GJAHR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'FI DOC YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
*  WA_FIELDCAT-TABNAME   = 'IT_PRM3'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'MENGE'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRN QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MEINS'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'UOM'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DMBTR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'FG GRN VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LGORT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'STORAGE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDAT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM FI DOC POSTING DT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

*  WA_FIELDCAT-FIELDNAME = 'RPMWSKZ'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
*  WA_FIELDCAT-SELTEXT_L = 'RM/PM TAX CODE'.
*  APPEND WA_FIELDCAT TO FIELDCAT.
*  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRNINV'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM GRN BILL NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRNINVDT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM GRN BILL DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'XBLNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM MIRO BILL NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BLDAT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM MIRO BILL DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WRBTR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM FI BASE AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'HWSTE'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM TAX AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'IGST'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM IGST AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CGST'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM CGST AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SGST'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM SGST/UGST AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CESS'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM CESS AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OTHR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RM/PM OTHR AMT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VBELN'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'DELIVERY CHALLAN'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FKDAT'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'DELIVERY CHALLAN DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GRBELNR'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRN FI DOC'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MBLNR541'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRN541'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MJAHR541'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'GRNYR541'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS541'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = 'RECEIPT PLANT541'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BELNR541'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = '541 FI DOC'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GJAHR541'.
*  WA_FIELDCAT-TABNAME   = 'IT_RPM3'.
  WA_FIELDCAT-SELTEXT_L = '541 FI YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

***********************************************************************************
*
*  wa_fieldcat-fieldname = 'BEZEI'.
*  wa_fieldcat-seltext_l = 'PACK SIZE'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'STAT'.
*  wa_fieldcat-seltext_l = 'STATUS'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'SAMPQTY'.
*  wa_fieldcat-seltext_l = 'ALLOCATED QTY'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'NSAMPQTY'.
*  wa_fieldcat-seltext_l = 'NEW QTY'.
*  wa_fieldcat-edit = 'X'. "
*  append wa_fieldcat to fieldcat.

  L_GLAY-EDT_CLL_CB = 'X'.

*  ls_layout-colwidth_optimize = 'X'.


  WA_FIELDCAT-FIELDNAME = 'CHK1'.
  WA_FIELDCAT-SELTEXT_L = 'SELECT'.
  WA_FIELDCAT-CHECKBOX = 'X'.
  WA_FIELDCAT-EDIT = 'X'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'SELECT BATCH TO VIEW FG GRN DETAILS'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = 'STATUS'
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         = L_GLAY
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_RPM7
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  CLEAR : FIELDCAT,LAYOUT.
*  call screen 9001.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  ORITAX
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ORITAX .
  LOOP AT IT_RPM3 INTO WA_RPM3 WHERE BELNR EQ SPACE.
    WA_RPM4-MJAHR = WA_RPM3-MJAHR.
    WA_RPM4-MBLNR = WA_RPM3-MBLNR.
    WA_RPM4-WERKS = WA_RPM3-WERKS.
    WA_RPM4-BWART = WA_RPM3-BWART.
    WA_RPM4-MATNR = WA_RPM3-MATNR.
    WA_RPM4-MAKTX = WA_RPM3-MAKTX.
    WA_RPM4-CHARG = WA_RPM3-CHARG.
    WA_RPM4-MENGE = WA_RPM3-MENGE.
    WA_RPM4-MEINS = WA_RPM3-MEINS.
    WA_RPM4-LGORT = WA_RPM3-LGORT.
    WA_RPM4-EBELN = WA_RPM3-EBELN.
    WA_RPM4-EBELP = WA_RPM3-EBELP.
    WA_RPM4-LIFNR = WA_RPM3-LIFNR.
    WA_RPM4-NAME1 = WA_RPM3-NAME1.
    WA_RPM4-ORT01 = WA_RPM3-NAME1.
    WA_RPM4-DMBTR = WA_RPM3-DMBTR.
    WA_RPM4-STCD3 = WA_RPM3-STCD3.
    WA_RPM4-MWSKZ = WA_RPM3-MWSKZ.
    WA_RPM4-DELADDR1 = WA_RPM3-DELADDR1.
    WA_RPM4-DELADDR2 = WA_RPM3-DELADDR2.
    WA_RPM4-VBELN = WA_RPM3-VBELN.
    WA_RPM4-FKDAT = WA_RPM3-FKDAT.
    WA_RPM4-BELNR = WA_RPM3-BELNR.
    WA_RPM4-GJAHR =  WA_RPM3-GJAHR.
    WA_RPM4-XBLNR =  WA_RPM3-XBLNR.
    WA_RPM4-BLDAT =  WA_RPM3-BLDAT.
    WA_RPM4-BUDAT =  WA_RPM3-BUDAT.
    WA_RPM4-WRBTR =  WA_RPM3-WRBTR.
    WA_RPM4-HWSTE =  WA_RPM3-HWSTE.
    WA_RPM4-IGST =  WA_RPM3-IGST.
    WA_RPM4-CGST =  WA_RPM3-CGST.
    WA_RPM4-SGST =  WA_RPM3-SGST.
    WA_RPM4-CESS = WA_RPM3-CESS.
    WA_RPM4-OTHR =  WA_RPM3-OTHR.
    COLLECT WA_RPM4 INTO IT_RPM4.
    CLEAR WA_RPM4.
  ENDLOOP.

  CLEAR: IT_RSEG,IT_MSEG2.
  IF IT_RPM4 IS NOT INITIAL.
    SELECT * FROM MSEG INTO TABLE IT_MSEG2 FOR ALL ENTRIES IN IT_RPM4 WHERE BWART EQ '101' AND MATNR EQ IT_RPM4-MATNR AND CHARG EQ IT_RPM4-CHARG AND LIFNR GT 0.
    IF SY-SUBRC EQ 0.
      SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_MSEG2  WHERE EBELN EQ IT_MSEG2-EBELN AND
      EBELP EQ IT_MSEG2-EBELP AND LFBNR EQ IT_MSEG2-MBLNR AND LFGJA EQ IT_MSEG2-MJAHR AND MATNR EQ IT_MSEG2-MATNR.
    ENDIF.
  ENDIF.

*    SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_RPM2  WHERE EBELN EQ IT_RPM2-RPEBELN AND
*      EBELP EQ IT_RPM2-RPEBELP AND LFBNR EQ IT_RPM2-RPMBLNR AND LFGJA EQ IT_RPM2-RPMJAHR AND MATNR EQ IT_RPM2-MATNR.
  CLEAR : IT_TAX1,WA_TAX1.
  SORT IT_RSEG DESCENDING BY BELNR.
  IF IT_MSEG2 IS NOT INITIAL.
    LOOP AT IT_MSEG2 INTO WA_MSEG2.
      LOOP AT IT_RSEG INTO WA_RSEG WHERE EBELN EQ WA_MSEG2-EBELN AND  EBELP EQ WA_MSEG2-EBELP AND LFBNR EQ WA_MSEG2-MBLNR AND LFGJA EQ WA_MSEG2-MJAHR
         AND MATNR EQ WA_MSEG2-MATNR AND LFPOS EQ WA_MSEG2-LINE_ID.
        WA_TAX1-MBLNR = WA_MSEG2-MBLNR.
        WA_TAX1-MJAHR = WA_MSEG2-MJAHR.
        WA_TAX1-MATNR = WA_MSEG2-MATNR.
        WA_TAX1-CHARG = WA_MSEG2-CHARG.
        WA_TAX1-LFGJA = WA_RSEG-LFGJA.
        WA_TAX1-LFPOS = WA_RSEG-LFPOS.
        WA_TAX1-BELNR = WA_RSEG-BELNR.
        WA_TAX1-GJAHR = WA_RSEG-GJAHR.
        WA_TAX1-WRBTR = WA_RSEG-WRBTR.
        WA_TAX1-MENGE = WA_RSEG-MENGE.
        SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_MSEG2-EBELN AND  EBELP EQ WA_MSEG2-EBELP.
        IF SY-SUBRC EQ 0.
          WA_TAX1-PEINH = EKPO-PEINH.
        ENDIF.
        COLLECT WA_TAX1 INTO IT_TAX1.
        CLEAR WA_TAX1.
      ENDLOOP.
    ENDLOOP.
  ENDIF.
  CLEAR : IT_TAX2,WA_TAX2.
  LOOP AT IT_TAX1 INTO WA_TAX1.
    WA_TAX2-MBLNR = WA_TAX1-MBLNR.
    WA_TAX2-MJAHR = WA_TAX1-MJAHR.
    WA_TAX2-MATNR = WA_TAX1-MATNR.
    WA_TAX2-CHARG = WA_TAX1-CHARG.
    WA_TAX2-LFGJA = WA_TAX1-LFGJA.
    WA_TAX2-LFPOS = WA_TAX1-LFPOS.
    WA_TAX2-WRBTR = WA_TAX1-WRBTR.
    WA_TAX2-MENGE = WA_TAX1-MENGE.
    WA_TAX2-PEINH = WA_TAX1-PEINH.
    CLEAR: AWKEY.
    CONCATENATE WA_TAX1-BELNR WA_TAX1-GJAHR INTO AWKEY.
    SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ WA_TAX1-GJAHR AND AWKEY = AWKEY.
    IF SY-SUBRC EQ 0.
      WA_TAX2-BELNR = BKPF-BELNR.
      WA_TAX2-GJAHR =  BKPF-GJAHR.
      WA_TAX2-XBLNR =  BKPF-XBLNR.
      WA_TAX2-BLDAT = BKPF-BLDAT.
      WA_TAX2-BUDAT = BKPF-BUDAT.
*      SELECT SINGLE * FROM BSET WHERE BUKRS EQ 'BCLL' AND BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND
*        BUZEI EQ WA_RSEG-LFPOS.
*      IF SY-SUBRC EQ 0.
*        WA_RPM3-HWSTE = BSET-HWSTE.
*      ENDIF.
    ENDIF.
    COLLECT WA_TAX2 INTO IT_TAX2.
    CLEAR WA_TAX2.
  ENDLOOP.
  CLEAR : IT_BSET,WA_BSET.
  IF IT_TAX2 IS NOT INITIAL.
    SELECT * FROM BSET INTO TABLE IT_BSET FOR ALL ENTRIES IN IT_TAX2 WHERE BUKRS EQ 'BCLL' AND BELNR EQ IT_TAX2-BELNR AND GJAHR EQ IT_TAX2-GJAHR.
*      AND BUZEI EQ WA_TAX2-LFPOS.
  ENDIF.
  CLEAR : IT_TAX3,WA_TAX3.
  LOOP AT IT_TAX2 INTO WA_TAX2.
    LOOP AT IT_BSET INTO WA_BSET WHERE BELNR EQ WA_TAX2-BELNR AND GJAHR EQ WA_TAX2-GJAHR AND TXGRP EQ WA_TAX2-LFPOS.
      WA_TAX3-MBLNR = WA_TAX2-MBLNR.
      WA_TAX3-MJAHR = WA_TAX2-MJAHR.
      WA_TAX3-MATNR = WA_TAX2-MATNR.
      WA_TAX3-CHARG = WA_TAX2-CHARG.
*      WA_TAX3-LFGJA = WA_TAX2-LFGJA.
*      WA_TAX3-LFPOS = WA_TAX2-LFPOS.
      WA_TAX3-BELNR = WA_TAX2-BELNR.
      WA_TAX3-GJAHR =  WA_TAX2-GJAHR.
      WA_TAX3-XBLNR =  WA_TAX2-XBLNR.
      WA_TAX3-BLDAT = WA_TAX2-BLDAT.
      WA_TAX3-BUDAT = WA_TAX2-BUDAT.

      IF WA_BSET-SHKZG EQ 'H'.
        WA_BSET-HWSTE = WA_BSET-HWSTE * ( - 1 ).
      ENDIF.
      CLEAR : VAL,VAL1.
      VAL = WA_BSET-HWSTE / ( WA_TAX2-MENGE / WA_TAX2-PEINH ).
      VAL1 = WA_TAX2-WRBTR / ( WA_TAX2-MENGE / WA_TAX2-PEINH ).
      WA_BSET-HWSTE = VAL.
      WA_TAX2-WRBTR = VAL1.
      WA_TAX3-HWSTE = WA_BSET-HWSTE.
      IF WA_BSET-KTOSL EQ 'JIC' OR WA_BSET-KTOSL EQ 'JRC'.
        WA_TAX3-CGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JIS' OR WA_BSET-KTOSL EQ 'JRS' OR WA_BSET-KTOSL EQ 'JIU' OR WA_BSET-KTOSL EQ 'JRU'.
        WA_TAX3-SGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JRI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX3-IGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JCI' OR WA_BSET-KTOSL EQ 'JCR'.
        WA_TAX3-CESS = WA_BSET-HWSTE.
      ELSE.
        WA_TAX3-OTHR = WA_BSET-HWSTE.
      ENDIF.
      COLLECT WA_TAX3 INTO IT_TAX3.
      CLEAR WA_TAX3.
    ENDLOOP.
  ENDLOOP.

  SORT IT_TAX3 DESCENDING BY BELNR.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  ORITAX1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ORITAX1 .
  LOOP AT IT_RPM5 INTO WA_RPM5 WHERE BELNR EQ SPACE.
    WA_RPM6-MJAHR = WA_RPM5-MJAHR.
    WA_RPM6-MBLNR = WA_RPM5-MBLNR.
    WA_RPM6-WERKS = WA_RPM5-WERKS.
    WA_RPM6-BWART = WA_RPM5-BWART.
    WA_RPM6-MATNR = WA_RPM5-MATNR.
    WA_RPM6-MAKTX = WA_RPM5-MAKTX.
    WA_RPM6-CHARG = WA_RPM5-CHARG.
    WA_RPM6-MENGE = WA_RPM5-MENGE.
    WA_RPM6-MEINS = WA_RPM5-MEINS.
    WA_RPM6-LGORT = WA_RPM5-LGORT.
    WA_RPM6-EBELN = WA_RPM5-EBELN.
    WA_RPM6-EBELP = WA_RPM5-EBELP.
    WA_RPM6-LIFNR = WA_RPM5-LIFNR.
    WA_RPM6-NAME1 = WA_RPM5-NAME1.
    WA_RPM6-ORT01 = WA_RPM5-NAME1.
    WA_RPM6-DMBTR = WA_RPM5-DMBTR.
    WA_RPM6-STCD3 = WA_RPM5-STCD3.
    WA_RPM6-MWSKZ = WA_RPM5-MWSKZ.
    WA_RPM6-DELADDR1 = WA_RPM5-DELADDR1.
    WA_RPM6-DELADDR2 = WA_RPM5-DELADDR2.
    WA_RPM6-VBELN = WA_RPM5-VBELN.
    WA_RPM6-FKDAT = WA_RPM5-FKDAT.
    WA_RPM6-BELNR = WA_RPM5-BELNR.
    WA_RPM6-GJAHR =  WA_RPM5-GJAHR.
    WA_RPM6-XBLNR =  WA_RPM5-XBLNR.
    WA_RPM6-BLDAT =  WA_RPM5-BLDAT.
    WA_RPM6-BUDAT =  WA_RPM5-BUDAT.
    WA_RPM6-WRBTR =  WA_RPM5-WRBTR.
    WA_RPM6-HWSTE =  WA_RPM5-HWSTE.
    WA_RPM6-IGST =  WA_RPM5-IGST.
    WA_RPM6-CGST =  WA_RPM5-CGST.
    WA_RPM6-SGST =  WA_RPM5-SGST.
    WA_RPM6-CESS = WA_RPM5-CESS.
    WA_RPM6-OTHR =  WA_RPM5-OTHR.
    COLLECT WA_RPM6 INTO IT_RPM6.
    CLEAR WA_RPM6.
  ENDLOOP.

  CLEAR: IT_RSEG,IT_MSEG2.
  IF IT_RPM6 IS NOT INITIAL.
    SELECT * FROM MSEG INTO TABLE IT_MSEG2 FOR ALL ENTRIES IN IT_RPM6 WHERE BWART EQ '101' AND CHARG EQ IT_RPM6-CHARG AND LIFNR GT 0.
    IF SY-SUBRC EQ 0.
      SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_MSEG2  WHERE EBELN EQ IT_MSEG2-EBELN AND
      EBELP EQ IT_MSEG2-EBELP AND LFBNR EQ IT_MSEG2-MBLNR AND LFGJA EQ IT_MSEG2-MJAHR AND MATNR EQ IT_MSEG2-MATNR.
    ENDIF.
  ENDIF.

*    SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_RPM2  WHERE EBELN EQ IT_RPM2-RPEBELN AND
*      EBELP EQ IT_RPM2-RPEBELP AND LFBNR EQ IT_RPM2-RPMBLNR AND LFGJA EQ IT_RPM2-RPMJAHR AND MATNR EQ IT_RPM2-MATNR.
  CLEAR : IT_TAX1,WA_TAX1.
  SORT IT_RSEG DESCENDING BY BELNR.
  IF IT_MSEG2 IS NOT INITIAL.
    LOOP AT IT_MSEG2 INTO WA_MSEG2.
      LOOP AT IT_RSEG INTO WA_RSEG WHERE EBELN EQ WA_MSEG2-EBELN AND  EBELP EQ WA_MSEG2-EBELP AND LFBNR EQ WA_MSEG2-MBLNR AND LFGJA EQ WA_MSEG2-MJAHR
         AND MATNR EQ WA_MSEG2-MATNR AND LFPOS EQ WA_MSEG2-LINE_ID.
        WA_TAX1-MBLNR = WA_MSEG2-MBLNR.
        WA_TAX1-MJAHR = WA_MSEG2-MJAHR.
        WA_TAX1-MATNR = WA_MSEG2-MATNR.
        WA_TAX1-CHARG = WA_MSEG2-CHARG.
        WA_TAX1-LFGJA = WA_RSEG-LFGJA.
        WA_TAX1-LFPOS = WA_RSEG-LFPOS.
        WA_TAX1-BELNR = WA_RSEG-BELNR.
        WA_TAX1-GJAHR = WA_RSEG-GJAHR.
        WA_TAX1-WRBTR = WA_RSEG-WRBTR.
        WA_TAX1-MENGE = WA_RSEG-MENGE.
        SELECT SINGLE * FROM EKPO WHERE EBELN EQ WA_MSEG2-EBELN AND  EBELP EQ WA_MSEG2-EBELP.
        IF SY-SUBRC EQ 0.
          WA_TAX1-PEINH = EKPO-PEINH.
        ENDIF.
        COLLECT WA_TAX1 INTO IT_TAX1.
        CLEAR WA_TAX1.
      ENDLOOP.
    ENDLOOP.
  ENDIF.
  CLEAR : IT_TAX2,WA_TAX2.
  LOOP AT IT_TAX1 INTO WA_TAX1.
    WA_TAX2-MBLNR = WA_TAX1-MBLNR.
    WA_TAX2-MJAHR = WA_TAX1-MJAHR.
    WA_TAX2-MATNR = WA_TAX1-MATNR.
    WA_TAX2-CHARG = WA_TAX1-CHARG.
    WA_TAX2-LFGJA = WA_TAX1-LFGJA.
    WA_TAX2-LFPOS = WA_TAX1-LFPOS.
    WA_TAX2-WRBTR = WA_TAX1-WRBTR.
    WA_TAX2-MENGE = WA_TAX1-MENGE.
    WA_TAX2-PEINH = WA_TAX1-PEINH.
    CLEAR: AWKEY.
    CONCATENATE WA_TAX1-BELNR WA_TAX1-GJAHR INTO AWKEY.
    SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ WA_TAX1-GJAHR AND AWKEY = AWKEY.
    IF SY-SUBRC EQ 0.
      WA_TAX2-BELNR = BKPF-BELNR.
      WA_TAX2-GJAHR =  BKPF-GJAHR.
      WA_TAX2-XBLNR =  BKPF-XBLNR.
      WA_TAX2-BLDAT = BKPF-BLDAT.
      WA_TAX2-BUDAT = BKPF-BUDAT.
*      SELECT SINGLE * FROM BSET WHERE BUKRS EQ 'BCLL' AND BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND
*        BUZEI EQ WA_RSEG-LFPOS.
*      IF SY-SUBRC EQ 0.
*        WA_RPM3-HWSTE = BSET-HWSTE.
*      ENDIF.
    ENDIF.
    COLLECT WA_TAX2 INTO IT_TAX2.
    CLEAR WA_TAX2.
  ENDLOOP.
  CLEAR : IT_BSET,WA_BSET.
  IF IT_TAX2 IS NOT INITIAL.
    SELECT * FROM BSET INTO TABLE IT_BSET FOR ALL ENTRIES IN IT_TAX2 WHERE BUKRS EQ 'BCLL' AND BELNR EQ IT_TAX2-BELNR AND GJAHR EQ IT_TAX2-GJAHR.
*      AND BUZEI EQ WA_TAX2-LFPOS.
  ENDIF.
  CLEAR : IT_TAX3,WA_TAX3.
  LOOP AT IT_TAX2 INTO WA_TAX2.
    LOOP AT IT_BSET INTO WA_BSET WHERE BELNR EQ WA_TAX2-BELNR AND GJAHR EQ WA_TAX2-GJAHR AND TXGRP EQ WA_TAX2-LFPOS.
      WA_TAX3-MBLNR = WA_TAX2-MBLNR.
      WA_TAX3-MJAHR = WA_TAX2-MJAHR.
      WA_TAX3-MATNR = WA_TAX2-MATNR.
      WA_TAX3-CHARG = WA_TAX2-CHARG.
*      WA_TAX3-LFGJA = WA_TAX2-LFGJA.
*      WA_TAX3-LFPOS = WA_TAX2-LFPOS.
      WA_TAX3-BELNR = WA_TAX2-BELNR.
      WA_TAX3-GJAHR =  WA_TAX2-GJAHR.
      WA_TAX3-XBLNR =  WA_TAX2-XBLNR.
      WA_TAX3-BLDAT = WA_TAX2-BLDAT.
      WA_TAX3-BUDAT = WA_TAX2-BUDAT.

      IF WA_BSET-SHKZG EQ 'H'.
        WA_BSET-HWSTE = WA_BSET-HWSTE * ( - 1 ).
      ENDIF.
      CLEAR : VAL,VAL1.
      VAL = WA_BSET-HWSTE / ( WA_TAX2-MENGE / WA_TAX2-PEINH ).
      VAL1 = WA_TAX2-WRBTR / ( WA_TAX2-MENGE / WA_TAX2-PEINH ).
      WA_BSET-HWSTE = VAL.
      WA_TAX2-WRBTR = VAL1.
      WA_TAX3-HWSTE = WA_BSET-HWSTE.
      IF WA_BSET-KTOSL EQ 'JIC' OR WA_BSET-KTOSL EQ 'JRC'.
        WA_TAX3-CGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JIS' OR WA_BSET-KTOSL EQ 'JRS' OR WA_BSET-KTOSL EQ 'JIU' OR WA_BSET-KTOSL EQ 'JRU'.
        WA_TAX3-SGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JRI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX3-IGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JCI' OR WA_BSET-KTOSL EQ 'JCR'.
        WA_TAX3-CESS = WA_BSET-HWSTE.
      ELSE.
        WA_TAX3-OTHR = WA_BSET-HWSTE.
      ENDIF.
      COLLECT WA_TAX3 INTO IT_TAX3.
      CLEAR WA_TAX3.
    ENDLOOP.
  ENDLOOP.
  SORT IT_TAX3 DESCENDING BY BELNR.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  TAX1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM TAX1 .
  CLEAR: IT_RSEG,IT_MSEG2.
  IF IT_RPM3 IS NOT INITIAL.
    SELECT * FROM MSEG INTO TABLE IT_MSEG2 FOR ALL ENTRIES IN IT_RPM1  WHERE MBLNR EQ IT_RPM1-MBLNR AND MJAHR EQ IT_RPM1-MJAHR AND
    EBELN EQ IT_RPM1-EBELN AND EBELP EQ IT_RPM1-EBELP AND MATNR EQ IT_RPM1-MATNR AND CHARG EQ IT_RPM1-CHARG .
    IF SY-SUBRC EQ 0.
      SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_MSEG2  WHERE EBELN EQ IT_MSEG2-EBELN AND
      EBELP EQ IT_MSEG2-EBELP AND LFBNR EQ IT_MSEG2-MBLNR AND LFGJA EQ IT_MSEG2-MJAHR AND MATNR EQ IT_MSEG2-MATNR.
    ENDIF.
  ENDIF.

*    SELECT * FROM RSEG INTO TABLE IT_RSEG FOR ALL ENTRIES IN IT_RPM2  WHERE EBELN EQ IT_RPM2-RPEBELN AND
*      EBELP EQ IT_RPM2-RPEBELP AND LFBNR EQ IT_RPM2-RPMBLNR AND LFGJA EQ IT_RPM2-RPMJAHR AND MATNR EQ IT_RPM2-MATNR.
  CLEAR : IT_TAX1,WA_TAX1.
  SORT IT_RSEG DESCENDING BY BELNR.
  IF IT_MSEG2 IS NOT INITIAL.
    LOOP AT IT_MSEG2 INTO WA_MSEG2.
      LOOP AT IT_RSEG INTO WA_RSEG WHERE EBELN EQ WA_MSEG2-EBELN AND  EBELP EQ WA_MSEG2-EBELP AND LFBNR EQ WA_MSEG2-MBLNR AND LFGJA EQ WA_MSEG2-MJAHR
         AND MATNR EQ WA_MSEG2-MATNR AND LFPOS EQ WA_MSEG2-LINE_ID.
        WA_TAX1-MBLNR = WA_MSEG2-MBLNR.
        WA_TAX1-MJAHR = WA_MSEG2-MJAHR.
        WA_TAX1-MATNR = WA_MSEG2-MATNR.
        WA_TAX1-CHARG = WA_MSEG2-CHARG.
        WA_TAX1-LFGJA = WA_RSEG-LFGJA.
        WA_TAX1-LFPOS = WA_RSEG-LFPOS.
        WA_TAX1-BELNR = WA_RSEG-BELNR.
        WA_TAX1-GJAHR = WA_RSEG-GJAHR.
        WA_TAX1-WRBTR = WA_RSEG-WRBTR.
        COLLECT WA_TAX1 INTO IT_TAX1.
        CLEAR WA_TAX1.
      ENDLOOP.
    ENDLOOP.
  ENDIF.
  CLEAR : IT_TAX2,WA_TAX2.
  LOOP AT IT_TAX1 INTO WA_TAX1.
    WA_TAX2-MBLNR = WA_TAX1-MBLNR.
    WA_TAX2-MJAHR = WA_TAX1-MJAHR.
    WA_TAX2-MATNR = WA_TAX1-MATNR.
    WA_TAX2-CHARG = WA_TAX1-CHARG.
    WA_TAX2-LFGJA = WA_TAX1-LFGJA.
    WA_TAX2-LFPOS = WA_TAX1-LFPOS.
    WA_TAX2-WRBTR = WA_TAX1-WRBTR.
    CLEAR: AWKEY.
    CONCATENATE WA_TAX1-BELNR WA_TAX1-GJAHR INTO AWKEY.
    SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ WA_TAX1-GJAHR AND AWKEY = AWKEY.
    IF SY-SUBRC EQ 0.
      WA_TAX2-BELNR = BKPF-BELNR.
      WA_TAX2-GJAHR =  BKPF-GJAHR.
      WA_TAX2-XBLNR =  BKPF-XBLNR.
      WA_TAX2-BLDAT = BKPF-BLDAT.
      WA_TAX2-BUDAT = BKPF-BUDAT.
*      SELECT SINGLE * FROM BSET WHERE BUKRS EQ 'BCLL' AND BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND
*        BUZEI EQ WA_RSEG-LFPOS.
*      IF SY-SUBRC EQ 0.
*        WA_RPM3-HWSTE = BSET-HWSTE.
*      ENDIF.
    ENDIF.
    COLLECT WA_TAX2 INTO IT_TAX2.
    CLEAR WA_TAX2.
  ENDLOOP.

  IF IT_TAX2 IS NOT INITIAL.
    SELECT * FROM BSET INTO TABLE IT_BSET FOR ALL ENTRIES IN IT_TAX2 WHERE BUKRS EQ 'BCLL' AND BELNR EQ IT_TAX2-BELNR AND GJAHR EQ IT_TAX2-GJAHR.
*      AND BUZEI EQ WA_TAX2-LFPOS.
  ENDIF.
  CLEAR : IT_TAX3,WA_TAX3.
  LOOP AT IT_TAX2 INTO WA_TAX2.
    LOOP AT IT_BSET INTO WA_BSET WHERE BELNR EQ WA_TAX2-BELNR AND GJAHR EQ WA_TAX2-GJAHR AND TXGRP EQ WA_TAX2-LFPOS.
      WA_TAX3-MBLNR = WA_TAX2-MBLNR.
      WA_TAX3-MJAHR = WA_TAX2-MJAHR.
      WA_TAX3-MATNR = WA_TAX2-MATNR.
      WA_TAX3-CHARG = WA_TAX2-CHARG.
*      WA_TAX3-LFGJA = WA_TAX2-LFGJA.
*      WA_TAX3-LFPOS = WA_TAX2-LFPOS.
      WA_TAX3-BELNR = WA_TAX2-BELNR.
      WA_TAX3-GJAHR =  WA_TAX2-GJAHR.
      WA_TAX3-XBLNR =  WA_TAX2-XBLNR.
      WA_TAX3-BLDAT = WA_TAX2-BLDAT.
      WA_TAX3-BUDAT = WA_TAX2-BUDAT.

      IF WA_BSET-SHKZG EQ 'H'.
        WA_BSET-HWSTE = WA_BSET-HWSTE * ( - 1 ).
      ENDIF.
      WA_TAX3-HWSTE = WA_BSET-HWSTE.
      IF WA_BSET-KTOSL EQ 'JIC' OR WA_BSET-KTOSL EQ 'JRC'.
        WA_TAX3-CGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JIS' OR WA_BSET-KTOSL EQ 'JRS' OR WA_BSET-KTOSL EQ 'JIU' OR WA_BSET-KTOSL EQ 'JRU'.
        WA_TAX3-SGST = WA_BSET-HWSTE.
      ELSEIF WA_BSET-KTOSL EQ 'JII' OR WA_BSET-KTOSL EQ 'JRI' OR WA_BSET-KTOSL EQ 'JIM'.
        WA_TAX3-IGST = WA_BSET-HWSTE.
        WA_TAX3-WRBTR = WA_TAX2-WRBTR.
      ELSEIF WA_BSET-KTOSL EQ 'JCI' OR WA_BSET-KTOSL EQ 'JCR'.
        WA_TAX3-CESS = WA_BSET-HWSTE.
      ELSE.
        WA_TAX3-OTHR = WA_BSET-HWSTE.
      ENDIF.
      COLLECT WA_TAX3 INTO IT_TAX3.
      CLEAR WA_TAX3.
    ENDLOOP.
  ENDLOOP.



*  LOOP AT IT_TAX3 INTO WA_TAX3.
*
*    ENDLOOP.



*  LOOP AT IT_RPM2 INTO WA_RPM2.
*    WA_RPM3-MATNR = WA_RPM2-MATNR.
*    WA_RPM3-CHARG = WA_RPM2-CHARG.
*    WA_RPM3-RPEBELN = WA_RPM2-RPEBELN.
*    WA_RPM3-RPEBELP = WA_RPM2-RPEBELP.
*    WA_RPM3-RPMBLNR = WA_RPM2-RPMBLNR.
*    WA_RPM3-RPMJAHR =  WA_RPM2-RPMJAHR.
*    WA_RPM3-RPLINE_ID = WA_RPM2-RPLINE_ID.
*    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_RPM2-RPMBLNR AND MJAHR EQ WA_RPM2-RPMJAHR  AND MATNR EQ WA_RPM2-MATNR
*       AND CHARG EQ  WA_RPM2-CHARG.
*    IF SY-SUBRC EQ 0.
*      READ TABLE IT_RSEG INTO WA_RSEG WITH KEY BUZEI = MSEG-LINE_ID EBELN = WA_RPM2-RPEBELN EBELP = WA_RPM2-RPEBELP LFBNR = WA_RPM2-RPMBLNR
*      LFGJA = WA_RPM2-RPMJAHR MATNR = WA_RPM2-MATNR.
*      IF SY-SUBRC EQ 0.
*        WA_RPM3-RPBELNR = WA_RSEG-BELNR.
*        WA_RPM3-RPGJAHR =  WA_RSEG-GJAHR.
*        WA_RPM3-RPXBLNR =  WA_RSEG-XBLNR.
*        WA_RPM3-RPMWSKZ =  WA_RSEG-MWSKZ.
*        WA_RPM3-WRBTR =  WA_RSEG-WRBTR.
*        CLEAR: AWKEY.
*        CONCATENATE WA_RSEG-BELNR WA_RSEG-GJAHR INTO AWKEY.
*        SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ WA_RSEG-GJAHR AND AWKEY = AWKEY.
*        IF SY-SUBRC EQ 0.
*          WA_RPM3-RPFIDOC = BKPF-BELNR.
*          WA_RPM3-RPFIDOCYR =  BKPF-GJAHR.
*          SELECT SINGLE * FROM BSET WHERE BUKRS EQ 'BCLL' AND BELNR EQ BKPF-BELNR AND GJAHR EQ BKPF-GJAHR AND
*            BUZEI EQ WA_RSEG-LFPOS.
*          IF SY-SUBRC EQ 0.
*            WA_RPM3-HWSTE = BSET-HWSTE.
*          ENDIF.
*        ENDIF.
*      ENDIF.
*    ENDIF.
*    COLLECT WA_RPM3 INTO IT_RPM3.
*    CLEAR WA_RPM3.
*  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*&      Module  STATUS_9001  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  ALV
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  ALV_BUILD_FIELDCAT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  ALV_REPORT_LAYOUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_9001  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  BATCHDET
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM BATCHDET .
  CLEAR : CHARG,MATNR,MJAHR.
  CLEAR : IT_DET2,WA_DET2.
  LOOP AT IT_RPM7 INTO WA_RPM7 WHERE CHK1 = 'X'.
    WA_DET2-CHARG = WA_RPM7-CHARG.
    WA_DET2-MATNR = WA_RPM7-MATNR.
    WA_DET2-MJAHR = WA_RPM7-MJAHR.
    COLLECT WA_DET2 INTO IT_DET2.
    CLEAR WA_DET2.
  ENDLOOP.
  SORT IT_DET2 BY MATNR CHARG MJAHR.
  DELETE ADJACENT DUPLICATES FROM IT_DET2.
**  break-point.
*  select * from mseg into table it_mseg11 where mjahr ge mjahr and bwart in ( '543','544' ) and matnr eq matnr and charg eq charg.
  CLEAR : IT_MSEG11,WA_MSEG11.
  SELECT * FROM MSEG INTO TABLE IT_MSEG11 FOR ALL ENTRIES IN IT_DET2 WHERE MJAHR GE IT_DET2-MJAHR AND BWART IN ( '543','544' )
    AND MATNR EQ IT_DET2-MATNR AND CHARG EQ IT_DET2-CHARG .
  CLEAR : IT_DET1,WA_DET1.
  CLEAR : IT_DET3,WA_DET3.
  LOOP AT IT_MSEG11 INTO WA_MSEG11.
    WA_DET3-MBLNR = WA_MSEG11-MBLNR.
    WA_DET3-MJAHR = WA_MSEG11-MJAHR.
    WA_DET3-BWART = WA_MSEG11-BWART.
    WA_DET3-MATNR = WA_MSEG11-MATNR.
    WA_DET3-CHARG = WA_MSEG11-CHARG.
    IF WA_MSEG11-SHKZG EQ 'S'.
      WA_MSEG11-DMBTR = WA_MSEG11-DMBTR * ( - 1 ).
    ENDIF.
    WA_DET3-DMBTR = WA_MSEG11-DMBTR.
    COLLECT WA_DET3 INTO IT_DET3.
    CLEAR WA_DET3.
  ENDLOOP.
  LOOP AT IT_MSEG11 INTO WA_MSEG11.
    WA_DET1-MBLNR = WA_MSEG11-MBLNR.
    WA_DET1-BWART = WA_MSEG11-BWART.
    WA_DET1-MJAHR = WA_MSEG11-MJAHR.
    WA_DET1-WERKS = WA_MSEG11-WERKS.
    READ TABLE IT_DET3 INTO WA_DET3 WITH KEY MBLNR = WA_MSEG11-MBLNR MJAHR = WA_MSEG11-MJAHR MATNR = WA_MSEG11-MATNR CHARG = WA_MSEG11-CHARG
    BWART = WA_MSEG11-BWART.
    IF SY-SUBRC EQ 0.
      WA_DET1-DMBTR = WA_DET3-DMBTR.
    ENDIF.
    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_MSEG11-MBLNR AND MJAHR EQ WA_MSEG11-MJAHR.
    IF SY-SUBRC EQ 0.
      CLEAR :  DOC3.
      CONCATENATE WA_MSEG11-MBLNR WA_MSEG11-MJAHR INTO DOC3.
      SELECT SINGLE * FROM BKPF WHERE BUKRS EQ 'BCLL' AND GJAHR EQ MSEG-GJAHR AND AWKEY EQ DOC3.
      IF SY-SUBRC EQ 0.
        WA_DET1-BELNR = BKPF-BELNR.
        WA_DET1-GJAHR = BKPF-GJAHR.
      ENDIF.
    ENDIF.
    WA_DET1-MATNR = WA_MSEG11-MATNR.
    WA_DET1-CHARG = WA_MSEG11-CHARG.
    SELECT SINGLE * FROM MSEG WHERE MBLNR EQ WA_MSEG11-MBLNR AND MJAHR EQ WA_MSEG11-MJAHR AND LGORT NE SPACE.
    IF SY-SUBRC EQ 0.
      WA_DET1-FGCHARG = MSEG-CHARG.
    ENDIF.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MSEG11-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_DET1-MAKTX = MAKT-MAKTX.
    ENDIF.
    COLLECT WA_DET1 INTO IT_DET1.
    CLEAR WA_DET1.
  ENDLOOP.
*  break-point.

  WA_FIELDCAT1-FIELDNAME = 'BWART'.
  WA_FIELDCAT1-SELTEXT_L = 'MOV'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'WERKS'.
  WA_FIELDCAT1-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'MBLNR'.
  WA_FIELDCAT1-SELTEXT_L = 'GRN'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.



  WA_FIELDCAT1-FIELDNAME = 'MJAHR'.
  WA_FIELDCAT1-SELTEXT_L = 'GRN YEAR'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT1-SELTEXT_L = 'MATERIAL NAME'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'MATNR'.
  WA_FIELDCAT1-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'CHARG'.
  WA_FIELDCAT1-SELTEXT_L = 'MAYTERIAL BATCH'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'DMBTR'.
  WA_FIELDCAT1-SELTEXT_L = 'GRN MATERIAL VAL'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'FGCHARG'.
  WA_FIELDCAT1-SELTEXT_L = 'FG BATCH'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'BELNR'.
  WA_FIELDCAT1-SELTEXT_L = 'FG GRN FI DOC'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

  WA_FIELDCAT1-FIELDNAME = 'GJAHR'.
  WA_FIELDCAT1-SELTEXT_L = 'FG GRN FI YR'.
  APPEND WA_FIELDCAT1 TO FIELDCAT1.
  CLEAR : WA_FIELDCAT1.

*  wa_fieldcat1-fieldname = 'ZSAM'.
*  wa_fieldcat1-seltext_l = 'ZZSAM VALUE'.
*  wa_fieldcat1-edit = 'X'.
*  append wa_fieldcat1 to fieldcat1.
*  clear : wa_fieldcat1.




  L_GLAY-EDT_CLL_CB = 'X'.

*  ls_layout-colwidth_optimize = 'X'.

*  wa_fieldcat1-fieldname = 'CHK'.
*  wa_fieldcat1-seltext_l = 'SELECT'.
*  wa_fieldcat1-checkbox = 'X'.
*  wa_fieldcat1-edit = 'X'.
*  append wa_fieldcat1 to fieldcat1.
*  clear wa_fieldcat1.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'LLM FG BATCH DETAILS FOR RM & PM'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = 'STATUS'
      I_CALLBACK_USER_COMMAND = 'USER_COMM1'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP1'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         = L_GLAY
      IS_LAYOUT               = LAYOUT1
      IT_FIELDCAT             = FIELDCAT1
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_DET1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CLEAR : LAYOUT1,FIELDCAT1.
  CLEAR : IT_DET1,WA_DET1.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Module  STATUS_9002  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE STATUS_9002 OUTPUT.
  SET PF-STATUS 'STATUS'.
  SET TITLEBAR 'TEST1'.
  PERFORM ALV2.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Form  ALV2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ALV2 .

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  ALV11
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ALV11 .
  WA_FIELDCAT-FIELDNAME = 'MBLNR'.
  WA_FIELDCAT-SELTEXT_L = 'GRN'.
  APPEND WA_FIELDCAT TO FIELDCAT.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'PLANT WISE STOCK TRANSFER DETAIL'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_DET1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.


FORM USER_COMM USING UCOMM LIKE SY-UCOMM SELFIELD TYPE SLIS_SELFIELD.
*  IF R1 EQ 'X'.
  CASE SY-UCOMM. "SELFIELD-FIELDNAME.
*      loop at it_tab5 into wa_tab5 WHERE nsampqty ne 0 AND chk ne 'X'.
*        MESSAGE 'TICK THE CHECKBOX TO SAVE DATA' TYPE 'E'.
*      ENDLOOP.
*      break-point.
    WHEN '&DATA_SAVE'(001).
*      message 'TERRITORY SAVED 1' type 'I'.
*      PERFORM BDC.
      PERFORM BATCHDET.
    WHEN 'MBLNR'.
      SET PARAMETER ID 'MBN' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'MB03' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
      CASE SELFIELD-FIELDNAME.
        WHEN 'MBLNR'.
          SET PARAMETER ID 'MBN' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'MB03' AND SKIP FIRST SCREEN.
        WHEN 'MBLNR541'.
          SET PARAMETER ID 'MBN' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'MB03' AND SKIP FIRST SCREEN.
        WHEN 'EBELN'.
          SET PARAMETER ID 'BES' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'ME23N' AND SKIP FIRST SCREEN.
        WHEN 'LIFNR'.
          SET PARAMETER ID 'LIF' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'XK03' AND SKIP FIRST SCREEN.
        WHEN 'BELNR'.
          SET PARAMETER ID 'BLN' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.
        WHEN 'GRBELNR'.
          SET PARAMETER ID 'BLN' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.
        WHEN 'BELNR541'.
          SET PARAMETER ID 'BLN' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.
        WHEN 'MATNR'.
          SET PARAMETER ID 'MAT' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.

        WHEN 'VBELN1'.
          SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
          CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
        WHEN OTHERS.
      ENDCASE.
  ENDCASE.
  EXIT.
ENDFORM.                    "USER_COMM

FORM TOP.
  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'TICK THE CHECKBOX & SAVE TO PROCEED'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT.
*     I_LOGO                   = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID       =
*     I_ALV_FORM               =
  CLEAR COMMENT.
ENDFORM.                    "TOP


FORM TOP1.
  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'LLM FG BATCH DETAILS FOR RM & PM'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT.
*     I_LOGO                   = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID       =
*     I_ALV_FORM               =
  CLEAR COMMENT.
ENDFORM.                    "TOP

FORM USER_COMM1 USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'MBLNR'.
      SET PARAMETER ID 'MBN' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'MB03' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN 'BELNR'.
      SET PARAMETER ID 'BLN' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.
