"Name: \PR:SAPMM07M\FO:KONTIERUNG_LESEN\SE:BEGIN\EI
ENHANCEMENT 0 ZMB1B.
*
  IF SY-TCODE = 'MIGO'.
    IF MSEG-WERKS EQ '1000' .

      IF MSEG-LGORT EQ 'RM04' OR MSEG-LGORT EQ 'PM04' OR MSEG-LGORT EQ 'SF04'.
        IF MSEG-BWART EQ '349'.
        ELSEIF MSEG-BWART EQ '350'.
        ELSEIF MSEG-BWART EQ '344'.
        ELSE.
          IF MSEGK-UMLGO EQ 'RM04' OR MSEGK-UMLGO EQ 'PM04' OR MSEGK-UMLGO EQ 'SF04'."26.11.20
          ELSE.
            IF  MSEG-BWART eq '311'.
              IF SY-UNAME EQ 'BCLPLJK' OR SY-UNAME EQ '13959'.  "ADDED QA ON 2.5.23
                MESSAGE 'TRANSFER FROM CEPHA IS NOT ALLOWED' TYPE 'I'.  "changes to move to rm05 on 5.9.21
              ELSE.
                MESSAGE 'TRANSFER FROM CEPHA IS NOT ALLOWED' TYPE 'E'.
              ENDIF.
            ENDIF.
          ENDIF.

        ENDIF.
      ENDIF.

    ENDIF.
  ENDIF.

ENDENHANCEMENT.
