*&---------------------------------------------------------------------*
*& Report  ZMC46_1
*& report developed by Jyotsna' Jan'15
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZMC46_8 NO STANDARD PAGE HEADING LINE-SIZE 200.

TABLES : MCHB,
         MARA,
         MAKT,
         MBEW,
         KNA1,
         ADRC,
         T005U,
         WB2_V_VBRK_VBRP2,
         VBRP,
         VBRK,
         T005T.

TYPES : BEGIN OF TYP_AUFM,
          BWART TYPE AUFM-BWART,
          WERKS TYPE AUFM-WERKS,
          MATNR TYPE AUFM-MATNR,
          CHARG TYPE AUFM-CHARG,
          BUDAT TYPE AUFM-BUDAT,
        END OF TYP_AUFM.

TYPES : BEGIN OF TYP_MSEG,
          MBLNR TYPE MSEG-MBLNR,
          MJAHR TYPE MSEG-MJAHR,
          BWART TYPE AUFM-BWART,
          WERKS TYPE AUFM-WERKS,
          MATNR TYPE AUFM-MATNR,
          CHARG TYPE AUFM-CHARG,
          BUDAT TYPE AUFM-BUDAT,
        END OF TYP_MSEG.

DATA : IT_MCHB             TYPE TABLE OF MCHB,
       WA_MCHB             TYPE MCHB,
       IT_MCHA             TYPE TABLE OF MCHA,
       WA_MCHA             TYPE MCHA,
       IT_MARA             TYPE TABLE OF MARA,
       WA_MARA             TYPE MARA,
       IT_AUFM             TYPE TABLE OF TYP_AUFM,
       WA_AUFM             TYPE TYP_AUFM,
       IT_MSEG             TYPE TABLE OF TYP_MSEG,
       WA_MSEG             TYPE TYP_MSEG,
       IT_MKPF             TYPE TABLE OF MKPF,
       WA_MKPF             TYPE MKPF,
       IT_VBRP             TYPE TABLE OF VBRP,
       WA_VBRP             TYPE VBRP,
       IT_VBRK             TYPE TABLE OF VBRK,
       WA_VBRK             TYPE VBRK,
       IT_WB2_V_VBRK_VBRP2 TYPE TABLE OF WB2_V_VBRK_VBRP2,
       WA_WB2_V_VBRK_VBRP2 TYPE WB2_V_VBRK_VBRP2.

TYPES : BEGIN OF ITAB,
          BWART TYPE MSEG-BWART,
          WERKS TYPE MCHB-WERKS,
          MATNR TYPE MCHB-MATNR,
          CHARG TYPE MCHB-CHARG,
          BUDAT TYPE MKPF-BUDAT,
        END OF ITAB.

TYPES : BEGIN OF ITAB1,
          MTART    TYPE MARA-MTART,
          WERKS    TYPE MCHB-WERKS,
          MATNR    TYPE MCHB-MATNR,
          CHARG    TYPE MCHB-CHARG,
          CLABS    TYPE MCHB-CLABS,
          CINSM    TYPE MCHB-CINSM,
          CLABS3   TYPE MCHB-CLABS,
          CLABS6   TYPE MCHB-CLABS,
          CLABS12  TYPE MCHB-CLABS,
          CLABS12A TYPE MCHB-CLABS,
          ERSDA    TYPE MCHB-ERSDA,
          LGORT    TYPE MCHB-LGORT,
          LWEDT    TYPE MCHA-LWEDT,
          HSDAT    TYPE MCHA-HSDAT,
          VFDAT    TYPE MCHA-VFDAT,
          MAKTX    TYPE MAKT-MAKTX,
          BUDAT    TYPE AUFM-BUDAT,
          VERPR    TYPE MBEW-VERPR,
          MV       TYPE P  DECIMALS 2,
          MV3      TYPE P  DECIMALS 2,
          MV6      TYPE P  DECIMALS 2,
          MV12     TYPE P  DECIMALS 2,
          MV12A    TYPE P  DECIMALS 2,
          DAY2     TYPE P,
          VMPEI    TYPE MBEW-VMPEI,
          BEZEI    TYPE T005U-BEZEI,
          LAND1    TYPE VBRK-LAND1,
          REGIO    TYPE VBRK-REGIO,
          KUNNR    TYPE VBRK-KUNAG,
          R_MONTH  TYPE I,
          R_LIFE   TYPE I,
          PER      TYPE P DECIMALS 2,
          KUNAG    TYPE VBRK-KUNAG,
          LANDX    TYPE T005T-LANDX,
        END OF ITAB1.

TYPES : BEGIN OF ITAB11,
          MTART TYPE MARA-MTART,
          WERKS TYPE MCHB-WERKS,
          MATNR TYPE MCHB-MATNR,
          CHARG TYPE MCHB-CHARG,
          CLABS TYPE MCHB-CLABS,
          CINSM TYPE MCHB-CINSM,
          ERSDA TYPE MCHB-ERSDA,
          LGORT TYPE MCHB-LGORT,
          LWEDT TYPE MCHA-LWEDT,
          HSDAT TYPE MCHA-HSDAT,
          VFDAT TYPE MCHA-VFDAT,
          MAKTX TYPE MAKT-MAKTX,
          BUDAT TYPE AUFM-BUDAT,
        END OF ITAB11.

TYPES : BEGIN OF MAT1,
          MAT(3)  TYPE C,
          COUNTRY TYPE T005T-LAND1,
        END OF MAT1.

DATA : IT_TAB   TYPE TABLE OF ITAB,
       WA_TAB   TYPE ITAB,
       IT_TAB1  TYPE TABLE OF ITAB1,
       WA_TAB1  TYPE ITAB1,
       IT_TAB2  TYPE TABLE OF ITAB1,
       WA_TAB2  TYPE ITAB1,
       IT_TAB3  TYPE TABLE OF ITAB1,
       WA_TAB3  TYPE ITAB1,
       IT_TAB11 TYPE TABLE OF ITAB11,
       WA_TAB11 TYPE ITAB11,
       IT_MAT1  TYPE TABLE OF MAT1,
       WA_MAT1  TYPE MAT1.

DATA : C_DATE     TYPE SY-DATUM,
       STAY       TYPE I,
       STAY1      TYPE I,
       STAY2      TYPE I,
       STAY3      TYPE I,
       STAY4(10)  TYPE C,
       RSTAY      TYPE I,
       RSTAY1     TYPE I,
       RSTAY2     TYPE I,
       RSTAY3     TYPE I,
       RSTAY4(10) TYPE C.
DATA : MV      TYPE P DECIMALS 2,
       RATE1   TYPE P DECIMALS 2,
       PER     TYPE P DECIMALS 2,
       REG(3)  TYPE C,
       COUNTRY TYPE T005T-LAND1.

DATA : DT1 TYPE SY-DATUM,
       DT2 TYPE SY-DATUM,
       DT3 TYPE SY-DATUM,
       DT4 TYPE SY-DATUM,
       DT5 TYPE SY-DATUM,
       DT6 TYPE SY-DATUM,
       DT7 TYPE SY-DATUM.

TYPE-POOLS: SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.

DATA : DATE_3  TYPE SY-DATUM,
       DATE_6  TYPE SY-DATUM,
       DATE_12 TYPE SY-DATUM,
       CDATE   TYPE SY-DATUM.
DATA: STOCK TYPE MCHB-CLABS.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : PLANT FOR MCHB-WERKS,
                 LGORT FOR MCHB-LGORT,
                 MATNR FOR MCHB-MATNR,
                 TYPE FOR MARA-MTART.
SELECTION-SCREEN END OF BLOCK MERKMALE1.
*obligatory default 'ZESC'.
*select-options : inv_type for vbrk-fkart obligatory default 'Z002'.
*PARAMETER : days(3) TYPE c NO-DISPLAY.

*PARAMETER : r1 RADIOBUTTON GROUP r1,
*            r2 RADIOBUTTON GROUP r1.




INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION.

*  if r1 eq 'X'.
*    PERFORM RMPM.
*  ELSE.
  PERFORM FINISH.
*  ENDIF.


*----------------------------------------------------------------------*
FORM FINISH.
  SELECT * FROM MCHB INTO TABLE IT_MCHB WHERE WERKS IN PLANT AND LGORT IN LGORT AND MATNR IN MATNR .
  IF SY-SUBRC EQ 0.
    SELECT * FROM MARA INTO TABLE IT_MARA FOR ALL ENTRIES IN IT_MCHB WHERE MATNR EQ IT_MCHB-MATNR AND MTART IN TYPE.
    IF SY-SUBRC NE 0.
      EXIT.
    ENDIF.
  ENDIF.

  SELECT * FROM MCHA INTO TABLE IT_MCHA FOR ALL ENTRIES IN IT_MCHB WHERE MATNR EQ IT_MCHB-MATNR AND WERKS EQ
     IT_MCHB-WERKS AND CHARG EQ IT_MCHB-CHARG.

  LOOP AT IT_MCHB INTO WA_MCHB.
    CLEAR : STOCK.
    STOCK = WA_MCHB-CLABS + WA_MCHB-CINSM.
    IF STOCK GT 0.
*  WRITE : / WA_MCHB-WERKS,WA_MCHB-MATNR,WA_MCHB-CHARG,WA_MCHB-CLABS.
*  WA_MCHB-ERSDA.
      READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_MCHB-MATNR.
      IF SY-SUBRC EQ 0.
*      if wa_mara-mtart NE 'ZVRP' OR wa_mara-mtart NE 'ZROH'.
        WA_TAB11-MTART = WA_MARA-MTART.
        WA_TAB11-WERKS = WA_MCHB-WERKS.
        WA_TAB11-MATNR = WA_MCHB-MATNR.
        SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MCHB-MATNR AND SPRAS EQ 'EN'.
        IF SY-SUBRC EQ 0.
          WA_TAB11-MAKTX = MAKT-MAKTX.
        ENDIF.
        WA_TAB11-CHARG = WA_MCHB-CHARG.
        WA_TAB11-CLABS = WA_MCHB-CLABS.
        WA_TAB11-CINSM = WA_MCHB-CINSM.
        WA_TAB11-LGORT = WA_MCHB-LGORT.
        WA_TAB11-ERSDA = WA_MCHB-ERSDA.
        READ TABLE IT_MCHA INTO WA_MCHA WITH KEY MATNR = WA_MCHB-MATNR WERKS = WA_MCHB-WERKS CHARG = WA_MCHB-CHARG.
        IF SY-SUBRC EQ 0.
*    WRITE : WA_MCHA-LWEDT.
*          WA_TAB11-LWEDT = WA_MCHA-LWEDT.
          WA_TAB11-HSDAT = WA_MCHA-HSDAT.
          WA_TAB11-VFDAT = WA_MCHA-VFDAT.
        ENDIF.
        COLLECT WA_TAB11 INTO IT_TAB11.
        CLEAR WA_TAB11.
      ENDIF.
    ENDIF.
  ENDLOOP.

  LOOP AT IT_TAB11 INTO WA_TAB11.
    CLEAR : MV, STAY,STAY1,STAY2,STAY3,RSTAY,RSTAY1,RSTAY2,RSTAY3,PER,DATE_3,DATE_6,DATE_12.
    WA_TAB2-MTART = WA_TAB11-MTART.
    WA_TAB2-WERKS = WA_TAB11-WERKS.
    WA_TAB2-MATNR = WA_TAB11-MATNR.
    WA_TAB2-MAKTX = WA_TAB11-MAKTX.
    WA_TAB2-CHARG = WA_TAB11-CHARG.
    WA_TAB2-CLABS = WA_TAB11-CLABS.
    WA_TAB2-CINSM = WA_TAB11-CINSM.
    WA_TAB2-LGORT = WA_TAB11-LGORT.
    WA_TAB2-ERSDA = WA_TAB11-ERSDA.
    WA_TAB2-HSDAT = WA_TAB11-HSDAT.
    WA_TAB2-VFDAT = WA_TAB11-VFDAT.

    SELECT SINGLE * FROM MBEW WHERE MATNR EQ WA_TAB11-MATNR AND BWKEY EQ WA_TAB11-WERKS.
    IF SY-SUBRC EQ 0.
      RATE1 = MBEW-VERPR / MBEW-VMPEI.
      WA_TAB2-VERPR = MBEW-VERPR.
      WA_TAB2-VMPEI = MBEW-VMPEI.
      MV = WA_TAB11-CLABS * RATE1.
      WA_TAB2-MV = MV.
    ENDIF.

    CALL FUNCTION 'HR_SGPBS_YRS_MTHS_DAYS'
      EXPORTING
        BEG_DA        = WA_TAB11-HSDAT
        END_DA        = SY-DATUM
      IMPORTING
        NO_DAY        = STAY
        NO_MONTH      = STAY1
        NO_YEAR       = STAY2
        NO_CAL_DAY    = STAY3
      EXCEPTIONS
        DATEINT_ERROR = 1
        OTHERS        = 2.
    IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.

    CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
      EXPORTING
        MONTHS  = '3'
        OLDDATE = WA_TAB11-HSDAT
      IMPORTING
        NEWDATE = DATE_3.

    CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
      EXPORTING
        MONTHS  = '6'
        OLDDATE = WA_TAB11-HSDAT
      IMPORTING
        NEWDATE = DATE_6.

    CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
      EXPORTING
        MONTHS  = '12'
        OLDDATE = WA_TAB11-HSDAT
      IMPORTING
        NEWDATE = DATE_12.

*    WRITE : /'*', WA_TAB11-MATNR,WA_TAB11-HSDAT,STAY1,stay3,date_3,date_6,date_12.

    IF SY-DATUM LE DATE_3.
      WA_TAB2-CLABS3 = WA_TAB11-CLABS.
      WA_TAB2-MV3 = WA_TAB2-MV.
    ELSEIF SY-DATUM GT DATE_3 AND SY-DATUM LE DATE_6.
      WA_TAB2-CLABS6 = WA_TAB11-CLABS.
      WA_TAB2-MV6 = WA_TAB2-MV.
    ELSEIF SY-DATUM GT DATE_6 AND SY-DATUM LE DATE_12.
      WA_TAB2-CLABS12 = WA_TAB11-CLABS.
      WA_TAB2-MV12 = WA_TAB2-MV.
    ELSE.
      WA_TAB2-CLABS12A = WA_TAB11-CLABS.
      WA_TAB2-MV12A = WA_TAB2-MV.
    ENDIF.

*    wa_tab2-R_MONTH = stay1.
    COLLECT WA_TAB2 INTO IT_TAB2.
    CLEAR WA_TAB2.
  ENDLOOP.

*  if it_tab2 is not initial.
*    select * from vbrk into table it_vbrk for all entries in it_tab2 where fkart in inv_type and fkdat gt it_tab2-hsdat.
*    if sy-subrc eq 0.
*      select * from vbrp into table it_vbrp for all entries in it_vbrk where vbeln eq it_vbrk-vbeln and matnr in matnr.
*    endif.
*  endif.
*  sort it_vbrp descending by erdat.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-1'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT1.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-3'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT2.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-6'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT3.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-9'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT4.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-12'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT5.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-24'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT6.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-60'
      OLDDATE = SY-DATUM
    IMPORTING
      NEWDATE = DT7.
  IF IT_TAB2 IS NOT INITIAL.
    SELECT * FROM WB2_V_VBRK_VBRP2 INTO TABLE IT_WB2_V_VBRK_VBRP2 FOR ALL ENTRIES IN IT_TAB2 WHERE MATNR_I EQ IT_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004')
      AND FKDAT GE DT2.
  ENDIF.
  LOOP AT IT_WB2_V_VBRK_VBRP2 INTO WA_WB2_V_VBRK_VBRP2.
    WA_MAT1-MAT = WA_WB2_V_VBRK_VBRP2-MATNR_I+10(3).
    WA_MAT1-COUNTRY = WA_WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  LOOP AT IT_TAB2 INTO WA_TAB2.
    CLEAR : COUNTRY.
    WA_TAB3-MTART = WA_TAB2-MTART.
    WA_TAB3-WERKS = WA_TAB2-WERKS.
    WA_TAB3-MATNR = WA_TAB2-MATNR.
    WA_TAB3-MAKTX = WA_TAB2-MAKTX.
    WA_TAB3-CHARG = WA_TAB2-CHARG.
    WA_TAB3-CLABS = WA_TAB2-CLABS.
    WA_TAB3-CINSM = WA_TAB2-CINSM.
    WA_TAB3-LGORT = WA_TAB2-LGORT.
    WA_TAB3-ERSDA = WA_TAB2-ERSDA.
    WA_TAB3-HSDAT = WA_TAB2-HSDAT.
    WA_TAB3-VFDAT = WA_TAB2-VFDAT.
    WA_TAB3-VERPR = WA_TAB2-VERPR.
    WA_TAB3-VMPEI = WA_TAB2-VMPEI.
    WA_TAB3-MV = WA_TAB2-MV.
*    wa_tab3-R_MONTH = wa_tab2-R_MONTH.
    WA_TAB3-CLABS3 = WA_TAB2-CLABS3.
    WA_TAB3-MV3 = WA_TAB2-MV3.
    WA_TAB3-CLABS6 = WA_TAB2-CLABS6.
    WA_TAB3-MV6 = WA_TAB2-MV6.
    WA_TAB3-CLABS12 = WA_TAB2-CLABS12.
    WA_TAB3-MV12 = WA_TAB2-MV12.
    WA_TAB3-CLABS12A = WA_TAB2-CLABS12A.
    WA_TAB3-MV12A = WA_TAB2-MV12A.

*    WRITE : / 'A',WA_TAB2-MATNR.
    IF WA_TAB2-MTART EQ 'ZESC' OR WA_TAB2-MTART EQ 'ZESM'.
      SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT1.
      IF SY-SUBRC EQ 0.
*        WRITE : WB2_V_VBRK_VBRP2-INCO2.
        COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
      ELSE.
        SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT2 AND FKDAT LE DT1.
        IF SY-SUBRC EQ 0.
*          WRITE : WB2_V_VBRK_VBRP2-INCO2.
          COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
        ELSE.
          SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT3 AND FKDAT LE DT2.
          IF SY-SUBRC EQ 0.
*            WRITE : WB2_V_VBRK_VBRP2-INCO2.
            COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
          ELSE.
            SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT4 AND FKDAT LE DT3.
            IF SY-SUBRC EQ 0.
*              WRITE : WB2_V_VBRK_VBRP2-INCO2.
              COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
            ELSE.
              SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT5 AND FKDAT LE DT4.
              IF SY-SUBRC EQ 0.
*                WRITE : WB2_V_VBRK_VBRP2-INCO2.
                COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
              ELSE.
                SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT6 AND FKDAT LE DT5.
                IF SY-SUBRC EQ 0.
*                  WRITE : WB2_V_VBRK_VBRP2-INCO2.
                  COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
                ELSE.
                  SELECT SINGLE * FROM WB2_V_VBRK_VBRP2 WHERE MATNR_I EQ WA_TAB2-MATNR AND FKART IN ('Z002','Z003','Z004') AND FKDAT GE DT7 AND FKDAT LE DT6.
                  IF SY-SUBRC EQ 0.
*                    WRITE : WB2_V_VBRK_VBRP2-INCO2.
                    COUNTRY = WB2_V_VBRK_VBRP2-LLAND_AUFT_I.
                  ENDIF.
                ENDIF.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDIF.
      ENDIF.
      SELECT SINGLE * FROM T005T WHERE SPRAS EQ 'EN' AND LAND1 EQ COUNTRY.
      IF SY-SUBRC EQ 0.
        WA_TAB3-LANDX = T005T-LANDX.
      ENDIF.
      IF COUNTRY EQ SPACE.
        READ TABLE IT_MAT1 INTO WA_MAT1 WITH KEY MAT = WA_TAB2-MATNR+10(3).
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM T005T WHERE SPRAS EQ 'EN' AND LAND1 EQ WA_MAT1-COUNTRY.
          IF SY-SUBRC EQ 0.
            WA_TAB3-LANDX = T005T-LANDX.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDIF.


    COLLECT WA_TAB3 INTO IT_TAB3.
    CLEAR WA_TAB3.
  ENDLOOP.


  LOOP AT IT_TAB3 INTO WA_TAB3.
    IF WA_TAB3-MATNR NA 'H'.
      PACK WA_TAB3-MATNR TO WA_TAB3-MATNR.
      PACK WA_TAB3-KUNNR TO WA_TAB3-KUNNR.
      CONDENSE : WA_TAB3-MATNR, WA_TAB3-KUNNR.
      MODIFY IT_TAB3 FROM WA_TAB3 TRANSPORTING MATNR KUNNR.
    ENDIF.
  ENDLOOP.

*  wa_fieldcat-fieldname = 'LAND1'.
*  wa_fieldcat-seltext_l = 'COUNTRY CODE'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'REGIO'.
*  wa_fieldcat-seltext_l = 'REGION'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'KUNAG'.
*  wa_fieldcat-seltext_l = 'CUSTOMER'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'BEZEI'.
*  wa_fieldcat-seltext_l = 'COUNTRY'.
*  append wa_fieldcat to fieldcat.

  WA_FIELDCAT-FIELDNAME = 'LANDX'.
  WA_FIELDCAT-SELTEXT_L = 'COUNTRY'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'MTART'.
  WA_FIELDCAT-SELTEXT_L = 'TYPE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL DESCRIPTION'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LGORT'.
  WA_FIELDCAT-SELTEXT_L = 'STORAGE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CLABS'.
  WA_FIELDCAT-SELTEXT_L = 'UNRESTRICTED STOCK'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
*  WA_FIELDCAT-fieldname = 'CLABS_60'.
*  WA_FIELDCAT-seltext_l = 'UNRESTRICTED QTY BET. 30 TO 60 DAYS'.
*  APPEND WA_FIELDCAT TO FIELDCAT.
*
*  WA_FIELDCAT-fieldname = 'CLABS_90'.
*  WA_FIELDCAT-seltext_l = 'UNRESTRICTED QTY BET. 60 TO 90 DAYS'.
*  APPEND WA_FIELDCAT TO FIELDCAT.
*
*  WA_FIELDCAT-fieldname = 'CLABS_A90'.
*  WA_FIELDCAT-seltext_l = 'UNRESTRICTED QTY ABOVE 90 DAYS'.
*  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VERPR'.
  WA_FIELDCAT-SELTEXT_L = 'MOVING RATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VMPEI'.
  WA_FIELDCAT-SELTEXT_L = 'MOVING RATE PER'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MV'.
  WA_FIELDCAT-SELTEXT_L = 'MOVING VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'HSDAT'.
  WA_FIELDCAT-SELTEXT_L = 'MFG. DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VFDAT'.
  WA_FIELDCAT-SELTEXT_L = 'EXP. DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CLABS3'.
  WA_FIELDCAT-SELTEXT_L = 'QTY UPTO 3 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MV3'.
  WA_FIELDCAT-SELTEXT_L = 'VALUE UPTO 3 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CLABS6'.
  WA_FIELDCAT-SELTEXT_L = 'QTY 3-6 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MV6'.
  WA_FIELDCAT-SELTEXT_L = 'VALUE 3-6 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CLABS12'.
  WA_FIELDCAT-SELTEXT_L = 'QTY 6-12 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MV12'.
  WA_FIELDCAT-SELTEXT_L = 'VALUE 6-12 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CLABS12A'.
  WA_FIELDCAT-SELTEXT_L = 'QTY MORE THAN 12 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MV12A'.
  WA_FIELDCAT-SELTEXT_L = 'VALUE MORE THAN 12 MONTHS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

   WA_FIELDCAT-FIELDNAME = 'CINSM'.
  WA_FIELDCAT-SELTEXT_L = 'QUALITY STOCK'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'PRODUCT STOCK DETAILS'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB3
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.                    "FINISH
*&---------------------------------------------------------------------*
*&      Form  TOP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO+0(35) = 'STOCK DETAILS'.
*  WA_COMMENT-INFO+35(3) = DAYS.
*  WA_COMMENT-INFO+40(4) = 'DAYS'.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'VBELN'.
      SET PARAMETER ID 'VF' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VF03' AND SKIP FIRST SCREEN.
    WHEN 'MATNR'.
      SET PARAMETER ID 'MAT' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM


*TOP-OF-PAGE .
*  WRITE : /1 'TYPE',6 'PLANT',13 'MATERIAL',28 'MATERIAL DESCRIPTION',70 'STORAGE',80 'BATCH',95 'UNRESTRICTED',
*  115 'CREATED ON',128 'DATE OF LAST',141 'Mfg. date',154 'Exp. date'.
*  WRITE : /95 'STOCK',128 'GOODS RECEIPT'.
*  ULINE.
