PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMRP_DATA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMRP_DATA-MATNR .
    FIELD ZMRP_DATA-WERKS .
    FIELD ZMRP_DATA-ZMONTH .
    FIELD ZMRP_DATA-ZYEAR .
    FIELD ZMRP_DATA-STLAL .
    FIELD ZMRP_DATA-USNAM .
    FIELD ZMRP_DATA-CPUDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMRP_DATA-MATNR .
    FIELD ZMRP_DATA-WERKS .
    FIELD ZMRP_DATA-ZMONTH .
    FIELD ZMRP_DATA-ZYEAR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
