PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPROD_INSP_YLD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPROD_INSP_YLD-CHARG .
    FIELD ZPROD_INSP_YLD-WERKS .
    FIELD ZPROD_INSP_YLD-QTY .
    FIELD ZPROD_INSP_YLD-MEINS .
    FIELD ZPROD_INSP_YLD-PERNR .
    FIELD ZPROD_INSP_YLD-CPUDT .
    FIELD ZPROD_INSP_YLD-CPUTM .
    FIELD ZPROD_INSP_YLD-PERNR1 .
    FIELD ZPROD_INSP_YLD-CPUDT1 .
    FIELD ZPROD_INSP_YLD-CPUTM1 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPROD_INSP_YLD-CHARG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
