PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TBC_9025'
  MODULE TBC_9025_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_9025_CHANGE_COL_ATTR.
  LOOP AT   ITAB3
       WITH CONTROL TBC_9025
       CURSOR TBC_9025-CURRENT_LINE.
    MODULE TBC_9025_GET_LINES.
*&SPWIZARD:   MODULE TBC_9025_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_9025.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TBC_9025'
  LOOP AT ITAB3.
    CHAIN.
      FIELD ITAB3-MATNR.
      FIELD ITAB3-MAKTX.
      FIELD ITAB3-BEZEI.
      FIELD ITAB3-NSKSTK.
      FIELD ITAB3-GOASTK.
      FIELD ITAB3-OZRSTK.
      FIELD ITAB3-GHASTK.
      FIELD ITAB3-CNFSTK.
      FIELD ITAB3-TRAME.
      FIELD ITAB3-TOTAL.
      FIELD ITAB3-CREQQTY.
      FIELD ITAB3-RCREQQTY.
      FIELD ITAB3-CBUDQTY.
      FIELD ITAB3-CL1.
      FIELD ITAB3-NREQQTY.
      FIELD ITAB3-RNREQQTY.
      FIELD ITAB3-NBUDQTY.
      FIELD ITAB3-CL2.
      FIELD ITAB3-NNREQQTY.
      FIELD ITAB3-RNNREQQTY.
      FIELD ITAB3-NNBUDQTY.
      FIELD ITAB3-CL3.
      FIELD ITAB3-NNNREQQTY.
      FIELD ITAB3-RNNNREQQTY.
      FIELD ITAB3-NNNBUDQTY.
      FIELD ITAB3-CL4.
       module calc on chain-request.
    endchain.
    FIELD ITAB3-TICK
      MODULE TBC_9025_MARK ON REQUEST.
  ENDLOOP.
  MODULE TBC_9025_USER_COMMAND.
*&SPWIZARD: MODULE TBC_9025_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_9025_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_9025.
