PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPUR_REQ1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPUR_REQ1-BANFN .
    FIELD ZPUR_REQ1-BNFPO .
    FIELD ZPUR_REQ1-PERNR .
    FIELD ZPUR_REQ1-BTRTL .
    FIELD ZPUR_REQ1-PERNRDT .
    FIELD ZPUR_REQ1-CPUTM .
    FIELD ZPUR_REQ1-PERNRTXT .
    FIELD ZPUR_REQ1-TXZ01 .
    FIELD ZPUR_REQ1-MENGE .
    FIELD ZPUR_REQ1-MEINS .
    FIELD ZPUR_REQ1-PREIS .
    FIELD ZPUR_REQ1-PEINH .
    FIELD ZPUR_REQ1-WERKS .
    FIELD ZPUR_REQ1-APPR1 .
    FIELD ZPUR_REQ1-APR1 .
    FIELD ZPUR_REQ1-REJ1 .
    FIELD ZPUR_REQ1-APPR1DT .
    FIELD ZPUR_REQ1-APPR1TM .
    FIELD ZPUR_REQ1-APPR1TXT .
    FIELD ZPUR_REQ1-APPR2 .
    FIELD ZPUR_REQ1-APR2 .
    FIELD ZPUR_REQ1-REJ2 .
    FIELD ZPUR_REQ1-APPR2DT .
    FIELD ZPUR_REQ1-APPR2TM .
    FIELD ZPUR_REQ1-APPR2TXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPUR_REQ1-BANFN .
    FIELD ZPUR_REQ1-BNFPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
