*&---------------------------------------------------------------------*
*& Report  ZDELIVERY_CHALLAN
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZDELIVERY_CHALLAN.

TABLES : MSEG,
         MARC,
         MAKT,
         T001W,
         ZRM05,
         MKPF,
         MCHA.

DATA : IT_MSEG  TYPE TABLE OF MSEG,
       WA_MSEG  TYPE MSEG,
       IT_MSEG1 TYPE TABLE OF MSEG,
       WA_MSEG1 TYPE MSEG,
       IT_MCHA  TYPE TABLE OF MCHA,
       WA_MCHA  TYPE MCHA,
       IT_MKPF  TYPE TABLE OF MKPF,
       WA_MKPF  TYPE MKPF,
       IT_MSEG2 TYPE TABLE OF MSEG,
       WA_MSEG2 TYPE MSEG,
       IT_EKPO  TYPE TABLE OF EKPO,
       WA_EKPO  TYPE EKPO,
       IT_EKBE  TYPE TABLE OF EKBE,
       WA_EKBE  TYPE EKBE.

TYPES : BEGIN OF ITAB1,
          WERKS TYPE MSEG-WERKS,
          MATNR TYPE MSEG-MATNR,
          CHARG TYPE MSEG-CHARG,
          MENGE TYPE MSEG-MENGE,
          MEINS TYPE MSEG-MEINS,
          VFDAT TYPE MSEG-VFDAT,
          STEUC TYPE MARC-STEUC,
          MAKTX TYPE MAKT-MAKTX,
          SGTXT TYPE MSEG-SGTXT,
        END OF ITAB1.
TYPES: BEGIN OF STR1,
         LGORT TYPE MSEG-LGORT,
       END OF STR1.
DATA : IT_TAB1 TYPE TABLE OF ITAB1,
       WA_TAB1 TYPE ITAB1,
       IT_STR1 TYPE TABLE OF STR1,
       WA_STR1 TYPE STR1.
DATA : STR TYPE MSEG-LGORT.
DATA : LICHA TYPE MCHA-LICHA.

DATA : WERKS TYPE MSEG-WERKS.
DATA : P_KUNNR LIKE T001W-KUNNR.
DATA : P_ADRNR LIKE T001W-ADRNR,
       P_REGIO LIKE T001W-REGIO.
DATA : P_ADRNR1 LIKE KNA1-ADRNR,
       P_STCD3  LIKE KNA1-STCD3,
       BKTXT    TYPE MKPF-BKTXT,
       DL       LIKE ADRC-EXTENSION1.
DATA : P_NAME1      LIKE ADRC-NAME1,
       P_NAME2      LIKE ADRC-NAME2,
       P_NAME3      LIKE ADRC-NAME3,
       P_NAME4      LIKE ADRC-NAME4,
       P_EXTENSION1 TYPE ADRC-EXTENSION1.

DATA : TEXT1(220) TYPE C.
DATA : TOTQTY    TYPE MSEG-MENGE,
       VBELN(10) TYPE N,
       FKDAT     TYPE MKPF-BUDAT.
SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
PARAMETERS: MBLNR   TYPE MSEG-MBLNR OBLIGATORY,
            YEAR(4) TYPE C OBLIGATORY.
SELECTION-SCREEN END OF BLOCK MERKMALE1 .

START-OF-SELECTION.

  SELECT * FROM MSEG INTO TABLE IT_MSEG WHERE MBLNR EQ MBLNR AND MJAHR EQ YEAR AND SHKZG EQ 'S'.
  SELECT * FROM MSEG INTO TABLE IT_MSEG1 WHERE MBLNR EQ MBLNR AND MJAHR EQ YEAR AND SHKZG EQ 'H'.

  SELECT SINGLE * FROM ZRM05 WHERE MBLNR EQ MBLNR AND MJAHR EQ YEAR.
  IF SY-SUBRC EQ 0.
    VBELN = ZRM05-VBELN.
  ELSE.
    MESSAGE 'MAINTAIN CHALLAN NUMBER FOR DOCUMENT NUMBER IN ''ZRM05''' TYPE 'E'.
  ENDIF.
  SELECT SINGLE * FROM MKPF WHERE MBLNR EQ MBLNR AND MJAHR EQ YEAR.
  IF SY-SUBRC EQ 0.
    FKDAT = MKPF-BUDAT.
  ENDIF.

  SORT IT_MSEG1 BY LGORT.
  DELETE ADJACENT DUPLICATES FROM IT_MSEG1 COMPARING LGORT.
  LOOP AT IT_MSEG1 INTO WA_MSEG1.
    CONCATENATE ' ' WA_MSEG1-LGORT INTO STR.
  ENDLOOP.
*  write : / 'loc',str.
*  ******************************
  IF IT_MSEG IS NOT INITIAL.
    SELECT * FROM MCHA INTO TABLE IT_MCHA FOR ALL ENTRIES IN IT_MSEG WHERE CHARG EQ IT_MSEG-CHARG.
    IF SY-SUBRC EQ 0.
      SELECT * FROM MKPF INTO TABLE IT_MKPF FOR ALL ENTRIES IN IT_MCHA WHERE BUDAT EQ IT_MCHA-LWEDT AND VGART EQ 'WE'.
      IF SY-SUBRC EQ 0.
        SELECT * FROM MSEG INTO TABLE IT_MSEG2 FOR ALL ENTRIES IN  IT_MKPF WHERE MBLNR = IT_MKPF-MBLNR AND MJAHR EQ IT_MKPF-MJAHR AND BWART EQ '101'
          AND LIFNR NE SPACE.
*          WERKS IN  P_WERKS .
        IF SY-SUBRC EQ 0.
          SELECT * FROM EKPO INTO TABLE IT_EKPO FOR ALL ENTRIES IN IT_MSEG2 WHERE EBELN = IT_MSEG2-EBELN AND EBELP = IT_MSEG2-EBELP.
          SELECT * FROM EKBE INTO TABLE IT_EKBE FOR ALL ENTRIES IN IT_MSEG2 WHERE EBELN = IT_MSEG2-EBELN AND EBELP = IT_MSEG2-EBELP AND BEWTP
            IN ('Q','R') AND  LFBNR EQ IT_MSEG2-MBLNR.
        ENDIF.
      ENDIF.
    ENDIF.
  ENDIF.
***********************
  LOOP AT IT_MSEG INTO WA_MSEG.
********* MANUFACURER'S NAME**********
*    select single * from mseg where
    READ TABLE IT_MSEG2 INTO WA_MSEG2 WITH KEY MATNR = WA_MSEG-MATNR CHARG = WA_MSEG-CHARG.
    IF SY-SUBRC EQ 0.
      WA_TAB1-SGTXT = WA_MSEG2-SGTXT.
    ENDIF.
    WA_TAB1-MATNR = WA_MSEG-MATNR.
    WA_TAB1-WERKS = WA_MSEG-WERKS.
    WA_TAB1-CHARG = WA_MSEG-CHARG.
    WA_TAB1-MENGE = WA_MSEG-MENGE.
    TOTQTY = TOTQTY + WA_MSEG-MENGE.
    WA_TAB1-MEINS = WA_MSEG-MEINS.
    WA_TAB1-VFDAT = WA_MSEG-VFDAT.
    SELECT SINGLE * FROM MARC WHERE MATNR EQ WA_MSEG-MATNR AND WERKS EQ WA_MSEG-WERKS.
    IF SY-SUBRC EQ 0.
      WA_TAB1-STEUC = MARC-STEUC.
    ENDIF.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MSEG-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_TAB1-MAKTX = MAKT-MAKTX.
    ENDIF.
    WERKS = WA_MSEG-WERKS.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
  ENDLOOP.


  IF WERKS EQ '1000'.
    IF MKPF-BUDAT GT '20200504'.
      TEXT1 = 'Wholesale Licence No- 20B/366610, 21B/366611'.
    ELSE.
      TEXT1 = 'Wholesale Licence No- 20B/MH/NZ-1/1399, 21B/MH/NZ-1/1329'.
    ENDIF.
  ELSEIF WERKS EQ '1001'.
    TEXT1 = 'Wholesale Licence No- GA-SGO-5287,  GA-SGO-5288 dated 22.04.2016'.
  ENDIF.

  CALL FUNCTION 'OPEN_FORM'
    EXPORTING
*     APPLICATION                 = 'TX'
*     ARCHIVE_INDEX               =
*     ARCHIVE_PARAMS              =
      DEVICE                      = 'PRINTER'
      DIALOG                      = 'X'
*     FORM                        = 'Z_TRF_INVOICE_1 '
      LANGUAGE                    = SY-LANGU
*     OPTIONS                     =
*     MAIL_SENDER                 =
*     MAIL_RECIPIENT              =
*     MAIL_APPL_OBJECT            =
*     RAW_DATA_INTERFACE          = '*'
*     SPONUMIV                    =
* IMPORTING
*     LANGUAGE                    =
*     NEW_ARCHIVE_PARAMS          =
*     RESULT                      =
    EXCEPTIONS
      CANCELED                    = 1
      DEVICE                      = 2
      FORM                        = 3
      OPTIONS                     = 4
      UNCLOSED                    = 5
      MAIL_OPTIONS                = 6
      ARCHIVE_ERROR               = 7
      INVALID_FAX_NUMBER          = 8
      MORE_PARAMS_NEEDED_IN_BATCH = 9
      SPOOL_ERROR                 = 10
      CODEPAGE                    = 11
      OTHERS                      = 12.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'START_FORM'
    EXPORTING
*     FORM        = 'ZINV_NEP2_11'
      FORM        = 'ZRM05'
      LANGUAGE    = SY-LANGU
    EXCEPTIONS
      FORM        = 1
      FORMAT      = 2
      UNENDED     = 3
      UNOPENED    = 4
      UNUSED      = 5
      SPOOL_ERROR = 6
      CODEPAGE    = 7
      OTHERS      = 8.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


  SELECT SINGLE KUNNR ADRNR REGIO FROM T001W INTO (P_KUNNR,P_ADRNR,P_REGIO) WHERE WERKS EQ WERKS.
  SELECT SINGLE NAME1 NAME2 NAME3 NAME4 FROM ADRC INTO (P_NAME1,P_NAME2,P_NAME3,P_NAME4) WHERE ADDRNUMBER EQ P_ADRNR.
  SELECT SINGLE ADRNR STCD3 FROM KNA1 INTO (P_ADRNR1,P_STCD3) WHERE KUNNR EQ P_KUNNR.
  SELECT SINGLE EXTENSION1 FROM ADRC INTO DL WHERE ADDRNUMBER EQ P_ADRNR1.
  SELECT SINGLE BKTXT FROM MKPF INTO BKTXT WHERE MBLNR EQ MBLNR AND MJAHR EQ YEAR.

  CALL FUNCTION 'WRITE_FORM'
    EXPORTING
      WINDOW = 'INFO1'.

  LOOP AT IT_TAB1 INTO WA_TAB1.
    CLEAR : LICHA.
    SELECT SINGLE * FROM MCHA WHERE MATNR EQ WA_TAB1-MATNR AND WERKS EQ WA_TAB1-WERKS AND CHARG EQ WA_TAB1-CHARG AND LICHA NE SPACE.
    IF SY-SUBRC EQ 0.
      LICHA = MCHA-LICHA.
    ENDIF.

    CALL FUNCTION 'WRITE_FORM'
      EXPORTING
        ELEMENT = 'ITEM_VALUES'
      EXCEPTIONS
        OTHERS  = 1.
    IF SY-SUBRC NE 0.
    ENDIF.
  ENDLOOP.

*call function 'WRITE_FORM'
*  exporting
*    window  = 'FOOTER'
*    element = 'PAGE_NO'.

  CALL FUNCTION 'WRITE_FORM'
    EXPORTING
      WINDOW  = 'WINDOW3'
      ELEMENT = 'PAGE_NO1'.

  CALL FUNCTION 'WRITE_FORM'
    EXPORTING
      WINDOW  = 'WINDOW4'
      ELEMENT = 'PAGE_NO2'.

  CALL FUNCTION 'END_FORM'
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SPOOL_ERROR              = 3
      CODEPAGE                 = 4
      OTHERS                   = 5.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'CLOSE_FORM'
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SEND_ERROR               = 3
      SPOOL_ERROR              = 4
      CODEPAGE                 = 5
      OTHERS                   = 6.
  IF SY-SUBRC <> 0.
  ENDIF.
