*&---------------------------------------------------------------------*
*& Report  ZRM_BUDGET
*&*DEVELOPED BY JYOTSNA 10.5.22
******
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRM_BUDGET_A1.

TABLES : MARA,
         ZRM_BUDGET,
         MAKT,
         EKKO,
         EKPO.

TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV,
      L_GLAY      TYPE LVC_S_GLAY.

TYPES : BEGIN OF ITAB1,
          MJAHR   TYPE MSEG-MJAHR,
          MATNR   TYPE MSEG-MATNR,
          BUDGET  TYPE ZRM_BUDGET-BUDGET,
          CNT(20) TYPE C,
        END OF ITAB1.

TYPES : BEGIN OF DISP1,
          MJAHR      TYPE MSEG-MJAHR,
          MATNR      TYPE MSEG-MATNR,
          BUDGET     TYPE ZRM_BUDGET-BUDGET,
          MAKTX(100) TYPE C,
          USNAM      TYPE SY-UNAME,
          CPUDT      TYPE SY-DATUM,
          NETPR      TYPE EKPO-NETPR,
          PEINH      TYPE EKPO-PEINH,
          EBELN      TYPE EKPO-EBELN,
          EBELP      TYPE EKPO-EBELP,
          AEDAT      TYPE EKKO-AEDAT,
          DIFF       TYPE P DECIMALS 2,
          WERKS      TYPE EKPO-WERKS,
          MEINS      TYPE EKPO-MEINS,
        END OF DISP1.

DATA: IT_TAB1  TYPE TABLE OF ITAB1,
      WA_TAB1  TYPE ITAB1,
      IT_DISP1 TYPE TABLE OF DISP1,
      WA_DISP1 TYPE DISP1,
      IT_DISP2 TYPE TABLE OF DISP1,
      WA_DISP2 TYPE DISP1.

DATA : MAKTX1(40) TYPE C,
       MAKTX2(40) TYPE C,
       NORMT      TYPE MARA-NORMT,
       MAKTX(100) TYPE C.

DATA: NET  TYPE P DECIMALS 2,
      IMP1 TYPE P DECIMALS 2.
DATA : BUDGET TYPE ZRM_BUDGET-BUDGET.
DATA:  ZRM_BUDGET_WA TYPE  ZRM_BUDGET.
DATA: IT_ZRM_BUDGET TYPE TABLE OF ZRM_BUDGET,
      WA_ZRM_BUDGET TYPE ZRM_BUDGET,
      IT_EKPO       TYPE TABLE OF EKPO,
      WA_EKPO       TYPE EKPO,
      IT_EKKO       TYPE TABLE OF EKKO,
      WA_EKKO       TYPE EKKO.

DATA: YEAR(4) TYPE C,
      DATE1   TYPE SY-DATUM.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
PARAMETERS : MJAHR TYPE MSEG-MJAHR OBLIGATORY.
PARAMETERS : R1 RADIOBUTTON GROUP R1,
             R2 RADIOBUTTON GROUP R1,
             R3 RADIOBUTTON GROUP R1.
SELECT-OPTIONS : IMPMATNR FOR EKPO-MATNR,
IMPDT FOR SY-DATUM.
SELECT-OPTIONS : IMPLT FOR EKPO-WERKS.
SELECTION-SCREEN END OF BLOCK MERKMALE1.

INITIALIZATION.
  G_REPID = SY-REPID.


START-OF-SELECTION .

  IF R1 EQ 'X'.
    PERFORM UPDBUD.
  ELSEIF R2 EQ 'X'.
    PERFORM DISPLAY.
  ELSEIF R3 EQ 'X'.
    IF IMPDT IS INITIAL.
      MESSAGE 'ENTER PO DATE TO CHECK PRICE IMPACT' TYPE 'E'.
    ENDIF.
    PERFORM IMPACT.
  ENDIF.
*&---------------------------------------------------------------------*
*&      Form  UPDBUD
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM UPDBUD .
  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 1.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 2.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 3.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 4.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 5.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 6.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 7.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 8.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 9.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 10.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 11.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 12.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 13.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 14.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 15.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 16.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 17.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 18.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 19.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.

  WA_TAB1-MJAHR = MJAHR.
  WA_TAB1-MATNR = SPACE.
  WA_TAB1-CNT = 20.
  COLLECT WA_TAB1 INTO IT_TAB1.
  CLEAR WA_TAB1.



  WA_FIELDCAT-FIELDNAME = 'MJAHR'.
  WA_FIELDCAT-SELTEXT_L = 'YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  WA_FIELDCAT-EDIT = 'X'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDGET'.
  WA_FIELDCAT-SELTEXT_L = 'BUDGTED VALUE'.
  WA_FIELDCAT-EDIT = 'X'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'YEARLY RAW MATERIAL BUDGET CODE'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = 'STATUS'
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         = L_GLAY
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.

FORM USER_COMM USING UCOMM LIKE SY-UCOMM SELFIELD TYPE SLIS_SELFIELD.
  CASE SY-UCOMM. "SELFIELD-FIELDNAME.

    WHEN '&DATA_SAVE'.

      IF R1 EQ 'X'.
        PERFORM UPDCOATED.
      ENDIF.


    WHEN OTHERS.
  ENDCASE.

ENDFORM.

FORM TOP.
  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.

  WA_COMMENT-INFO = 'YEARLY RAW MATERIAL BUDGET'.

*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT.
*     I_LOGO                   = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID       =
*     I_ALV_FORM               =
  CLEAR COMMENT.
ENDFORM.                    "TOP
*&---------------------------------------------------------------------*
*&      Form  DISPLAY
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DISPLAY .
  SELECT * FROM ZRM_BUDGET INTO TABLE IT_ZRM_BUDGET WHERE MJAHR EQ MJAHR.

  IF IT_ZRM_BUDGET IS INITIAL.
    MESSAGE 'NO DATA' TYPE 'E'.
  ENDIF.

  LOOP AT IT_ZRM_BUDGET INTO WA_ZRM_BUDGET.
    WA_DISP1-MJAHR = WA_ZRM_BUDGET-MJAHR.
    WA_DISP1-MATNR = WA_ZRM_BUDGET-MATNR.

    CLEAR : MAKTX1, MAKTX2, MAKTX, NORMT.
    SELECT SINGLE * FROM MAKT WHERE SPRAS EQ 'EN' AND MATNR EQ  WA_ZRM_BUDGET-MATNR.
    IF SY-SUBRC EQ 0.
      MAKTX1 = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM MAKT WHERE SPRAS EQ 'Z1' AND MATNR EQ  WA_ZRM_BUDGET-MATNR.
    IF SY-SUBRC EQ 0.
      MAKTX2 = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE MATNR EQ  WA_ZRM_BUDGET-MATNR.
    IF SY-SUBRC EQ 0.
      NORMT = MARA-NORMT.
    ENDIF.
    CONCATENATE MAKTX1 MAKTX2 NORMT INTO MAKTX SEPARATED BY SPACE.


    WA_DISP1-MAKTX = MAKTX.
    WA_DISP1-BUDGET = WA_ZRM_BUDGET-BUDGET.
    WA_DISP1-USNAM = WA_ZRM_BUDGET-USNAM.
    WA_DISP1-CPUDT = WA_ZRM_BUDGET-CPUDT.

    SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_ZRM_BUDGET-MATNR.
    IF SY-SUBRC EQ 0.
      WA_DISP1-MEINS = MARA-MEINS.
    ENDIF.

    COLLECT WA_DISP1 INTO IT_DISP1.
    CLEAR WA_DISP1.
  ENDLOOP.

  LOOP AT IT_DISP1 INTO WA_DISP1.
    PACK WA_DISP1-MATNR TO WA_DISP1-MATNR.
    CONDENSE WA_DISP1-MATNR.
    MODIFY IT_DISP1 FROM WA_DISP1 TRANSPORTING MATNR.
  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'MJAHR'.
  WA_FIELDCAT-SELTEXT_L = 'BUDGET YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MEINS'.
  WA_FIELDCAT-SELTEXT_L = 'UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDGET'.
  WA_FIELDCAT-SELTEXT_L = 'BUDGETED VALUE PER UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'USNAM'.
  WA_FIELDCAT-SELTEXT_L = 'MAINTAINED BY'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CPUDT'.
  WA_FIELDCAT-SELTEXT_L = 'MAINTAINED ON'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'RAW MATERIAL BUDGET DATA FOR THE YEAR'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM1'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_DISP1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.

FORM USER_COMM1 USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'MATNR'.
      SET PARAMETER ID 'MAT' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'MM03' AND SKIP FIRST SCREEN.
    WHEN 'EBELN'.
      SET PARAMETER ID 'BES' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'ME23N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM
*&---------------------------------------------------------------------*
*&      Form  UPDCOATED
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM UPDCOATED .
*  BREAK-POINT.
  LOOP AT IT_TAB1 INTO WA_TAB1 WHERE MATNR GT 0 AND BUDGET GT 0.
    SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_TAB1-MATNR AND MTART EQ 'ZROH'.
    IF SY-SUBRC EQ 4.
      MESSAGE 'CHECK RAW MATERIAL CODE' TYPE 'E'.
    ENDIF.
    SELECT SINGLE * FROM ZRM_BUDGET WHERE MJAHR EQ WA_TAB1-MJAHR AND MATNR EQ WA_TAB1-MATNR.
    IF SY-SUBRC EQ 0.
      MESSAGE 'BUDGET IS ALREADY UPDATED FOR THIS MATERIAL' TYPE 'E'.
    ENDIF.
  ENDLOOP.


  LOOP AT IT_TAB1 INTO WA_TAB1 WHERE MATNR GT 0 AND BUDGET GT 0.
    ZRM_BUDGET_WA-MJAHR = WA_TAB1-MJAHR.
    ZRM_BUDGET_WA-MATNR = WA_TAB1-MATNR.
    ZRM_BUDGET_WA-BUDGET = WA_TAB1-BUDGET.
    ZRM_BUDGET_WA-USNAM = SY-UNAME.
    ZRM_BUDGET_WA-CPUDT = SY-DATUM.
    MODIFY ZRM_BUDGET FROM ZRM_BUDGET_WA.
    CLEAR ZRM_BUDGET_WA.
  ENDLOOP.


  IF SY-SUBRC EQ 0.
    MESSAGE 'DATA SAVED' TYPE 'I'.
  ENDIF.
  LEAVE TO SCREEN 0.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  IMPACT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM IMPACT .
  SELECT * FROM ZRM_BUDGET INTO TABLE IT_ZRM_BUDGET WHERE MJAHR EQ MJAHR.

  IF IT_ZRM_BUDGET IS INITIAL.
    MESSAGE 'NO DATA' TYPE 'I'.
  ENDIF.
  YEAR = MJAHR - 1.
  DATE1+6(2) = '01'.
  DATE1+4(2) = '04'.
  DATE1+0(4) = YEAR.

*  IF IT_ZRM_BUDGET IS NOT INITIAL.
  SELECT * FROM EKKO INTO TABLE IT_EKKO WHERE BUKRS EQ 'BCLL' AND BSART EQ 'ZL' AND AEDAT IN IMPDT.
  IF SY-SUBRC EQ 0.
    SELECT * FROM EKPO INTO TABLE IT_EKPO FOR ALL ENTRIES IN IT_EKKO WHERE EBELN EQ IT_EKKO-EBELN AND MATNR IN IMPMATNR AND WERKS IN IMPLT AND loekz eq space.
  ENDIF.


*  SORT IT_EKPO DESCENDING BY AEDAT.
  LOOP AT IT_EKPO INTO WA_EKPO.
    CLEAR : BUDGET.
    READ TABLE IT_EKKO INTO WA_EKKO WITH KEY EBELN = WA_EKPO-EBELN.
    IF SY-SUBRC EQ 0.
      WA_DISP1-MATNR = WA_EKPO-MATNR.
      WA_DISP1-WERKS = WA_EKPO-WERKS.
      WA_DISP1-MEINS = WA_EKPO-MEINS.
      WA_DISP1-NETPR = WA_EKPO-NETPR.
      WA_DISP1-PEINH = WA_EKPO-PEINH.
      WA_DISP1-EBELN = WA_EKPO-EBELN.
      WA_DISP1-EBELP = WA_EKPO-EBELP.
      WA_DISP1-AEDAT = WA_EKKO-AEDAT.
      READ TABLE IT_ZRM_BUDGET INTO WA_ZRM_BUDGET WITH KEY MATNR = WA_EKPO-MATNR.
      IF SY-SUBRC EQ 0.
        WA_DISP1-MJAHR = WA_ZRM_BUDGET-MJAHR.
        WA_DISP1-BUDGET = WA_ZRM_BUDGET-BUDGET.
        BUDGET = WA_ZRM_BUDGET-BUDGET.
        WA_DISP1-USNAM = WA_ZRM_BUDGET-USNAM.
        WA_DISP1-CPUDT = WA_ZRM_BUDGET-CPUDT.
      ENDIF.
      CLEAR : MAKTX1, MAKTX2, MAKTX, NORMT.
      SELECT SINGLE * FROM MAKT WHERE SPRAS EQ 'EN' AND MATNR EQ WA_EKPO-MATNR.
      IF SY-SUBRC EQ 0.
        MAKTX1 = MAKT-MAKTX.
      ENDIF.
      SELECT SINGLE * FROM MAKT WHERE SPRAS EQ 'Z1' AND MATNR EQ  WA_EKPO-MATNR.
      IF SY-SUBRC EQ 0.
        MAKTX2 = MAKT-MAKTX.
      ENDIF.
      SELECT SINGLE * FROM MARA WHERE MATNR EQ  WA_EKPO-MATNR.
      IF SY-SUBRC EQ 0.
        NORMT = MARA-NORMT.
      ENDIF.
      CONCATENATE MAKTX1 MAKTX2 NORMT INTO MAKTX SEPARATED BY SPACE.
      WA_DISP1-MAKTX = MAKTX.

      CLEAR : NET.
*    READ TABLE IT_EKPO INTO WA_EKPO WITH KEY MATNR = WA_ZRM_BUDGET-MATNR..
*    IF SY-SUBRC EQ 0.

      IF BUDGET GT 0.
        CLEAR : NET.
        NET = WA_EKPO-NETPR / WA_EKPO-PEINH.
        IMP1 =  BUDGET - NET.
        WA_DISP1-DIFF = IMP1 * wa_ekpo-menge.
      ENDIF.

      IF WA_DISP1-MEINS EQ SPACE.
        SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_EKPO-MATNR.
        IF SY-SUBRC EQ 0.
          WA_DISP1-MEINS = MARA-MEINS.
        ENDIF.
      ENDIF.


      COLLECT WA_DISP1 INTO IT_DISP1.
      CLEAR WA_DISP1.
    ENDIF.
  ENDLOOP.



  LOOP AT IT_DISP1 INTO WA_DISP1.
    PACK WA_DISP1-MATNR TO WA_DISP1-MATNR.
    CONDENSE WA_DISP1-MATNR.
    MODIFY IT_DISP1 FROM WA_DISP1 TRANSPORTING MATNR.
  ENDLOOP.

  WA_FIELDCAT-FIELDNAME = 'MJAHR'.
  WA_FIELDCAT-SELTEXT_L = 'YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PO PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.
*
  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MEINS'.
  WA_FIELDCAT-SELTEXT_L = 'UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'MATERIAL NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BUDGET'.
  WA_FIELDCAT-SELTEXT_L = 'BUDGETED VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETPR'.
  WA_FIELDCAT-SELTEXT_L = 'PRICE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PEINH'.
  WA_FIELDCAT-SELTEXT_L = 'PRICE PER UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELN'.
  WA_FIELDCAT-SELTEXT_L = 'PURCHASE ORDER'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELP'.
  WA_FIELDCAT-SELTEXT_L = 'PO IETM NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AEDAT'.
  WA_FIELDCAT-SELTEXT_L = 'PO DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DIFF'.
  WA_FIELDCAT-SELTEXT_L = 'DIFFERENCE PER UNIT'.
  APPEND WA_FIELDCAT TO FIELDCAT.
  CLEAR WA_FIELDCAT.



  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'RAW MATERIAL BUDGET & IMPACT'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM1'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_DISP1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.



ENDFORM.
