PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST5 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST5-MATNR .
    FIELD ZTP_COST5-LIFNR .
    FIELD ZTP_COST5-BUDAT .
    FIELD ZTP_COST5-CC .
    FIELD ZTP_COST5-PC .
    FIELD ZTP_COST5-SGTXT .
    FIELD ZTP_COST5-UNAME .
    FIELD ZTP_COST5-CPUDT .
    FIELD ZTP_COST5-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST5-MATNR .
    FIELD ZTP_COST5-LIFNR .
    FIELD ZTP_COST5-BUDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
