PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST14 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST14-VBELN .
    FIELD ZTP_COST14-GJAHR .
    FIELD ZTP_COST14-PROD .
    FIELD ZTP_COST14-PRODAPR .
    FIELD ZTP_COST14-PRODREJ .
    FIELD ZTP_COST14-PURAPPROVER .
    FIELD ZTP_COST14-PRODDT .
    FIELD ZTP_COST14-PRODTM .
    FIELD ZTP_COST14-PRODTXT .
    FIELD ZTP_COST14-PUR .
    FIELD ZTP_COST14-PURAPR .
    FIELD ZTP_COST14-PURREJ .
    FIELD ZTP_COST14-PURDT .
    FIELD ZTP_COST14-PURTM .
    FIELD ZTP_COST14-PURTXT .
    FIELD ZTP_COST14-ACCT .
    FIELD ZTP_COST14-ACCTAPR .
    FIELD ZTP_COST14-ACCTREJ .
    FIELD ZTP_COST14-ACCAPPROVER .
    FIELD ZTP_COST14-ACCTDT .
    FIELD ZTP_COST14-ACCTTM .
    FIELD ZTP_COST14-ACCTTXT .
    FIELD ZTP_COST14-FI .
    FIELD ZTP_COST14-FIAPR .
    FIELD ZTP_COST14-FIREJ .
    FIELD ZTP_COST14-FIDT .
    FIELD ZTP_COST14-FITM .
    FIELD ZTP_COST14-FITXT .
    FIELD ZTP_COST14-FINAL .
    FIELD ZTP_COST14-FINALAPR .
    FIELD ZTP_COST14-FINALREJ .
    FIELD ZTP_COST14-FINALDT .
    FIELD ZTP_COST14-FINALTM .
    FIELD ZTP_COST14-FINALTXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST14-VBELN .
    FIELD ZTP_COST14-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
