PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST12 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST12-GJAHR .
    FIELD ZTP_COST12-VBELN .
    FIELD ZTP_COST12-POSNR .
    FIELD ZTP_COST12-IDNRK .
    FIELD ZTP_COST12-LIFNR .
    FIELD ZTP_COST12-MENGE .
    FIELD ZTP_COST12-RATE .
    FIELD ZTP_COST12-GSTRATE .
    FIELD ZTP_COST12-GSTVAL .
    FIELD ZTP_COST12-FRTPER .
    FIELD ZTP_COST12-FRTRATE .
    FIELD ZTP_COST12-FRTVAL .
    FIELD ZTP_COST12-V1 .
    FIELD ZTP_COST12-V2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST12-GJAHR .
    FIELD ZTP_COST12-VBELN .
    FIELD ZTP_COST12-POSNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
