PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST1-MATNR .
    FIELD ZTP_COST1-FGLIFNR .
    FIELD ZTP_COST1-POSNR .
    FIELD ZTP_COST1-BUDAT .
    FIELD ZTP_COST1-RPLIFNR .
    FIELD ZTP_COST1-NETPR .
    FIELD ZTP_COST1-PEINH .
    FIELD ZTP_COST1-SGTXT .
    FIELD ZTP_COST1-UZEIT .
    FIELD ZTP_COST1-UNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST1-MATNR .
    FIELD ZTP_COST1-FGLIFNR .
    FIELD ZTP_COST1-POSNR .
    FIELD ZTP_COST1-BUDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
