PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST4 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST4-MATNR .
    FIELD ZTP_COST4-LIFNR .
    FIELD ZTP_COST4-BUDAT .
    FIELD ZTP_COST4-PERCNT .
    FIELD ZTP_COST4-SGTXT .
    FIELD ZTP_COST4-UNAME .
    FIELD ZTP_COST4-CPUDT .
    FIELD ZTP_COST4-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST4-MATNR .
    FIELD ZTP_COST4-LIFNR .
    FIELD ZTP_COST4-BUDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
