PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST11 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST11-GJAHR .
    FIELD ZTP_COST11-VBELN .
    FIELD ZTP_COST11-WERKS .
    FIELD ZTP_COST11-MATNR .
    FIELD ZTP_COST11-FGLIFNR .
    FIELD ZTP_COST11-STLAL .
    FIELD ZTP_COST11-R2 .
    FIELD ZTP_COST11-P2 .
    FIELD ZTP_COST11-RP1 .
    FIELD ZTP_COST11-M1 .
    FIELD ZTP_COST11-CCPC .
    FIELD ZTP_COST11-ANAVAL .
    FIELD ZTP_COST11-ANART .
    FIELD ZTP_COST11-GSTVAL1 .
    FIELD ZTP_COST11-NET .
    FIELD ZTP_COST11-MARGIN .
    FIELD ZTP_COST11-FGGST .
    FIELD ZTP_COST11-BMENG .
    FIELD ZTP_COST11-BATSZ .
    FIELD ZTP_COST11-RMYLD .
    FIELD ZTP_COST11-PMYLD .
    FIELD ZTP_COST11-CPUDT .
    FIELD ZTP_COST11-UNAME .
    FIELD ZTP_COST11-UZEIT .
    FIELD ZTP_COST11-SUBJECT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST11-GJAHR .
    FIELD ZTP_COST11-VBELN .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
