PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST3 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST3-MATNR .
    FIELD ZTP_COST3-FGLIFNR .
    FIELD ZTP_COST3-BUDAT .
    FIELD ZTP_COST3-FRTVAL .
    FIELD ZTP_COST3-SGTXT .
    FIELD ZTP_COST3-UNAME .
    FIELD ZTP_COST3-CPUDT .
    FIELD ZTP_COST3-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST3-MATNR .
    FIELD ZTP_COST3-FGLIFNR .
    FIELD ZTP_COST3-BUDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
