PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTP_COST13 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTP_COST13-VBELN .
    FIELD ZTP_COST13-GJAHR .
    FIELD ZTP_COST13-SUBJECT .
    FIELD ZTP_COST13-WERKS .
    FIELD ZTP_COST13-MATNR .
    FIELD ZTP_COST13-MAKTX .
    FIELD ZTP_COST13-LIFNR .
    FIELD ZTP_COST13-NAME1 .
    FIELD ZTP_COST13-CPUDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTP_COST13-VBELN .
    FIELD ZTP_COST13-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
