*&---------------------------------------------------------------------*
*& Include          ZXCLFU02
*&---------------------------------------------------------------------*
*"  IMPORTING
*"     VALUE(I_RMCLF) LIKE  RMCLF STRUCTURE  RMCLF
*"     VALUE(I_APPL) LIKE  RMCLF-KREUZ
*"     VALUE(I_CALLED) TYPE  C OPTIONAL
*"  EXPORTING
*"     VALUE(E_ACTIVE) LIKE  RMCLF-KREUZ
*"     VALUE(E_OK_CODE) LIKE  SY-UCOMM
*"     VALUE(E_DYNPRO) LIKE  SY-DYNNR
*"  TABLES
*"      T_ALLKSSK STRUCTURE  RMCLKSSK
*"      T_ALLAUSP STRUCTURE  RMCLAUSP
*"      T_DELCL STRUCTURE  RMCLDEL
*"      T_DELOB STRUCTURE  RMCLDOB
FIELD-SYMBOLS: <F1> TYPE ANY.
DATA: LS_GOITEM TYPE GOITEM,
      LS_GOHEAD TYPE GOHEAD.
DATA: LV_ATNAM TYPE ATNAM,
      lv_ATINN TYPE ATINN,
      LV_ATWRT TYPE ATWRT,
      LV_REJ   TYPE QBEWERTUNG,
      LV_BUKRS TYPE BUKRS,
      LV_GJAHR TYPE GJAHR,
      LV_SDAT  TYPE SY-DATuM,
      LV_EDAT  TYPE SY-DATUM.

*IF SY-UNAME = 'CTPLGW'.

ASSIGN ('(SAPLMIGO)GOITEM') TO <F1>.
IF <F1> IS ASSIGNED.
  MOVE-CORRESPONDING <F1> TO LS_GOITEM.
ENDIF.
UNASSIGN <F1>.

CHECK LS_GOITEM-BWART = '101'.  "Do not do further if it is not 101

ASSIGN ('(SAPLMIGO)GOHEAD') TO <F1>.
IF <F1> IS ASSIGNED.
  MOVE-CORRESPONDING <F1> TO LS_GOHEAD.
ENDIF.
UNASSIGN <F1>.

*Dates
IF LS_GOHEAD-BUDAT IS NOT INITIAL.
  LV_BUKRS = '1000'.
  CALL FUNCTION 'BAPI_COMPANYCODE_GET_PERIOD'
    EXPORTING
      COMPANYCODEID = LV_BUKRS
      POSTING_DATE  = LS_GOHEAD-BUDAT
    IMPORTING
      FISCAL_YEAR   = LV_GJAHR
*     FISCAL_PERIOD =
*     RETURN        =
    .
  CALL FUNCTION 'BAPI_CCODE_GET_FIRSTDAY_PERIOD'
    EXPORTING
      COMPANYCODEID       = LV_BUKRS
      FISCAL_PERIOD       = '01'
      FISCAL_YEAR         = LV_GJAHR
    IMPORTING
      FIRST_DAY_OF_PERIOD = LV_SDAT
*     RETURN              =
    .

  CALL FUNCTION 'BAPI_CCODE_GET_LASTDAY_FYEAR'
    EXPORTING
      COMPANYCODEID           = LV_BUKRS
      FISCAL_YEAR             = lv_gjahr
    IMPORTING
      LAST_DAY_OF_FISCAL_YEAR = LV_EDAT
*     RETURN                  =
    .

ENDIF.
* End of Dates
LV_ATNAM = 'ZVENDOR_BATCH'.

SELECT SINGLE ATINN INTO @LV_ATINN FROM CABN
                    WHERE ATNAM = @LV_ATNAM.

CALL FUNCTION 'CONVERSION_EXIT_ATINN_INPUT'
  EXPORTING
    INPUT  = LV_ATINN
  IMPORTING
    OUTPUT = LV_ATINN.

READ TABLE T_ALLAUSP INTO DATA(LS_AUSP) WITH KEY ATINN = LV_ATINN.
IF SY-SUBRC = 0.
  LV_REJ = 'R'.

  SELECT FROM AUSP AS A
        LEFT OUTER JOIN MCH1 AS B ON B~CUOBJ_BM = A~OBJEK
      FIELDS
      A~OBJEK,
      B~MATNR,
      B~CHARG
      WHERE A~ATWRT = @LS_AUSP-Atwrt
        AND B~MATNR = @LS_GOITEM-MATNR
        AND B~LIFNR = @LS_GOITEM-LIFNR
        AND B~ERSDA >= @LV_SDAT        "Fiscal year start date
        AND B~ERSDA <= @LV_EDAT        "Fiscal year end date
    INTO TABLE @DATA(LT_OBJEK).

  IF LT_OBJEK IS NOT INITIAL.
    SORT LT_OBJEK BY MATNR CHARG.
    SELECT * FROM QALSVE_V1 INTO TABLE @DATA(LT_QALSVE)
                    FOR ALL ENTRIES IN @LT_OBJEK
                        WHERE MATNR = @LT_OBJEK-MATNR
                          AND CHARG = @LT_OBJEK-CHARG
                          AND LIFNR = @LS_GOITEM-LIFNR
                          AND VBEWERTUNG = @LV_REJ.
    IF LT_QALSVE IS NOT INITIAL.
      MESSAGE E705(ZPP).
    ENDIF.

  ENDIF.
ENDIF.


*ENDIF.
